# 📘 1. Title Page

# 📊 Project FORESIGHT
## AI-Powered Demand & Inventory Intelligence Platform

### Notebook 01: Data Engineering & Validation

---

### 📌 Project Information

| Item | Details |
|---|---|
| **Author** | Mohit Kumar |
| **Internship** | Zidio Development |
| **Project Type** | End-to-End Data Analytics & Machine Learning Project |
| **Notebook Version** | 1.0 |
| **Status** | Completed |
| **Last Updated** | August 2026 |

------
# 🎯 2. Business Problem

Retail businesses operate in highly dynamic environments where customer demand fluctuates due to seasonality, promotions, holidays, pricing strategies, and changing consumer behavior. Inaccurate demand estimation often leads to two major business challenges:

- **Overstocking**, which increases inventory holding costs and ties up working capital.
- **Stockouts**, which result in lost sales, dissatisfied customers, and reduced customer satisfaction.

Traditional inventory planning methods often rely on historical averages or manual decision-making, making it difficult for retailers to respond quickly to changing demand patterns.

Project FORESIGHT aims to address these challenges by developing an AI-powered demand and inventory intelligence platform. The project combines data engineering, analytics, machine learning, and business intelligence to generate demand forecasts, monitor inventory health, identify stock-related risks, and support data-driven inventory decisions.

Building reliable analytical and forecasting models requires high-quality data. Therefore, the first objective of this project is to transform the raw M5 Forecasting datasets into clean, validated, and business-ready datasets, which is the primary purpose of this notebook.

----
> **💡 Key Takeaway**
>
> Effective demand forecasting and inventory management are fundamental to retail success. Project FORESIGHT addresses these challenges by building a data-driven platform that transforms raw retail data into actionable business intelligence.
---

# 🎯 3. Notebook Objective
The primary objective of this notebook is to build a robust data engineering pipeline that transforms the raw M5 Forecasting datasets into clean, validated, and business-ready datasets for downstream analytics and machine learning.

Specifically, this notebook will:

- Load the raw M5 datasets.
- Understand the structure and quality of each dataset.
- Perform data engineering and feature creation.
- Build standardized business-ready datasets.
- Validate the engineered datasets for consistency and accuracy.

Export the processed datasets for use in subsequent notebooks.
The datasets generated in this notebook will serve as the foundation for exploratory data analysis, feature engineering, demand forecasting, inventory intelligence, Power BI dashboard development, and Streamlit application deployment throughout Project FORESIGHT.


----
> **💡 Key Takeaway**
>
> The primary goal of Notebook 01 is to transform the raw M5 datasets into clean, validated, and business-ready datasets that will support all subsequent stages of Project FORESIGHT.
---

# 🔄 4. Project Workflow

Notebook 01 is the starting point of **Project FORESIGHT**. It transforms the raw M5 datasets into clean, validated, and business-ready datasets that serve as the foundation for all subsequent stages of the project.

## End-to-End Project Pipeline

```text
                           Project FORESIGHT

Raw M5 Retail Datasets
        │
        ▼
🛠️ Notebook 01
Data Engineering & Validation
(Create Business-Ready Datasets)
        │
        ▼
🔍 Notebook 02
Exploratory Data Analysis
(Understand Sales & Inventory Patterns)
        │
        ▼
⚡ Notebook 03
Feature Engineering
(Create Predictive Features)
        │
        ▼
📈 Notebook 04
Baseline Forecasting
(Build Statistical Forecasts)
        │
        ▼
🤖 Notebook 05
Machine Learning Forecasting
(Train & Optimize Forecasting Models)
        │
        ▼
📊 Notebook 06
Model Evaluation
(Compare & Select the Best Model)
        │
        ▼
📦 Notebook 07
Inventory Intelligence
(Generate Inventory Recommendations)
        │
        ▼
📉 Power BI Dashboard
(Interactive Business Intelligence)
        │
        ▼
🌐 Streamlit Web Application
(Decision Support Platform)
        │
        ▼
💼 Data-Driven Business Decisions
```

## 📦 Deliverables of Notebook 01

By the end of this notebook, the following business-ready datasets will be created:

- ✅ Sales Daily Dataset
- ✅ SKU Master Dataset
- ✅ Enhanced Calendar Dataset
- ✅ Inventory Snapshot Dataset

Additionally, all datasets will be:

- Clean
- Validated
- Business-ready
- Ready for analytics
- Ready for machine learning
- Ready for dashboard development

### 💾 Outputs Generated

Upon successful completion of Notebook 01, the following validated datasets will be available:

| Output | Description |
|---|---|
| `sales_daily_final.csv` | Daily SKU-level sales dataset prepared for analysis and forecasting |
| `calendar_final.csv` | Enhanced Calendar dimension containing engineered temporal, event, and SNAP attributes |
| `sku_master_final.csv` | Canonical SKU-store reference containing hierarchy, lifecycle, pricing, and estimated financial attributes |
| `inventory_snapshots_final.csv` | Simulated daily inventory dataset containing stock movements, replenishment activity, status, and inventory metrics |

The datasets are stored in the `data/processed/` directory and serve as the validated inputs for subsequent Project FORESIGHT notebooks.

---

> **💡 Key Takeaway**
>
> Notebook 01 establishes the validated analytical data foundation of Project FORESIGHT. The quality and reliability of every subsequent analysis, forecasting model, dashboard, and business recommendation depend on the datasets engineered, validated, and exported in this notebook.

# ⚙️ 5. Project Configuration

This section prepares the notebook environment to ensure a clean, consistent, and reproducible workflow throughout **Project FORESIGHT**.

The configuration performed in this section includes:

- Suppressing unnecessary warning messages
- Establishing notebook-wide settings
- Preparing the environment before importing project libraries

A properly configured notebook improves readability, minimizes distractions during analysis, and provides a consistent development experience.

In [1]:
# ============================================================
# Notebook Configuration
# Project: FORESIGHT
# ============================================================

# Suppress non-critical warning messages
import warnings

warnings.filterwarnings("ignore")

print("✅ Notebook environment configured successfully.")

✅ Notebook environment configured successfully.

### 📝 Configuration Summary

The notebook environment has now been configured successfully.

In this step, warning messages are suppressed to keep the notebook output clean and focused during data exploration and feature engineering. This improves readability while working with large datasets and multiple libraries.

> **Note:** Warning suppression does not resolve underlying issues. During development, important warnings should always be reviewed before deciding whether to suppress them.

# 📚 6. Import Required Libraries

This section imports and configures the Python libraries required for data manipulation, numerical operations, file-path management, and notebook display.

The libraries are organized by purpose to maintain a clear and consistent notebook structure.

In [2]:
# ============================================================
# Import Required Libraries
# Project: FORESIGHT
# ============================================================

# -----------------------------
# Standard Library
# -----------------------------
from pathlib import Path

# -----------------------------
# Data Manipulation
# -----------------------------
import pandas as pd
import numpy as np

# -----------------------------
# Notebook Utilities
# -----------------------------
from IPython.display import display

# ============================================================
# Display Configuration
# ============================================================

# Display all columns
pd.set_option("display.max_columns", None)

# Display up to 100 rows
pd.set_option("display.max_rows", 100)

# Set display width
pd.set_option("display.width", 120)

# Display floating-point values with two decimal places
pd.set_option("display.float_format", "{:.2f}".format)

print("✅ Section 6 completed: Required libraries imported successfully.")

✅ Section 6 completed: Required libraries imported successfully.

### 📝 Library Summary

The required Python libraries were successfully imported and configured for Notebook 01. Each library supports a specific aspect of the data engineering workflow.

| Library | Purpose |
|----------|---------|
| **pandas** | Data manipulation, cleaning, and transformation |
| **NumPy** | Numerical computations and array operations |
| **Pathlib** | File and directory management |
| **IPython.display** | Enhanced display of notebook outputs |

The notebook environment is now fully configured for the subsequent stages of Project FORESIGHT.

# 📂 7. Project Directory & File Paths

This section defines reusable project paths for source datasets and engineered outputs, ensuring consistent file access throughout Notebook 01.

This section will:

- identify the project root and data directories;
- define the source paths for the Sales, Calendar, and Selling Prices datasets;
- define the processed-data location for engineered outputs.

Using `pathlib.Path` keeps file-path handling readable and portable across operating systems.

In [3]:
# ============================================================
# Section 7: Project Directory & File Paths
# Project: FORESIGHT
# ============================================================

# Define the project root directory
PROJECT_ROOT = Path.cwd().parent

# Define data directories
RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DATA_DIR = PROJECT_ROOT / "data" / "processed"

# Define raw dataset file paths
SALES_FILE = RAW_DATA_DIR / "sales_train_validation.csv.gz"
CALENDAR_FILE = RAW_DATA_DIR / "calendar.csv"
PRICES_FILE = RAW_DATA_DIR / "sell_prices.csv.gz"

print("✅ Section 7 completed: Project directories and file paths configured successfully.")

✅ Section 7 completed: Project directories and file paths configured successfully.

### 📂 Directory Summary

The project directory structure has been successfully configured to support a consistent and organized data engineering workflow throughout Notebook 01.

| Directory | Purpose |
|-----------|---------|
| **data/raw/** | Stores the original M5 datasets used as notebook inputs. |
| **data/processed/** | Stores the engineered datasets generated by Notebook 01 for downstream analytics and forecasting. |
| **data/external/** | Reserved for additional external datasets that may be integrated into future stages of Project FORESIGHT. |

The project directory structure is now ready to support the remaining stages of the Project FORESIGHT pipeline.

> **💡 Key Takeaway:** Organizing datasets into dedicated directories for raw, processed, and external data improves project maintainability, reproducibility, and scalability by ensuring a clear separation between original and engineered data assets.

# 📊 8. Load Raw M5 Datasets

After configuring the project directories and file paths, the three original M5 datasets are loaded into Pandas DataFrames. These datasets provide the raw inputs required for exploration, quality assessment, and data engineering.

This section will:

- load the historical sales dataset;
- load the calendar and selling-prices datasets;
- confirm that all source datasets were loaded successfully.

> **📌 Note:** No cleaning or transformation is performed at this stage. The datasets are loaded in their original form for subsequent assessment.

In [4]:
# ============================================================
# Section 8: Load Raw M5 Datasets
# Project: FORESIGHT
# ============================================================

# Load the raw M5 datasets.

sales_df = pd.read_csv(SALES_FILE)
calendar_df = pd.read_csv(CALENDAR_FILE)
prices_df = pd.read_csv(PRICES_FILE)

# Display the loading summary.

print("✅ All raw M5 datasets loaded successfully.")
print(f"Sales dataset shape   : {sales_df.shape}")
print(f"Calendar dataset shape: {calendar_df.shape}")
print(f"Prices dataset shape  : {prices_df.shape}")

✅ All raw M5 datasets loaded successfully.
Sales dataset shape   : (30490, 1919)
Calendar dataset shape: (1969, 14)
Prices dataset shape  : (6841121, 4)

### 📊 Dataset Loading Summary

The three raw M5 datasets were successfully loaded into Pandas DataFrames using the configured source file paths.

| DataFrame | Source Dataset | Purpose |
|-----------|----------------|---------|
| **`sales_df`** | `sales_train_validation.csv` | Contains historical daily unit sales across products and stores. |
| **`calendar_df`** | `calendar.csv` | Contains dates, events, calendar attributes, and SNAP indicators. |
| **`prices_df`** | `sell_prices.csv` | Contains weekly selling prices for item-store combinations. |

> **💡 Key Takeaway:** The datasets remain unchanged from their original source files at this stage. Cleaning, transformation, and feature engineering will be performed only after completing the initial exploration and quality assessment.

# 🔍 9. Source Data Understanding

Understanding the raw datasets is the first step in the analytics workflow. Before assessing data quality or performing data engineering, it is essential to understand each dataset's structure, business purpose, and relationships.

In this section, we will:

- Explore the Sales dataset.
- Explore the Calendar dataset.
- Explore the Selling Prices dataset.
- Examine how the datasets are connected.

This understanding provides the foundation for the data quality assessment and engineering tasks in the following sections.

> **📌 Note:** This section focuses only on understanding the raw datasets. No cleaning, validation, or transformation is performed.

## 📦 9.1 Sales Dataset Overview

The Sales dataset contains historical daily demand for 30,490 item-store combinations.

Each row represents one item-store series, while columns `d_1` through `d_1913` contain daily units sold. This section reviews the dataset’s dimensions, schema, identifiers, and business role before quality assessment.

In this subsection, we will:

- Preview the dataset.
- Examine its dimensions.
- Review its schema.
- Understand its business context.

### 9.1.1 Dataset Preview & Dimensions

Previewing the dataset and examining its dimensions provide an initial understanding of its structure and scale. These checks verify that the data has been loaded correctly and establish the foundation for subsequent schema inspection.

In [5]:
# ============================================================
# 9.1.1 Dataset Preview & Dimensions
# ============================================================

# Display the first five rows of the dataset
display(sales_df.head())

print("\n" + "=" * 80 + "\n")

# Display dataset dimensions
print(f"Number of Rows    : {sales_df.shape[0]:,}")
print(f"Number of Columns : {sales_df.shape[1]}")

print("\n" + "=" * 80 + "\n")

print("✅ Sales dataset preview and dimensions displayed successfully.")

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,d_5,d_6,d_7,d_8,d_9,d_10,d_11,d_12,d_13,d_14,d_15,d_16,d_17,d_18,d_19,d_20,d_21,d_22,d_23,d_24,d_25,d_26,d_27,d_28,d_29,d_30,d_31,d_32,d_33,d_34,d_35,d_36,d_37,d_38,d_39,d_40,d_41,d_42,d_43,d_44,d_45,d_46,d_47,d_48,d_49,d_50,d_51,d_52,d_53,d_54,d_55,d_56,d_57,d_58,d_59,d_60,d_61,d_62,d_63,d_64,d_65,d_66,d_67,d_68,d_69,d_70,d_71,d_72,d_73,d_74,d_75,d_76,d_77,d_78,d_79,d_80,d_81,d_82,d_83,d_84,d_85,d_86,d_87,d_88,d_89,d_90,d_91,d_92,d_93,d_94,d_95,d_96,d_97,d_98,d_99,d_100,d_101,d_102,d_103,d_104,d_105,d_106,d_107,d_108,d_109,d_110,d_111,d_112,d_113,d_114,d_115,d_116,d_117,d_118,d_119,d_120,d_121,d_122,d_123,d_124,d_125,d_126,d_127,d_128,d_129,d_130,d_131,d_132,d_133,d_134,d_135,d_136,d_137,d_138,d_139,d_140,d_141,d_142,d_143,d_144,d_145,d_146,d_147,d_148,d_149,d_150,d_151,d_152,d_153,d_154,d_155,d_156,d_157,d_158,d_159,d_160,d_161,d_162,d_163,d_164,d_165,d_166,d_167,d_168,d_169,d_170,d_171,d_172,d_173,d_174,d_175,d_176,d_177,d_178,d_179,d_180,d_181,d_182,d_183,d_184,d_185,d_186,d_187,d_188,d_189,d_190,d_191,d_192,d_193,d_194,d_195,d_196,d_197,d_198,d_199,d_200,d_201,d_202,d_203,d_204,d_205,d_206,d_207,d_208,d_209,d_210,d_211,d_212,d_213,d_214,d_215,d_216,d_217,d_218,d_219,d_220,d_221,d_222,d_223,d_224,d_225,d_226,d_227,d_228,d_229,d_230,d_231,d_232,d_233,d_234,d_235,d_236,d_237,d_238,d_239,d_240,d_241,d_242,d_243,d_244,d_245,d_246,d_247,d_248,d_249,d_250,d_251,d_252,d_253,d_254,d_255,d_256,d_257,d_258,d_259,d_260,d_261,d_262,d_263,d_264,d_265,d_266,d_267,d_268,d_269,d_270,d_271,d_272,d_273,d_274,d_275,d_276,d_277,d_278,d_279,d_280,d_281,d_282,d_283,d_284,d_285,d_286,d_287,d_288,d_289,d_290,d_291,d_292,d_293,d_294,d_295,d_296,d_297,d_298,d_299,d_300,d_301,d_302,d_303,d_304,d_305,d_306,d_307,d_308,d_309,d_310,d_311,d_312,d_313,d_314,d_315,d_316,d_317,d_318,d_319,d_320,d_321,d_322,d_323,d_324,d_325,d_326,d_327,d_328,d_329,d_330,d_331,d_332,d_333,d_334,d_335,d_336,d_337,d_338,d_339,d_340,d_341,d_342,d_343,d_344,d_345,d_346,d_347,d_348,d_349,d_350,d_351,d_352,d_353,d_354,d_355,d_356,d_357,d_358,d_359,d_360,d_361,d_362,d_363,d_364,d_365,d_366,d_367,d_368,d_369,d_370,d_371,d_372,d_373,d_374,d_375,d_376,d_377,d_378,d_379,d_380,d_381,d_382,d_383,d_384,d_385,d_386,d_387,d_388,d_389,d_390,d_391,d_392,d_393,d_394,d_395,d_396,d_397,d_398,d_399,d_400,d_401,d_402,d_403,d_404,d_405,d_406,d_407,d_408,d_409,d_410,d_411,d_412,d_413,d_414,d_415,d_416,d_417,d_418,d_419,d_420,d_421,d_422,d_423,d_424,d_425,d_426,d_427,d_428,d_429,d_430,d_431,d_432,d_433,d_434,d_435,d_436,d_437,d_438,d_439,d_440,d_441,d_442,d_443,d_444,d_445,d_446,d_447,d_448,d_449,d_450,d_451,d_452,d_453,d_454,d_455,d_456,d_457,d_458,d_459,d_460,d_461,d_462,d_463,d_464,d_465,d_466,d_467,d_468,d_469,d_470,d_471,d_472,d_473,d_474,d_475,d_476,d_477,d_478,d_479,d_480,d_481,d_482,d_483,d_484,d_485,d_486,d_487,d_488,d_489,d_490,d_491,d_492,d_493,d_494,d_495,d_496,d_497,d_498,d_499,d_500,d_501,d_502,d_503,d_504,d_505,d_506,d_507,d_508,d_509,d_510,d_511,d_512,d_513,d_514,d_515,d_516,d_517,d_518,d_519,d_520,d_521,d_522,d_523,d_524,d_525,d_526,d_527,d_528,d_529,d_530,d_531,d_532,d_533,d_534,d_535,d_536,d_537,d_538,d_539,d_540,d_541,d_542,d_543,d_544,d_545,d_546,d_547,d_548,d_549,d_550,d_551,d_552,d_553,d_554,d_555,d_556,d_557,d_558,d_559,d_560,d_561,d_562,d_563,d_564,d_565,d_566,d_567,d_568,d_569,d_570,d_571,d_572,d_573,d_574,d_575,d_576,d_577,d_578,d_579,d_580,d_581,d_582,d_583,d_584,d_585,d_586,d_587,d_588,d_589,d_590,d_591,d_592,d_593,d_594,d_595,d_596,d_597,d_598,d_599,d_600,d_601,d_602,d_603,d_604,d_605,d_606,d_607,d_608,d_609,d_610,d_611,d_612,d_613,d_614,d_615,d_616,d_617,d_618,d_619,d_620,d_621,d_622,d_623,d_624,d_625,d_626,d_627,d_628,d_629,d_630,d_631,d_632,d_633,d_634,d_635,d_636,d_637,d_638,d_639,d_640,d_641,d_642,d_643,d_644,d_645,d_646,d_647,d_648,d_649,d_650,d_651,d_652,d_653,d_654,d_655,d_656,d_657,d_658,d_659,d_660,d_661,d_662,d_663,d_664,d_665,d_666,d_667,d_668,d_669,d_670,d_671,d_672,d_673,d_674,d_675,d_676,d_677,d_678,d_679,d_680,d_681,d_682,d_683,d_684,d_685,d_686,d_687,d_688,d_689,d_690,d_691,d_692,d_693,d_694,d_695,d_696,d_697,d_698,d_699,d_700,d_701,d_702,d_703,d_704,d_705,d_706,d_707,d_708,d_709,d_710,d_711,d_712,d_713,d_714,d_715,d_716,d_717,d_718,d_719,d_720,d_721,d_722,d_723,d_724,d_725,d_726,d_727,d_728,d_729,d_730,d_731,d_732,d_733,d_734,d_735,d_736,d_737,d_738,d_739,d_740,d_741,d_742,d_743,d_744,d_745,d_746,d_747,d_748,d_749,d_750,d_751,d_752,d_753,d_754,d_755,d_756,d_757,d_758,d_759,d_760,d_761,d_762,d_763,d_764,d_765,d_766,d_767,d_768,d_769,d_770,d_771,d_772,d_773,d_774,d_775,d_776,d_777,d_778,d_779,d_780,d_781,d_782,d_783,d_784,d_785,d_786,d_787,d_788,d_789,d_790,d_791,d_792,d_793,d_794,d_795,d_796,d_797,d_798,d_799,d_800,d_801,d_802,d_803,d_804,d_805,d_806,d_807,d_808,d_809,d_810,d_811,d_812,d_813,d_814,d_815,d_816,d_817,d_818,d_819,d_820,d_821,d_822,d_823,d_824,d_825,d_826,d_827,d_828,d_829,d_830,d_831,d_832,d_833,d_834,d_835,d_836,d_837,d_838,d_839,d_840,d_841,d_842,d_843,d_844,d_845,d_846,d_847,d_848,d_849,d_850,d_851,d_852,d_853,d_854,d_855,d_856,d_857,d_858,d_859,d_860,d_861,d_862,d_863,d_864,d_865,d_866,d_867,d_868,d_869,d_870,d_871,d_872,d_873,d_874,d_875,d_876,d_877,d_878,d_879,d_880,d_881,d_882,d_883,d_884,d_885,d_886,d_887,d_888,d_889,d_890,d_891,d_892,d_893,d_894,d_895,d_896,d_897,d_898,d_899,d_900,d_901,d_902,d_903,d_904,d_905,d_906,d_907,d_908,d_909,d_910,d_911,d_912,d_913,d_914,d_915,d_916,d_917,d_918,d_919,d_920,d_921,d_922,d_923,d_924,d_925,d_926,d_927,d_928,d_929,d_930,d_931,d_932,d_933,d_934,d_935,d_936,d_937,d_938,d_939,d_940,d_941,d_942,d_943,d_944,d_945,d_946,d_947,d_948,d_949,d_950,d_951,d_952,d_953,d_954,d_955,d_956,d_957,d_958,d_959,d_960,d_961,d_962,d_963,d_964,d_965,d_966,d_967,d_968,d_969,d_970,d_971,d_972,d_973,d_974,d_975,d_976,d_977,d_978,d_979,d_980,d_981,d_982,d_983,d_984,d_985,d_986,d_987,d_988,d_989,d_990,d_991,d_992,d_993,d_994,d_995,d_996,d_997,d_998,d_999,d_1000,d_1001,d_1002,d_1003,d_1004,d_1005,d_1006,d_1007,d_1008,d_1009,d_1010,d_1011,d_1012,d_1013,d_1014,d_1015,d_1016,d_1017,d_1018,d_1019,d_1020,d_1021,d_1022,d_1023,d_1024,d_1025,d_1026,d_1027,d_1028,d_1029,d_1030,d_1031,d_1032,d_1033,d_1034,d_1035,d_1036,d_1037,d_1038,d_1039,d_1040,d_1041,d_1042,d_1043,d_1044,d_1045,d_1046,d_1047,d_1048,d_1049,d_1050,d_1051,d_1052,d_1053,d_1054,d_1055,d_1056,d_1057,d_1058,d_1059,d_1060,d_1061,d_1062,d_1063,d_1064,d_1065,d_1066,d_1067,d_1068,d_1069,d_1070,d_1071,d_1072,d_1073,d_1074,d_1075,d_1076,d_1077,d_1078,d_1079,d_1080,d_1081,d_1082,d_1083,d_1084,d_1085,d_1086,d_1087,d_1088,d_1089,d_1090,d_1091,d_1092,d_1093,d_1094,d_1095,d_1096,d_1097,d_1098,d_1099,d_1100,d_1101,d_1102,d_1103,d_1104,d_1105,d_1106,d_1107,d_1108,d_1109,d_1110,d_1111,d_1112,d_1113,d_1114,d_1115,d_1116,d_1117,d_1118,d_1119,d_1120,d_1121,d_1122,d_1123,d_1124,d_1125,d_1126,d_1127,d_1128,d_1129,d_1130,d_1131,d_1132,d_1133,d_1134,d_1135,d_1136,d_1137,d_1138,d_1139,d_1140,d_1141,d_1142,d_1143,d_1144,d_1145,d_1146,d_1147,d_1148,d_1149,d_1150,d_1151,d_1152,d_1153,d_1154,d_1155,d_1156,d_1157,d_1158,d_1159,d_1160,d_1161,d_1162,d_1163,d_1164,d_1165,d_1166,d_1167,d_1168,d_1169,d_1170,d_1171,d_1172,d_1173,d_1174,d_1175,d_1176,d_1177,d_1178,d_1179,d_1180,d_1181,d_1182,d_1183,d_1184,d_1185,d_1186,d_1187,d_1188,d_1189,d_1190,d_1191,d_1192,d_1193,d_1194,d_1195,d_1196,d_1197,d_1198,d_1199,d_1200,d_1201,d_1202,d_1203,d_1204,d_1205,d_1206,d_1207,d_1208,d_1209,d_1210,d_1211,d_1212,d_1213,d_1214,d_1215,d_1216,d_1217,d_1218,d_1219,d_1220,d_1221,d_1222,d_1223,d_1224,d_1225,d_1226,d_1227,d_1228,d_1229,d_1230,d_1231,d_1232,d_1233,d_1234,d_1235,d_1236,d_1237,d_1238,d_1239,d_1240,d_1241,d_1242,d_1243,d_1244,d_1245,d_1246,d_1247,d_1248,d_1249,d_1250,d_1251,d_1252,d_1253,d_1254,d_1255,d_1256,d_1257,d_1258,d_1259,d_1260,d_1261,d_1262,d_1263,d_1264,d_1265,d_1266,d_1267,d_1268,d_1269,d_1270,d_1271,d_1272,d_1273,d_1274,d_1275,d_1276,d_1277,d_1278,d_1279,d_1280,d_1281,d_1282,d_1283,d_1284,d_1285,d_1286,d_1287,d_1288,d_1289,d_1290,d_1291,d_1292,d_1293,d_1294,d_1295,d_1296,d_1297,d_1298,d_1299,d_1300,d_1301,d_1302,d_1303,d_1304,d_1305,d_1306,d_1307,d_1308,d_1309,d_1310,d_1311,d_1312,d_1313,d_1314,d_1315,d_1316,d_1317,d_1318,d_1319,d_1320,d_1321,d_1322,d_1323,d_1324,d_1325,d_1326,d_1327,d_1328,d_1329,d_1330,d_1331,d_1332,d_1333,d_1334,d_1335,d_1336,d_1337,d_1338,d_1339,d_1340,d_1341,d_1342,d_1343,d_1344,d_1345,d_1346,d_1347,d_1348,d_1349,d_1350,d_1351,d_1352,d_1353,d_1354,d_1355,d_1356,d_1357,d_1358,d_1359,d_1360,d_1361,d_1362,d_1363,d_1364,d_1365,d_1366,d_1367,d_1368,d_1369,d_1370,d_1371,d_1372,d_1373,d_1374,d_1375,d_1376,d_1377,d_1378,d_1379,d_1380,d_1381,d_1382,d_1383,d_1384,d_1385,d_1386,d_1387,d_1388,d_1389,d_1390,d_1391,d_1392,d_1393,d_1394,d_1395,d_1396,d_1397,d_1398,d_1399,d_1400,d_1401,d_1402,d_1403,d_1404,d_1405,d_1406,d_1407,d_1408,d_1409,d_1410,d_1411,d_1412,d_1413,d_1414,d_1415,d_1416,d_1417,d_1418,d_1419,d_1420,d_1421,d_1422,d_1423,d_1424,d_1425,d_1426,d_1427,d_1428,d_1429,d_1430,d_1431,d_1432,d_1433,d_1434,d_1435,d_1436,d_1437,d_1438,d_1439,d_1440,d_1441,d_1442,d_1443,d_1444,d_1445,d_1446,d_1447,d_1448,d_1449,d_1450,d_1451,d_1452,d_1453,d_1454,d_1455,d_1456,d_1457,d_1458,d_1459,d_1460,d_1461,d_1462,d_1463,d_1464,d_1465,d_1466,d_1467,d_1468,d_1469,d_1470,d_1471,d_1472,d_1473,d_1474,d_1475,d_1476,d_1477,d_1478,d_1479,d_1480,d_1481,d_1482,d_1483,d_1484,d_1485,d_1486,d_1487,d_1488,d_1489,d_1490,d_1491,d_1492,d_1493,d_1494,d_1495,d_1496,d_1497,d_1498,d_1499,d_1500,d_1501,d_1502,d_1503,d_1504,d_1505,d_1506,d_1507,d_1508,d_1509,d_1510,d_1511,d_1512,d_1513,d_1514,d_1515,d_1516,d_1517,d_1518,d_1519,d_1520,d_1521,d_1522,d_1523,d_1524,d_1525,d_1526,d_1527,d_1528,d_1529,d_1530,d_1531,d_1532,d_1533,d_1534,d_1535,d_1536,d_1537,d_1538,d_1539,d_1540,d_1541,d_1542,d_1543,d_1544,d_1545,d_1546,d_1547,d_1548,d_1549,d_1550,d_1551,d_1552,d_1553,d_1554,d_1555,d_1556,d_1557,d_1558,d_1559,d_1560,d_1561,d_1562,d_1563,d_1564,d_1565,d_1566,d_1567,d_1568,d_1569,d_1570,d_1571,d_1572,d_1573,d_1574,d_1575,d_1576,d_1577,d_1578,d_1579,d_1580,d_1581,d_1582,d_1583,d_1584,d_1585,d_1586,d_1587,d_1588,d_1589,d_1590,d_1591,d_1592,d_1593,d_1594,d_1595,d_1596,d_1597,d_1598,d_1599,d_1600,d_1601,d_1602,d_1603,d_1604,d_1605,d_1606,d_1607,d_1608,d_1609,d_1610,d_1611,d_1612,d_1613,d_1614,d_1615,d_1616,d_1617,d_1618,d_1619,d_1620,d_1621,d_1622,d_1623,d_1624,d_1625,d_1626,d_1627,d_1628,d_1629,d_1630,d_1631,d_1632,d_1633,d_1634,d_1635,d_1636,d_1637,d_1638,d_1639,d_1640,d_1641,d_1642,d_1643,d_1644,d_1645,d_1646,d_1647,d_1648,d_1649,d_1650,d_1651,d_1652,d_1653,d_1654,d_1655,d_1656,d_1657,d_1658,d_1659,d_1660,d_1661,d_1662,d_1663,d_1664,d_1665,d_1666,d_1667,d_1668,d_1669,d_1670,d_1671,d_1672,d_1673,d_1674,d_1675,d_1676,d_1677,d_1678,d_1679,d_1680,d_1681,d_1682,d_1683,d_1684,d_1685,d_1686,d_1687,d_1688,d_1689,d_1690,d_1691,d_1692,d_1693,d_1694,d_1695,d_1696,d_1697,d_1698,d_1699,d_1700,d_1701,d_1702,d_1703,d_1704,d_1705,d_1706,d_1707,d_1708,d_1709,d_1710,d_1711,d_1712,d_1713,d_1714,d_1715,d_1716,d_1717,d_1718,d_1719,d_1720,d_1721,d_1722,d_1723,d_1724,d_1725,d_1726,d_1727,d_1728,d_1729,d_1730,d_1731,d_1732,d_1733,d_1734,d_1735,d_1736,d_1737,d_1738,d_1739,d_1740,d_1741,d_1742,d_1743,d_1744,d_1745,d_1746,d_1747,d_1748,d_1749,d_1750,d_1751,d_1752,d_1753,d_1754,d_1755,d_1756,d_1757,d_1758,d_1759,d_1760,d_1761,d_1762,d_1763,d_1764,d_1765,d_1766,d_1767,d_1768,d_1769,d_1770,d_1771,d_1772,d_1773,d_1774,d_1775,d_1776,d_1777,d_1778,d_1779,d_1780,d_1781,d_1782,d_1783,d_1784,d_1785,d_1786,d_1787,d_1788,d_1789,d_1790,d_1791,d_1792,d_1793,d_1794,d_1795,d_1796,d_1797,d_1798,d_1799,d_1800,d_1801,d_1802,d_1803,d_1804,d_1805,d_1806,d_1807,d_1808,d_1809,d_1810,d_1811,d_1812,d_1813,d_1814,d_1815,d_1816,d_1817,d_1818,d_1819,d_1820,d_1821,d_1822,d_1823,d_1824,d_1825,d_1826,d_1827,d_1828,d_1829,d_1830,d_1831,d_1832,d_1833,d_1834,d_1835,d_1836,d_1837,d_1838,d_1839,d_1840,d_1841,d_1842,d_1843,d_1844,d_1845,d_1846,d_1847,d_1848,d_1849,d_1850,d_1851,d_1852,d_1853,d_1854,d_1855,d_1856,d_1857,d_1858,d_1859,d_1860,d_1861,d_1862,d_1863,d_1864,d_1865,d_1866,d_1867,d_1868,d_1869,d_1870,d_1871,d_1872,d_1873,d_1874,d_1875,d_1876,d_1877,d_1878,d_1879,d_1880,d_1881,d_1882,d_1883,d_1884,d_1885,d_1886,d_1887,d_1888,d_1889,d_1890,d_1891,d_1892,d_1893,d_1894,d_1895,d_1896,d_1897,d_1898,d_1899,d_1900,d_1901,d_1902,d_1903,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,1,1,0,0,0,0,0,1,2,1,0,1,1,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,2,1,0,0,0,2,0,0,0,0,0,1,0,0,0,1,0,1,2,1,1,0,0,0,0,1,0,0,1,2,0,1,0,0,1,0,1,0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,2,2,0,1,1,0,0,0,1,1,0,1,1,1,1,0,2,3,1,1,0,0,0,0,0,1,0,0,0,0,2,1,0,0,1,1,2,1,1,0,1,0,1,1,0,1,1,0,3,0,0,3,0,1,1,2,0,1,1,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,2,0,0,1,0,2,0,0,0,0,0,0,1,0,1,0,1,1,0,0,0,0,0,1,0,0,0,0,0,1,2,0,0,0,0,0,0,1,2,0,0,0,2,1,2,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,1,1,1,0,2,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,0,0,0,1,1,2,0,1,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,2,0,0,1,0,0,0,1,0,1,0,0,0,0,1,0,1,0,1,0,0,1,0,0,1,1,2,0,1,0,0,0,0,0,0,0,0,3,1,2,2,1,1,0,0,2,0,0,0,0,1,0,1,0,0,0,1,1,0,3,1,0,0,0,0,0,1,0,1,1,1,0,0,0,0,2,0,0,2,0,0,0,1,0,0,0,0,0,4,0,0,2,1,0,0,0,0,0,1,0,0,0,0,0,4,0,1,0,1,2,2,0,0,0,0,2,1,1,1,1,1,0,0,1,0,0,1,0,0,0,1,1,0,1,2,0,0,2,0,1,3,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,1,0,1,1,0,1,1,0,0,1,1,1,0,0,0,0,0,2,0,0,0,0,3,0,2,0,0,0,0,3,2,0,2,0,0,2,0,0,0,0,3,0,1,1,1,0,1,0,1,0,0,2,4,0,0,0,0,0,2,0,0,1,0,0,1,1,5,1,1,0,0,0,0,0,0,0,0,2,1,1,0,2,0,2,1,0,1,0,1,1,0,0,0,2,1,1,0,0,1,0,3,0,0,0,1,0,0,2,1,0,1,0,0,3,3,0,0,0,0,0,0,0,1,1,1,0,2,2,2,0,0,1,0,0,1,3,0,0,0,1,1,0,1,0,1,0,0,1,1,1,2,1,1,1,0,2,2,2,1,0,0,0,1,2,0,0,1,2,1,1,1,0,1,0,1,0,0,1,0,1,0,2,1,0,2,0,1,0,0,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,3,1,1,0,1,1,0,0,0,1,1,2,0,0,0,1,0,2,1,0,1,1,0,0,0,1,1,1,3,1,1,0,0,2,0,1,0,0,0,2,0,0,0,4,2,1,0,0,0,0,2,1,0,1,1,0,0,0,1,2,1,1,0,0,2,0,2,2,0,0,0,1,1,0,2,0,1,1,2,0,1,0,0,0,2,1,0,1,1,2,0,0,0,0,0,0,0,1,0,1,0,1,0,3,1,1,0,1,1,2,0,0,0,0,1,1,0,0,0,0,3,0,1,0,0,0,0,1,1,1,0,1,0,2,0,0,0,0,2,0,0,0,0,1,1,2,0,0,0,0,2,0,0,1,1,1,1,0,0,0,0,0,1,2,2,0,1,0,0,0,0,1,2,1,0,0,0,0,0,1,0,3,0,1,2,1,0,3,0,0,0,1,0,2,2,1,0,0,1,2,0,1,0,1,4,0,0,5,0,0,0,0,0,0,2,1,2,1,0,0,0,1,1,1,0,0,1,1,1,1,1,0,0,0,2,2,0,0,1,4,0,0,0,0,1,1,2,0,4,0,1,0,1,4,2,0,2,0,1,1,0,1,0,0,1,1,3,0,0,0,1,1,1,3,1,3,1,2,2,0,1,1,1,1,0,0,0,0,0,1,0,4,2,3,0,1,2,0,0,0,1,1,3,0,1,1,1,3,0,1,1

================================================================================

Number of Rows    : 30,490
Number of Columns : 1919

================================================================================

✅ Sales dataset preview and dimensions displayed successfully.

### 9.1.2 Schema Inspection (Columns & Data Types)

Schema inspection provides an overview of the dataset's columns, data types, non-null values, and memory usage. This helps verify the dataset structure and understand how the information is organized before further analysis.

> **📌 Note:** This subsection inspects the dataset schema only. Data quality assessment and transformations are performed in later sections.

In [6]:
# ============================================================
# 9.1.2 Schema Inspection (Columns & Data Types)
# ============================================================

# Display column names
print("Column Names:\n")
print(sales_df.columns)

print("\n" + "=" * 80 + "\n")

# Display dataset schema
sales_df.info()

print("\n" + "=" * 80 + "\n")

print("✅ Sales dataset schema displayed successfully.")

Column Names:

Index(['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'd_1', 'd_2', 'd_3', 'd_4',
       ...
       'd_1904', 'd_1905', 'd_1906', 'd_1907', 'd_1908', 'd_1909', 'd_1910', 'd_1911', 'd_1912', 'd_1913'],
      dtype='str', length=1919)

================================================================================

<class 'pandas.DataFrame'>
RangeIndex: 30490 entries, 0 to 30489
Columns: 1919 entries, id to d_1913
dtypes: int64(1913), str(6)
memory usage: 448.2 MB

================================================================================

✅ Sales dataset schema displayed successfully.

### 9.1.3 Business Context

The Sales dataset captures the historical demand for products sold across multiple stores. Each row represents a unique product-store combination, while the daily columns (`d_1` to `d_1913`) record the number of units sold each day.

The first six columns describe the product and store:

- **id** – Unique identifier for each product-store combination.
- **item_id** – Product identifier.
- **dept_id** – Product department.
- **cat_id** – Product category.
- **store_id** – Store identifier.
- **state_id** – State identifier.

The remaining **1,913** columns contain the daily sales history, forming a wide-format time-series dataset that will later be transformed into a long-format dataset for feature engineering and forecasting.

> **📌 Business Importance:** Historical sales data enables demand forecasting, inventory optimization, and data-driven supply chain planning.

### 9.1.4 Key Observations

The initial exploration reveals the following:

- The dataset contains **30,490** product-store combinations.
- It consists of **1,919 columns**, including **6 identifier columns** and **1,913 daily sales columns** (`d_1`–`d_1913`).
- Identifier columns use the **`str`** data type, while daily sales values are stored as **`int64`**.
- The dataset follows a **wide-format time-series structure**.
- It serves as the primary source for demand forecasting and will later be reshaped into a long-format dataset for analysis and feature engineering.

## 📦 Sales Dataset Summary

The Sales dataset is the primary source of historical demand information in the M5 Forecasting project. Understanding its structure, schema, and business context establishes the foundation for data quality assessment, feature engineering, and demand forecasting.

> **💡 Key Takeaway:** A clear understanding of the raw dataset is essential before performing any validation, transformation, or analysis.

## 📅 9.2 Calendar Dataset Overview

The Calendar dataset maps encoded sales days to actual dates and provides temporal, event, and SNAP information.

This section reviews its dimensions, schema, key fields, and role in explaining seasonality and other time-based demand patterns.

In this subsection, we will:

- Preview the dataset.
- Examine its dimensions.
- Review its schema.
- Understand its business context.

### 9.2.1 Dataset Preview & Dimensions

Previewing the dataset and examining its dimensions provide an initial understanding of its structure and scale. These checks verify that the data has been loaded correctly and prepare us for schema inspection.

In [7]:
# ============================================================
# 9.2.1 Dataset Preview & Dimensions
# ============================================================

# Display the first five rows of the dataset
display(calendar_df.head())

print("\n" + "=" * 80 + "\n")

# Display dataset dimensions
print(f"Number of Rows    : {calendar_df.shape[0]:,}")
print(f"Number of Columns : {calendar_df.shape[1]}")

print("\n" + "=" * 80 + "\n")

print("✅ Calendar dataset preview and dimensions displayed successfully.")

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1

================================================================================

Number of Rows    : 1,969
Number of Columns : 14

================================================================================

✅ Calendar dataset preview and dimensions displayed successfully.

### 9.2.2 Schema Inspection (Columns & Data Types)

Schema inspection provides an overview of the dataset's columns, data types, non-null values, and memory usage. This helps verify the dataset structure and understand how the calendar information is organized before further analysis.

> **📌 Note:** This subsection inspects the dataset schema only. Data quality assessment and transformations are performed in later sections.

In [8]:
# ============================================================
# 9.2.2 Schema Inspection (Columns & Data Types)
# ============================================================

# Display column names
print("Column Names:\n")
print(calendar_df.columns)

print("\n" + "=" * 80 + "\n")

# Display dataset schema
calendar_df.info()

print("\n" + "=" * 80 + "\n")

print("✅ Calendar dataset schema displayed successfully.")

Column Names:

Index(['date', 'wm_yr_wk', 'weekday', 'wday', 'month', 'year', 'd', 'event_name_1', 'event_type_1', 'event_name_2',
       'event_type_2', 'snap_CA', 'snap_TX', 'snap_WI'],
      dtype='str')

================================================================================

<class 'pandas.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1969 non-null   str
 1   wm_yr_wk      1969 non-null   int64
 2   weekday       1969 non-null   str
 3   wday          1969 non-null   int64
 4   month         1969 non-null   int64
 5   year          1969 non-null   int64
 6   d             1969 non-null   str
 7   event_name_1  162 non-null    str
 8   event_type_1  162 non-null    str
 9   event_name_2  5 non-null      str
 10  event_type_2  5 non-null      str
 11  snap_CA       1969 non-null   int64
 12  snap_TX       1969 non-null   int64
 13  snap_WI       1969 non-null   int64
dtypes: int64(7), str(7)
memory usage: 263.1 KB

================================================================================

✅ Calendar dataset schema displayed successfully.

### 9.2.3 Business Context

The Calendar dataset provides the temporal context for historical sales data. While the Sales dataset records **what** was sold, the Calendar dataset explains **when** the sales occurred and identifies external factors that may influence demand.

The dataset can be understood through three logical groups:

#### 1. Calendar Attributes

The calendar-related columns (`date`, `wm_yr_wk`, `weekday`, `wday`, `month`, `year`, and `d`) map encoded day identifiers to actual calendar dates, enabling the extraction of time-based features.

#### 2. Event Information

The event-related columns (`event_name_1`, `event_type_1`, `event_name_2`, and `event_type_2`) capture holidays, cultural celebrations, sporting events, and other special occasions that may influence customer purchasing behavior.

#### 3. SNAP Indicators

The SNAP columns (`snap_CA`, `snap_TX`, and `snap_WI`) indicate whether the Supplemental Nutrition Assistance Program (SNAP) was active in California, Texas, and Wisconsin, providing additional socioeconomic context for demand forecasting.

> **📌 Business Importance:** Calendar information enables forecasting models to capture seasonality, holiday effects, and other time-based demand patterns.

### 9.2.4 Key Observations

The initial exploration reveals the following:

- The dataset contains **1,969 records** and **14 columns**.
- It consists of **7 `str` columns** and **7 `int64` columns**.
- The encoded day identifier (`d`) links the Calendar dataset with the Sales dataset.
- The dataset captures calendar attributes, events, and SNAP indicators that provide valuable context for demand forecasting.
- It serves as the temporal backbone of the forecasting pipeline and supports the creation of time-based features.

## 📅 Calendar Dataset Summary

The Calendar dataset provides the temporal and contextual information required to interpret historical sales data. Understanding its structure and business context establishes the foundation for time-based feature engineering and demand forecasting.

> **💡 Key Takeaway:** Calendar information enriches historical sales data with seasonality, events, and socioeconomic context, enabling more accurate demand forecasting.

## 💲 9.3 Selling Prices Dataset Overview

The Selling Prices dataset contains weekly item-store pricing records aligned through the retail-week identifier `wm_yr_wk`.

This section reviews its dimensions, schema, business keys, and role in pricing analysis and demand forecasting.

### 9.3.1 Dataset Preview & Dimensions

Previewing the dataset and examining its dimensions provide an initial understanding of its structure and scale. These checks verify that the data has been loaded correctly and prepare us for schema inspection.

In [9]:
# ============================================================
# 9.3.1 Dataset Preview & Dimensions
# ============================================================

# Display the first five rows of the dataset
display(prices_df.head())

print("\n" + "=" * 80 + "\n")

# Display dataset dimensions
print(f"Number of Rows    : {prices_df.shape[0]:,}")
print(f"Number of Columns : {prices_df.shape[1]}")

print("\n" + "=" * 80 + "\n")

print("✅ Selling Prices dataset preview and dimensions displayed successfully.")

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

================================================================================

Number of Rows    : 6,841,121
Number of Columns : 4

================================================================================

✅ Selling Prices dataset preview and dimensions displayed successfully.

### 9.3.2 Schema Inspection (Columns & Data Types)

Schema inspection provides an overview of the dataset's columns, data types, non-null values, and memory usage. This helps verify the dataset structure and understand how pricing information is organized before further analysis.

> **📌 Note:** This subsection inspects the dataset schema only. Data quality assessment and transformations are performed in later sections.

In [10]:
# ============================================================
# 9.3.2 Schema Inspection (Columns & Data Types)
# ============================================================

# Display column names
print("Column Names:\n")
print(prices_df.columns)

print("\n" + "=" * 80 + "\n")

# Display dataset schema
prices_df.info()

print("\n" + "=" * 80 + "\n")

print("✅ Selling Prices dataset schema displayed successfully.")

Column Names:

Index(['store_id', 'item_id', 'wm_yr_wk', 'sell_price'], dtype='str')

================================================================================

<class 'pandas.DataFrame'>
RangeIndex: 6841121 entries, 0 to 6841120
Data columns (total 4 columns):
 #   Column      Dtype
---  ------      -----
 0   store_id    str
 1   item_id     str
 2   wm_yr_wk    int64
 3   sell_price  float64
dtypes: float64(1), int64(1), str(2)
memory usage: 318.1 MB

================================================================================

✅ Selling Prices dataset schema displayed successfully.

### 9.3.3 Business Context

The Selling Prices dataset records the weekly selling price of each product across different stores. While the Sales dataset captures customer demand, this dataset provides the pricing information needed to analyze the impact of price changes on demand.

The dataset is organized around four key variables:

- **`store_id`** – Store identifier.
- **`item_id`** – Product identifier.
- **`wm_yr_wk`** – Retail week used to align pricing information with the Calendar dataset.
- **`sell_price`** – Weekly selling price of the product.

> **📌 Business Importance:** Pricing information enables forecasting models to capture the impact of price fluctuations, improving demand forecasting and inventory planning.

### 9.3.4 Key Observations

The initial exploration reveals the following:

- The dataset contains **6,841,121 records** and **4 columns**, making it the largest of the three M5 source datasets.
- It consists of **2 `str` columns**, **1 `int64` column**, and **1 `float64` column**.
- Each record represents the weekly selling price of a product in a specific store.
- The combination of `store_id`, `item_id`, and `wm_yr_wk` uniquely identifies a pricing record.
- The dataset provides the pricing context required to analyze the relationship between price changes and customer demand.

## 💲 Selling Prices Dataset Summary

The Selling Prices dataset provides the pricing dimension of the M5 Forecasting project. Understanding its structure, schema, and business context establishes the foundation for pricing analysis and demand forecasting.

> **💡 Key Takeaway:** Pricing data complements historical sales and calendar information, enabling forecasting models to capture the impact of price changes on customer demand.

## 🔗 9.4 Dataset Relationship Overview

The three source datasets combine demand, calendar context, and weekly pricing into a unified analytical structure.

### 9.4.1 Dataset Roles

- The **Sales dataset** records daily item-store demand.
- The **Calendar dataset** maps encoded sales days to dates, retail weeks, events, and SNAP indicators.
- The **Selling Prices dataset** provides weekly item-store prices.

Together, they explain what was sold, when it was sold, and at what price.

### 9.4.2 Common Keys and Join Strategy

The datasets are connected through the following fields:

- `d` links reshaped daily sales records with the Calendar dataset.
- `wm_yr_wk` connects calendar dates with weekly pricing records.
- `item_id` and `store_id` identify the applicable item-store price.

The Sales dataset will first be reshaped to long format, joined with Calendar using `d`, and then enriched with pricing information using `item_id`, `store_id`, and `wm_yr_wk`.

### 9.4.3 Integration Workflow

1. Reshape the Sales dataset into one record per item-store-day.
2. Attach calendar dates, events, and SNAP attributes using `d`.
3. Attach weekly selling prices using `item_id`, `store_id`, and `wm_yr_wk`.
4. Use the integrated records for feature engineering, forecasting, and inventory analysis.

> **📌 Business Importance:** Integrating these datasets enables forecasting models to capture historical demand, seasonality, events, and pricing behavior, supporting more accurate demand forecasting and inventory planning.

## 📖 Source Data Understanding Summary

In this section, we explored the three M5 source datasets and their roles in the demand forecasting pipeline. We examined their structure, schema, business context, and relationships to establish a clear understanding of the data before moving to the engineering phase.

> **🚀 Next Step:** Section 10 focuses on Data Quality Assessment, where we will evaluate missing values, duplicates, inconsistencies, and other quality issues before data integration and transformation.

# 🛡️ 10. Data Quality Assessment

This section evaluates the completeness, uniqueness, data types, key integrity, and business-rule validity of the three source datasets before data engineering begins.

This section will:

- assess the Sales, Calendar, and Selling Prices datasets independently;
- distinguish genuine data-quality issues from valid business conditions;
- confirm each dataset’s readiness for transformation and integration.

No cleaning or feature engineering is performed in this section.

## 📦 10.1 Sales Dataset Quality Assessment

This subsection evaluates the Sales dataset for:

- missing values;
- duplicate records;
- data-type consistency;
- identifier integrity;
- valid non-negative sales values.

The results will determine whether the dataset is ready for transformation in Section 11.

### 10.1.1 Missing Values

Missing values can reduce data quality and impact downstream analysis, feature engineering, and predictive modeling. This subsection evaluates the completeness of the Sales dataset by identifying missing values across all columns.

> **📌 Objective:** Verify whether the Sales dataset contains any missing values that require attention before data engineering.

In [11]:
# ============================================================
# 10.1.1 Missing Values
# ============================================================

# Count missing values in each column
missing_values = sales_df.isnull().sum()

# Display missing value summary
display(missing_values[missing_values > 0])

print("\n" + "=" * 80 + "\n")

# Display overall statistics
total_missing = missing_values.sum()
missing_columns = (missing_values > 0).sum()

print(f"Total Missing Values : {total_missing:,}")
print(f"Columns with Missing Values : {missing_columns}")

print("\n" + "=" * 80 + "\n")

if total_missing == 0:
    print("✅ No missing values detected in the Sales dataset.")
else:
    print("⚠️ Missing values detected. Further assessment is required.")

Series([], dtype: int64)

================================================================================

Total Missing Values : 0
Columns with Missing Values : 0

================================================================================

✅ No missing values detected in the Sales dataset.

### 🔎 Quality Assessment

No missing values were detected across the 1,919 Sales dataset columns.

All identifier fields and 1,913 daily sales columns are complete, confirming that the dataset can proceed to the remaining quality checks without missing-data treatment.

### 10.1.2 Duplicate Records

Duplicate records can introduce bias, inflate analytical results, and affect data integrity. This subsection evaluates whether the Sales dataset contains duplicate rows that require further investigation.

> **📌 Objective:** Identify duplicate records and determine whether they represent genuine data quality issues.

In [12]:
# ============================================================
# 10.1.2 Duplicate Records
# ============================================================

# Count duplicate rows
duplicate_count = sales_df.duplicated().sum()

print(f"Duplicate Records : {duplicate_count:,}")

print("\n" + "=" * 80 + "\n")

# Display duplicate records (if any)
if duplicate_count > 0:
    display(sales_df[sales_df.duplicated()].head())
    print(f"Showing first 5 of {duplicate_count:,} duplicate records.")
else:
    print("✅ No duplicate records detected in the Sales dataset.")

print("\n" + "=" * 80 + "\n")

print("✅ Duplicate record assessment completed.")

Duplicate Records : 0

================================================================================

✅ No duplicate records detected in the Sales dataset.

================================================================================

✅ Duplicate record assessment completed.

### 🔎 Quality Assessment

No duplicate rows were detected in the Sales dataset.

Each of the 30,490 records represents one unique product-store sales series, preventing duplicate demand histories and double-counting during downstream processing.

### 10.1.3 Data Type Validation

Data type validation verifies that each column is stored using an appropriate data type. Correct data types improve computational efficiency, reduce processing errors, and ensure compatibility with downstream data engineering and analytical tasks.

> **📌 Objective:** Validate the data types of all columns in the Sales dataset and identify any inconsistencies that may require correction.

In [13]:
# ============================================================
# 10.1.3 Data Type Validation
# ============================================================

# Display data types
display(sales_df.dtypes.value_counts())

print("\n" + "=" * 80 + "\n")

# Display columns by data type
display(
    sales_df.dtypes.reset_index().rename(
        columns={"index": "Column", 0: "Data Type"}
    )
)

print("\n" + "=" * 80 + "\n")

print("✅ Data type validation completed.")

int64    1913
str         6
Name: count, dtype: int64

================================================================================

        Column Data Type
0           id       str
1      item_id       str
2      dept_id       str
3       cat_id       str
4     store_id       str
...        ...       ...
1914    d_1909     int64
1915    d_1910     int64
1916    d_1911     int64
1917    d_1912     int64
1918    d_1913     int64

[1919 rows x 2 columns]

================================================================================

✅ Data type validation completed.

### 🔎 Quality Assessment

The Sales dataset contains 1,913 integer-based daily sales columns and six string-based identifier columns.

No unexpected data types were detected. The schema is consistent with the dataset’s wide-format structure and is suitable for subsequent reshaping and engineering.

### 10.1.4 Identifier Validation

Identifier columns uniquely describe each product-store combination and play a critical role in data integration and feature engineering. This subsection validates the identifier columns by checking for missing values, uniqueness, and cardinality.

> **📌 Objective:** Verify that the identifier columns are complete and suitable for downstream data integration.

In [14]:
# ============================================================
# 10.1.4 Identifier Validation
# ============================================================

identifier_columns = [
    "id",
    "item_id",
    "dept_id",
    "cat_id",
    "store_id",
    "state_id"
]

# Create identifier summary
identifier_summary = pd.DataFrame({
    "Unique Values": sales_df[identifier_columns].nunique(),
    "Missing Values": sales_df[identifier_columns].isnull().sum()
})

display(identifier_summary)

print("\n" + "=" * 80 + "\n")

# Validate uniqueness of the primary row identifier
duplicate_ids = sales_df["id"].duplicated().sum()

print(f"Duplicate 'id' Values : {duplicate_ids:,}")

print("\n" + "=" * 80 + "\n")

if identifier_summary["Missing Values"].sum() == 0:
    print("✅ No missing values detected in the identifier columns.")
else:
    print("⚠️ Missing values detected in one or more identifier columns.")

if duplicate_ids == 0:
    print("✅ The 'id' column uniquely identifies each product-store combination.")
else:
    print("⚠️ Duplicate values detected in the 'id' column.")

print("\n" + "=" * 80 + "\n")

print("✅ Identifier validation completed.")

          Unique Values  Missing Values
id                30490               0
item_id            3049               0
dept_id               7               0
cat_id                3               0
store_id             10               0
state_id              3               0

================================================================================

Duplicate 'id' Values : 0

================================================================================

✅ No missing values detected in the identifier columns.
✅ The 'id' column uniquely identifies each product-store combination.

================================================================================

✅ Identifier validation completed.

### 🔎 Quality Assessment

All identifier fields are complete, and the `id` column uniquely identifies all 30,490 product-store sales series.

The dataset contains 3,049 items, seven departments, three categories, 10 stores, and three states. No identifier-level integrity issues were detected.

### 10.1.5 Sales Value Validation

Sales value validation verifies that daily demand values are stored in a valid and consistent form. Since sales represent units sold, values should be non-negative integers, while zero values may legitimately indicate days with no demand.

> **📌 Objective:** Identify invalid sales values and confirm that the daily sales columns are suitable for downstream forecasting.

In [15]:
# ============================================================
# 10.1.5 Sales Value Validation
# ============================================================

# Identify daily sales columns
sales_columns = [column for column in sales_df.columns if column.startswith("d_")]

# Calculate validation metrics
minimum_sales = sales_df[sales_columns].min().min()
maximum_sales = sales_df[sales_columns].max().max()
negative_values = (sales_df[sales_columns] < 0).sum().sum()
zero_values = (sales_df[sales_columns] == 0).sum().sum()
total_sales_values = sales_df[sales_columns].size

# Check whether all values are integer-based
non_integer_values = (
    sales_df[sales_columns]
    .mod(1)
    .ne(0)
    .sum()
    .sum()
)

# Display validation summary
sales_validation_summary = pd.DataFrame({
    "Metric": [
        "Sales Columns",
        "Total Sales Values",
        "Minimum Sales Value",
        "Maximum Sales Value",
        "Negative Values",
        "Non-Integer Values",
        "Zero Sales Values"
    ],
    "Result": [
        len(sales_columns),
        total_sales_values,
        minimum_sales,
        maximum_sales,
        negative_values,
        non_integer_values,
        zero_values
    ]
})

display(sales_validation_summary)

print("\n" + "=" * 80 + "\n")

if negative_values == 0 and non_integer_values == 0:
    print("✅ Daily sales values are valid non-negative integers.")
else:
    print("⚠️ Invalid daily sales values detected.")

print("\n" + "=" * 80 + "\n")

print("✅ Sales value validation completed.")

                Metric    Result
0        Sales Columns      1913
1   Total Sales Values  58327370
2  Minimum Sales Value         0
3  Maximum Sales Value       763
4      Negative Values         0
5   Non-Integer Values         0
6    Zero Sales Values  39777094

================================================================================

✅ Daily sales values are valid non-negative integers.

================================================================================

✅ Sales value validation completed.

### 🔎 Quality Assessment

The 1,913 daily sales columns contain 58,327,370 non-negative integer observations ranging from 0 to 763 units.

No negative or non-integer values were detected. The 39,777,094 zero values represent valid no-demand observations rather than missing data.

### ✅ Sales Dataset Quality Assessment Summary

The Sales dataset passed all assessed quality checks.

No missing values, duplicate records, identifier inconsistencies, negative sales values, or non-integer demand observations were detected. Valid zero-demand records were retained as meaningful historical observations.

The dataset is ready for transformation and integration in Section 11.

## 📅 10.2 Calendar Dataset Quality Assessment

This subsection evaluates the Calendar dataset for:

- missing values;
- duplicate records;
- data-type consistency;
- calendar-key integrity;
- valid event and SNAP attributes.

The assessment will distinguish expected business-related missing values from genuine data-quality issues.

### 10.2.1 Missing Values

Missing values can indicate incomplete data or, in some cases, represent valid business conditions. This subsection evaluates the completeness of the Calendar dataset and distinguishes between expected and unexpected missing values.

> **📌 Objective:** Identify missing values and determine whether they represent genuine data quality issues or valid business scenarios.

In [16]:
# ============================================================
# 10.2.1 Missing Values
# ============================================================

# Count missing values
missing_values = calendar_df.isnull().sum()

# Create missing value summary
missing_summary = pd.DataFrame({
    "Missing Values": missing_values,
    "Percentage (%)": (
        missing_values / len(calendar_df) * 100
    ).round(2)
})

# Display only columns with missing values
display(missing_summary[missing_summary["Missing Values"] > 0])

print("\n" + "=" * 80 + "\n")

print(f"Total Missing Values : {missing_values.sum():,}")
print(f"Columns with Missing Values : {(missing_values > 0).sum()}")

print("\n" + "=" * 80 + "\n")

print("✅ Calendar missing value assessment completed.")

              Missing Values  Percentage (%)
event_name_1            1807           91.77
event_type_1            1807           91.77
event_name_2            1964           99.75
event_type_2            1964           99.75

================================================================================

Total Missing Values : 7,542
Columns with Missing Values : 4

================================================================================

✅ Calendar missing value assessment completed.

### 🔎 Quality Assessment

Missing values occur only in the four event-related columns.

The matching missing counts between each event name and event type confirm that these values represent dates without scheduled events rather than incomplete records. All remaining Calendar and SNAP fields are complete.

### 10.2.2 Duplicate Records

Duplicate records can introduce redundancy, affect data integrity, and lead to incorrect results during dataset integration and time-based analysis. This subsection evaluates whether the Calendar dataset contains duplicate rows that require further investigation.

📌 **Objective:** Verify that each calendar record represents a unique date and identify any duplicate records that may affect downstream data engineering.

In [17]:
# ============================================================
# 10.2.2 Duplicate Records
# ============================================================

# Count duplicate rows
duplicate_count = calendar_df.duplicated().sum()

print(f"Duplicate Records : {duplicate_count:,}")

print("\n" + "=" * 80 + "\n")

# Display duplicate records (if any)
if duplicate_count > 0:
    display(calendar_df[calendar_df.duplicated()].head())
    print(f"Showing first 5 of {duplicate_count:,} duplicate records.")
else:
    print("✅ No duplicate records detected in the Calendar dataset.")

print("\n" + "=" * 80 + "\n")

print("✅ Duplicate record assessment completed.")

Duplicate Records : 0

================================================================================

✅ No duplicate records detected in the Calendar dataset.

================================================================================

✅ Duplicate record assessment completed.

### 🔎 Quality Assessment

No duplicate rows were detected in the Calendar dataset.

Each of the 1,969 records represents one unique calendar date, supporting unambiguous date-based joins and chronological analysis.

### 10.2.3 Data Type Validation

Data type validation verifies that each column is stored using an appropriate data type. Correct data types improve data consistency, reduce processing errors, and ensure compatibility with downstream data engineering and analytical tasks.

📌 **Objective:** Validate the data types of all columns in the Calendar dataset and identify any inconsistencies that may require correction.

In [18]:
# ============================================================
# 10.2.3 Data Type Validation
# ============================================================

# Display count of each data type
display(calendar_df.dtypes.value_counts())

print("\n" + "=" * 80 + "\n")

# Display data type of each column
display(
    calendar_df.dtypes.reset_index().rename(
        columns={"index": "Column", 0: "Data Type"}
    )
)

print("\n" + "=" * 80 + "\n")

print("✅ Calendar data type validation completed.")

str      7
int64    7
Name: count, dtype: int64

================================================================================

          Column Data Type
0           date       str
1       wm_yr_wk     int64
2        weekday       str
3           wday     int64
4          month     int64
5           year     int64
6              d       str
7   event_name_1       str
8   event_type_1       str
9   event_name_2       str
10  event_type_2       str
11       snap_CA     int64
12       snap_TX     int64
13       snap_WI     int64

================================================================================

✅ Calendar data type validation completed.

### 🔎 Quality Assessment

The Calendar dataset contains seven string columns and seven integer columns.

All source data types are appropriate for initial assessment. The `date` field remains string-based and will be converted to `datetime` during calendar engineering; no other unexpected data-type issues were detected.

### 10.2.4 Calendar Attribute Validation

Calendar attribute validation evaluates the completeness, uniqueness, and cardinality of the core temporal fields. These checks confirm that the Calendar dataset contains one record per date and one unique encoded day identifier before downstream data engineering.

> **📌 Objective:** Verify that the core calendar attributes are complete and that the `date` and `d` columns uniquely identify each calendar record.

In [19]:
# ============================================================
# 10.2.4 Calendar Attribute Validation
# ============================================================

# Key calendar attributes
calendar_columns = [
    "date",
    "wm_yr_wk",
    "weekday",
    "wday",
    "month",
    "year",
    "d"
]

# Create validation summary
calendar_summary = pd.DataFrame({
    "Unique Values": calendar_df[calendar_columns].nunique(),
    "Missing Values": calendar_df[calendar_columns].isnull().sum()
})

display(calendar_summary)

print("\n" + "=" * 80 + "\n")

# Validate uniqueness of calendar day identifier
duplicate_day_ids = calendar_df["d"].duplicated().sum()

print(f"Duplicate 'd' Values : {duplicate_day_ids:,}")

print("\n" + "=" * 80 + "\n")

# Validate uniqueness of calendar dates
duplicate_dates = calendar_df["date"].duplicated().sum()

print(f"Duplicate Dates : {duplicate_dates:,}")

print("\n" + "=" * 80 + "\n")

if calendar_summary["Missing Values"].sum() == 0:
    print("✅ No missing values detected in the core calendar attributes.")
else:
    print("⚠️ Missing values detected in one or more calendar attributes.")

if duplicate_day_ids == 0 and duplicate_dates == 0:
    print("✅ Calendar day identifiers and dates are unique.")
else:
    print("⚠️ Duplicate calendar identifiers or dates detected.")

print("\n" + "=" * 80 + "\n")

print("✅ Calendar attribute validation completed.")

          Unique Values  Missing Values
date               1969               0
wm_yr_wk            282               0
weekday               7               0
wday                  7               0
month                12               0
year                  6               0
d                  1969               0

================================================================================

Duplicate 'd' Values : 0

================================================================================

Duplicate Dates : 0

================================================================================

✅ No missing values detected in the core calendar attributes.
✅ Calendar day identifiers and dates are unique.

================================================================================

✅ Calendar attribute validation completed.

### 🔎 Quality Assessment

All core Calendar attributes are complete.

The dataset contains 1,969 unique dates and 1,969 unique `d` identifiers, with no duplicate key values. The remaining attributes cover 282 retail weeks, 12 months, six years, and seven weekday categories.

### 10.2.5 Event Information Validation

The Calendar dataset contains event-related attributes that capture holidays, cultural celebrations, sporting events, and other special occasions that may influence customer demand. This subsection validates the completeness and consistency of the event information to ensure it is suitable for downstream feature engineering and demand forecasting.

📌 **Objective:** Validate the event-related columns and confirm that event information is logically consistent and suitable for downstream analytical tasks.

In [20]:
# ============================================================
# 10.2.5 Event Information Validation
# ============================================================

# Event-related columns
event_columns = [
    "event_name_1",
    "event_type_1",
    "event_name_2",
    "event_type_2"
]

# Create event summary
event_summary = pd.DataFrame({
    "Unique Values": calendar_df[event_columns].nunique(),
    "Missing Values": calendar_df[event_columns].isnull().sum()
})

display(event_summary)

print("\n" + "=" * 80 + "\n")

# Validate logical consistency between event names and event types
primary_event_mismatch = (
    calendar_df["event_name_1"].isna() != calendar_df["event_type_1"].isna()
).sum()

secondary_event_mismatch = (
    calendar_df["event_name_2"].isna() != calendar_df["event_type_2"].isna()
).sum()

print(f"Primary Event Mismatches   : {primary_event_mismatch:,}")
print(f"Secondary Event Mismatches : {secondary_event_mismatch:,}")

print("\n" + "=" * 80 + "\n")

if primary_event_mismatch == 0 and secondary_event_mismatch == 0:
    print("✅ Event names and event types are logically consistent.")
else:
    print("⚠️ Logical inconsistencies detected between event names and event types.")

print("\n" + "=" * 80 + "\n")

print("✅ Event information validation completed.")

              Unique Values  Missing Values
event_name_1             30            1807
event_type_1              4            1807
event_name_2              4            1964
event_type_2              2            1964

================================================================================

Primary Event Mismatches   : 0
Secondary Event Mismatches : 0

================================================================================

✅ Event names and event types are logically consistent.

================================================================================

✅ Event information validation completed.

### 🔎 Quality Assessment

The Calendar dataset contains 30 primary event names across four event types and four secondary event names across two event types.

No mismatches were detected between event names and event types. Missing values represent dates without scheduled events and do not indicate incomplete records.

### 10.2.6 SNAP Indicator Validation

The SNAP (Supplemental Nutrition Assistance Program) indicators identify whether SNAP benefits are available on a given day in California (CA), Texas (TX), and Wisconsin (WI). These binary variables are important external factors that may influence customer purchasing behavior and demand patterns. This subsection validates the SNAP indicators to ensure they are complete, consistent, and contain only valid binary values.

📌 **Objective:** Validate the SNAP indicator columns and confirm that they contain complete and valid binary values suitable for downstream feature engineering and demand forecasting.

In [21]:
# ============================================================
# 10.2.6 SNAP Indicator Validation
# ============================================================

# SNAP indicator columns
snap_columns = [
    "snap_CA",
    "snap_TX",
    "snap_WI"
]

# Create SNAP validation summary
snap_summary = pd.DataFrame({
    "Unique Values": calendar_df[snap_columns].nunique(),
    "Missing Values": calendar_df[snap_columns].isnull().sum(),
    "Minimum": calendar_df[snap_columns].min(),
    "Maximum": calendar_df[snap_columns].max()
})

display(snap_summary)

print("\n" + "=" * 80 + "\n")

# Check for invalid values
invalid_snap_values = (
    ~calendar_df[snap_columns].isin([0, 1])
).sum()

display(
    pd.DataFrame({
        "Invalid Values": invalid_snap_values
    })
)

print("\n" + "=" * 80 + "\n")

if invalid_snap_values.sum() == 0:
    print("✅ All SNAP indicators contain valid binary values (0 or 1).")
else:
    print("⚠️ Invalid SNAP indicator values detected.")

print("\n" + "=" * 80 + "\n")

print("✅ SNAP indicator validation completed.")

         Unique Values  Missing Values  Minimum  Maximum
snap_CA              2               0        0        1
snap_TX              2               0        0        1
snap_WI              2               0        0        1

================================================================================

         Invalid Values
snap_CA               0
snap_TX               0
snap_WI               0

================================================================================

✅ All SNAP indicators contain valid binary values (0 or 1).

================================================================================

✅ SNAP indicator validation completed.

### 🔎 Quality Assessment

The `snap_CA`, `snap_TX`, and `snap_WI` fields are complete and contain only the valid binary values `0` and `1`.

No missing or invalid SNAP indicator values were detected, confirming that the fields are ready for Calendar feature engineering.

### ✅ Calendar Dataset Quality Assessment Summary

The Calendar dataset passed all assessed quality checks.

Core calendar keys are complete and unique, event-field missing values represent valid non-event dates, event names and types are logically aligned, and all SNAP indicators contain valid binary values.

The `date` field requires conversion to `datetime` during Section 11; no other corrective treatment is required.

### 💲 10.3 Selling Prices Dataset Quality Assessment

This subsection evaluates the Selling Prices dataset for:

- missing values;
- duplicate records;
- data-type consistency;
- composite-key integrity;
- valid positive selling prices.

The results will determine whether the weekly pricing records are ready for integration with Sales and Calendar.

## 10.3.1 Missing Values

Missing values can reduce data quality and impact price analysis, feature engineering, and demand forecasting. This subsection evaluates the completeness of the Selling Prices dataset by identifying missing values across all columns.

📌 **Objective:** Verify whether the Selling Prices dataset contains any missing values that require attention before data engineering.

In [22]:
# ============================================================
# 10.3.1 Missing Values
# ============================================================

# Count missing values in each column
missing_values = prices_df.isnull().sum()

# Display missing value summary
display(missing_values[missing_values > 0])

print("\n" + "=" * 80 + "\n")

# Display overall statistics
total_missing = missing_values.sum()
missing_columns = (missing_values > 0).sum()

print(f"Total Missing Values : {total_missing:,}")
print(f"Columns with Missing Values : {missing_columns}")

print("\n" + "=" * 80 + "\n")

if total_missing == 0:
    print("✅ No missing values detected in the Selling Prices dataset.")
else:
    print("⚠️ Missing values detected. Further assessment is required.")

print("\n" + "=" * 80 + "\n")

print("✅ Selling Prices missing value assessment completed.")

Series([], dtype: int64)

================================================================================

Total Missing Values : 0
Columns with Missing Values : 0

================================================================================

✅ No missing values detected in the Selling Prices dataset.

================================================================================

✅ Selling Prices missing value assessment completed.

### 🔎 Quality Assessment

No missing values were detected across the four Selling Prices fields.

All product, store, retail-week, and selling-price records are complete, so no missing-data treatment is required before pricing integration.

### 10.3.2 Duplicate Records

Duplicate records can introduce redundancy, distort price analysis, and affect data integrity during dataset integration. This subsection evaluates whether the Selling Prices dataset contains duplicate records that require further investigation.

📌 **Objective:** Identify duplicate records and determine whether they represent genuine data quality issues.

In [23]:
# ============================================================
# 10.3.2 Duplicate Records
# ============================================================

# Count duplicate rows
duplicate_count = prices_df.duplicated().sum()

print(f"Duplicate Records : {duplicate_count:,}")

print("\n" + "=" * 80 + "\n")

# Display duplicate records (if any)
if duplicate_count > 0:
    display(prices_df[prices_df.duplicated()].head())
    print(f"Showing first 5 of {duplicate_count:,} duplicate records.")
else:
    print("✅ No duplicate records detected in the Selling Prices dataset.")

print("\n" + "=" * 80 + "\n")

print("✅ Selling Prices duplicate record assessment completed.")

Duplicate Records : 0

================================================================================

✅ No duplicate records detected in the Selling Prices dataset.

================================================================================

✅ Selling Prices duplicate record assessment completed.

### 🔎 Quality Assessment

No duplicate rows were detected in the Selling Prices dataset.

Each record represents one unique store-item-week pricing observation, preventing duplicate price assignments during integration.

### 10.3.3 Data Type Validation

Data type validation verifies that each column is stored using an appropriate data type. Correct data types improve computational efficiency, reduce processing errors, and ensure compatibility with downstream data engineering and analytical tasks.

📌 **Objective:** Validate the data types of all columns in the Selling Prices dataset and identify any inconsistencies that may require correction.

In [24]:
# ============================================================
# 10.3.3 Data Type Validation
# ============================================================

# Display count of each data type
display(prices_df.dtypes.value_counts())

print("\n" + "=" * 80 + "\n")

# Display data type of each column
display(
    prices_df.dtypes.reset_index().rename(
        columns={"index": "Column", 0: "Data Type"}
    )
)

print("\n" + "=" * 80 + "\n")

print("✅ Selling Prices data type validation completed.")

str        2
int64      1
float64    1
Name: count, dtype: int64

================================================================================

       Column Data Type
0    store_id       str
1     item_id       str
2    wm_yr_wk     int64
3  sell_price   float64

================================================================================

✅ Selling Prices data type validation completed.

### 🔎 Quality Assessment

The Selling Prices dataset contains two string identifier fields, one integer retail-week field, and one floating-point selling-price field.

No unexpected or inconsistent data types were detected. The schema is appropriate for pricing integration and downstream calculations.

### 10.3.4 Identifier Validation

Identifier columns uniquely define each product-store-week combination and play a critical role in data integration and feature engineering. This subsection validates the identifier columns by checking for missing values, uniqueness, and cardinality.

📌 **Objective:** Verify that the identifier columns are complete and suitable for downstream data integration with the Sales and Calendar datasets.

In [25]:
# ============================================================
# 10.3.4 Identifier Validation
# ============================================================

# Identifier columns
identifier_columns = [
    "store_id",
    "item_id",
    "wm_yr_wk"
]

# Create identifier summary
identifier_summary = pd.DataFrame({
    "Unique Values": prices_df[identifier_columns].nunique(),
    "Missing Values": prices_df[identifier_columns].isnull().sum()
})

display(identifier_summary)

print("\n" + "=" * 80 + "\n")

# Check duplicate product-store-week combinations
duplicate_keys = prices_df.duplicated(
    subset=["store_id", "item_id", "wm_yr_wk"]
).sum()

print(f"Duplicate Product-Store-Week Combinations : {duplicate_keys:,}")

print("\n" + "=" * 80 + "\n")

if identifier_summary["Missing Values"].sum() == 0:
    print("✅ No missing values detected in the identifier columns.")
else:
    print("⚠️ Missing values detected in one or more identifier columns.")

if duplicate_keys == 0:
    print("✅ Each product-store-week combination is unique.")
else:
    print("⚠️ Duplicate product-store-week combinations detected.")

print("\n" + "=" * 80 + "\n")

print("✅ Selling Prices identifier validation completed.")

          Unique Values  Missing Values
store_id             10               0
item_id            3049               0
wm_yr_wk            282               0

================================================================================

Duplicate Product-Store-Week Combinations : 0

================================================================================

✅ No missing values detected in the identifier columns.
✅ Each product-store-week combination is unique.

================================================================================

✅ Selling Prices identifier validation completed.

### 🔎 Quality Assessment

All identifier fields are complete.

The dataset contains 10 stores, 3,049 items, and 282 retail weeks. Every `store_id`–`item_id`–`wm_yr_wk` combination is unique, confirming a valid composite key for pricing integration.

### 10.3.5 Selling Price Validation

Selling price is the primary business metric in this dataset and directly influences revenue analysis, pricing strategy, and demand forecasting. This subsection validates the selling price values by identifying invalid, missing, zero, or negative prices and summarizing the overall price distribution.

📌 **Objective:** Assess the completeness and validity of selling price values to ensure they are suitable for downstream analytical and forecasting tasks.

In [26]:
# ============================================================
# 10.3.5 Selling Price Validation
# ============================================================

# Calculate price statistics
price_summary = pd.DataFrame({
    "Metric": [
        "Minimum Selling Price",
        "Maximum Selling Price",
        "Average Selling Price",
        "Missing Prices",
        "Zero Prices",
        "Negative Prices"
    ],
    "Value": [
        prices_df["sell_price"].min(),
        prices_df["sell_price"].max(),
        round(prices_df["sell_price"].mean(), 2),
        prices_df["sell_price"].isnull().sum(),
        (prices_df["sell_price"] == 0).sum(),
        (prices_df["sell_price"] < 0).sum()
    ]
})

display(price_summary)

print("\n" + "=" * 80 + "\n")

# Overall validation
if (
    prices_df["sell_price"].isnull().sum() == 0
    and (prices_df["sell_price"] < 0).sum() == 0
):
    print("✅ Selling price values passed the validation checks.")
else:
    print("⚠️ Issues detected in the selling price values.")

print("\n" + "=" * 80 + "\n")

print("✅ Selling Price validation completed.")

                  Metric  Value
0  Minimum Selling Price   0.01
1  Maximum Selling Price 107.32
2  Average Selling Price   4.41
3         Missing Prices   0.00
4            Zero Prices   0.00
5        Negative Prices   0.00

================================================================================

✅ Selling price values passed the validation checks.

================================================================================

✅ Selling Price validation completed.

### 🔎 Quality Assessment

All selling prices are complete, numeric, and strictly positive.

Observed prices range from 0.01 to 107.32, with an average of 4.41. No missing, zero, or negative price values were detected.

### ✅ Selling Prices Quality Assessment Summary

The Selling Prices dataset passed all assessed quality checks.

No missing values, duplicate records, data-type inconsistencies, composite-key violations, or invalid selling prices were detected.

The dataset is ready for integration with the Sales and Calendar datasets in Section 11.

## 📖 Section 10 Summary

The Sales, Calendar, and Selling Prices datasets completed all required quality assessments.

The source datasets contain valid identifiers, appropriate data types, consistent business keys, and no unresolved quality issues. Expected event-field missing values were retained as meaningful non-event dates.

The datasets are ready for engineering and integration in Section 11.

🚀 **Next Step:** Section 11 focuses on Data Engineering, where we will clean, transform, and integrate the validated datasets to create business-ready data structures for exploratory data analysis, feature engineering, and demand forecasting.

# ⚙️ 11. Data Engineering

This section transforms the validated source data into four standardized analytical datasets:

- Sales Daily Dataset;
- Calendar Dataset;
- SKU Master Dataset;
- simulated Inventory Snapshot Dataset.

Each dataset will be engineered and validated independently before final cross-dataset validation and export.

### 📈 11.1 Sales Daily Dataset Engineering

The raw sales dataset is transformed into a daily transactional format by integrating calendar and pricing information and engineering business-ready features.

**Objective:**
- Prepare the sales dataset for analysis and forecasting.
- Engineer business-relevant features.
- Create a clean and standardized daily sales dataset.

#### 📄 11.1.1 Create Sales Working Copy

A working copy of the raw sales dataset is created before applying any transformations. This preserves the original dataset and ensures a safe, reproducible data engineering workflow.

**Objective:**
- Preserve the raw dataset.
- Create an independent working copy.
- Perform all transformations safely.

In [27]:
# Create a working copy of the sales dataset
sales_daily = sales_df.copy()

print("✅ Sales Daily working dataset created successfully.")

✅ Sales Daily working dataset created successfully.

In [28]:
# Verify the dimensions of the working dataset
print(f" Dataset Shape: {sales_daily.shape}")

 Dataset Shape: (30490, 1919)

In [29]:
# Verify that the working copy is independent of the original dataset
is_independent = sales_df is not sales_daily

print(f" Independent Working Copy: {is_independent}")

 Independent Working Copy: True

#### ✅ Validation Result

A separate working copy of the Sales dataset was created successfully.

Validation confirms that:

- the working dataset preserves the original dimensions;
- the working copy is independent of the raw Sales dataset;
- all subsequent transformations will be performed safely without modifying the original source data.

### 📄 11.1.2 Identify Sales-Day Columns

The sales dataset stores daily sales values across multiple day columns (`d_1` to `d_n`). These columns are identified dynamically to support the transformation from wide format to long format.

**Objective:**
- Identify all daily sales columns.
- Separate identifier and sales columns.
- Prepare the dataset for reshaping.

In [30]:
# Identify all sales-day columns
sales_day_columns = [column for column in sales_daily.columns if column.startswith("d_")]

print(f"Sales-day columns identified: {len(sales_day_columns)}")

Sales-day columns identified: 1913

In [31]:
# Display the first and last five sales-day columns
print("First 5 sales-day columns:")
print(sales_day_columns[:5])

print("\nLast 5 sales-day columns:")
print(sales_day_columns[-5:])

First 5 sales-day columns:
['d_1', 'd_2', 'd_3', 'd_4', 'd_5']

Last 5 sales-day columns:
['d_1909', 'd_1910', 'd_1911', 'd_1912', 'd_1913']

In [32]:
# Define the identifier columns that describe each product-store series
identifier_columns = [
    "id",
    "item_id",
    "dept_id",
    "cat_id",
    "store_id",
    "state_id"
]

print("Identifier columns defined successfully.")
print(identifier_columns)

Identifier columns defined successfully.
['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id']

In [33]:
# Verify that all identifier columns exist in the working sales dataset
missing_identifier_columns = [
    column
    for column in identifier_columns
    if column not in sales_daily.columns
]

if missing_identifier_columns:
    raise ValueError(
        f"Missing identifier columns: {missing_identifier_columns}"
    )

print("All identifier columns are present in the sales dataset.")

All identifier columns are present in the sales dataset.

#### ✅ Validation Result

The daily sales columns were identified successfully.

Validation confirms that:

- all day-level sales columns were detected dynamically;
- the identified columns are ready for reshaping into long format;
- no manual column selection is required for subsequent transformations.

### ⚙️ 11.1.3 Configure the Development Sales Scope

The complete M5 sales dataset contains more than 30,000 product-store time series and would generate over 58 million records after conversion from wide to long format. Processing the complete dataset may require substantial memory, storage, and execution time on a local system.

To support efficient and reproducible local development, a category-balanced subset of 30 products—10 from each category—was selected using deterministic sorting, while retaining all 10 stores and all 1,913 historical sales days.

This subset supports pipeline development across product categories, stores, states and time periods, but it should not be interpreted as a statistically representative sample of the complete product or department population.

**Objective:**

- Define a reproducible and laptop-friendly sales development scope.
- Select an equal and reproducible number of development products from each product category.
- Retain all available stores and historical sales days.
- Reduce computational and storage requirements for downstream processing.

In [34]:
# ============================================================
# 11.1.3 Configure the Development Sales Scope
# ============================================================
# Define the number of products to select from each product category.
PRODUCTS_PER_CATEGORY = 10

# Display the configuration settings for the development dataset.
print("Development Scope Configuration")
print("-" * 40)

print(f"Products selected per category : {PRODUCTS_PER_CATEGORY}")
print(f"Available product categories   : {sales_daily['cat_id'].nunique()}")
print(f"Available retail stores        : {sales_daily['store_id'].nunique()}")
print(f"Historical sales-day columns   : {len(sales_day_columns)}")

Development Scope Configuration
----------------------------------------
Products selected per category : 10
Available product categories   : 3
Available retail stores        : 10
Historical sales-day columns   : 1913

In [35]:
# ============================================================
# Select Category-Balanced Development Products
# ============================================================

# Create a unique product list and select the first 10 products
# from each category using a reproducible sorting method.
selected_products = (
    sales_daily[["item_id", "dept_id", "cat_id"]]
    .drop_duplicates()
    .sort_values(["cat_id", "dept_id", "item_id"])
    .groupby("cat_id", group_keys=False)
    .head(PRODUCTS_PER_CATEGORY)
    .reset_index(drop=True)
)

# Display the number of selected products in each category.
selected_product_summary = (
    selected_products
    .groupby("cat_id")["item_id"]
    .nunique()
    .reset_index(name="selected_products")
)

display(selected_product_summary)

      cat_id  selected_products
0      FOODS                 10
1    HOBBIES                 10
2  HOUSEHOLD                 10

In [36]:
# ============================================================
# Create the Development Sales Dataset
# ============================================================

# Extract the identifiers of the selected products.
selected_item_ids = selected_products["item_id"].tolist()

# Retain the selected products along with all identifier
# and historical sales-day columns.
sales_daily_subset = (
    sales_daily.loc[
        sales_daily["item_id"].isin(selected_item_ids),
        identifier_columns + sales_day_columns
    ]
    .copy()
    .reset_index(drop=True)
)

# Confirm that the development dataset was created.
print(f"Development dataset created: {sales_daily_subset.shape}")

Development dataset created: (300, 1919)

In [37]:
# ============================================================
# Validate the Development Sales Dataset
# ============================================================

# Define the expected dimensions of the development scope.
expected_products = (
    PRODUCTS_PER_CATEGORY
    * sales_daily["cat_id"].nunique()
)

expected_stores = sales_daily["store_id"].nunique()

expected_sku_series = (
    expected_products
    * expected_stores
)

expected_long_rows = (
    expected_sku_series
    * len(sales_day_columns)
)

# Validate the product, store, and SKU-store counts.
assert sales_daily_subset["item_id"].nunique() == expected_products, (
    "Unexpected number of products."
)

assert sales_daily_subset["store_id"].nunique() == expected_stores, (
    "Not all retail stores were retained."
)

assert sales_daily_subset["id"].nunique() == expected_sku_series, (
    "Unexpected number of SKU-store series."
)

assert not sales_daily_subset["id"].duplicated().any(), (
    "Duplicate SKU-store identifiers were found."
)

# Display the validated development scope.
print("✅ Development sales dataset validated successfully.")
print(f"Unique products          : {expected_products}")
print(f"Unique retail stores     : {expected_stores}")
print(f"Unique SKU-store series  : {expected_sku_series}")
print(f"Expected long-format rows: {expected_long_rows:,}")

✅ Development sales dataset validated successfully.
Unique products          : 30
Unique retail stores     : 10
Unique SKU-store series  : 300
Expected long-format rows: 573,900

#### ✅ Validation Result

The development sales scope was configured successfully and validated against the expected engineering requirements.

Validation confirmed that:

30 category-balanced development products were selected, with 10 products retained from each of the 3 product categories.
- All 10 retail stores were retained in the development dataset.
- The dataset contains 300 unique SKU-store series.
- All 1,913 historical sales-day columns were preserved.
- The expected long-format dataset will contain 573,900 daily sales records after reshaping.

The validated development dataset provides a category-balanced, reproducible, and computationally efficient foundation for developing the remaining sales engineering pipeline within the defined 300-series scope.

### 🔄 11.1.4 Reshape the Sales Dataset to Long Format

The development sales dataset currently stores each historical sales day in a separate column. Although this wide structure is suitable for compact storage, it is not convenient for time-series analysis, relational joins, feature engineering, or downstream analytical workflows.

The dataset is therefore converted into long format, where each row represents the units sold for one SKU-store series on one historical sales day. This structure will support subsequent integration with calendar and pricing data.

**Objective:**

- Convert the wide sales dataset into a row-level daily sales structure.
- Preserve all product, store, category, department, and state identifiers.
- Create standardized `day` and `units_sold` fields.
- Validate the expected number and uniqueness of daily sales records.

In [38]:
# ============================================================
# Reshape the Development Sales Dataset to Long Format
# ============================================================

# Convert the historical sales-day columns into row-level records
# while preserving all product and store identifiers.
sales_long = sales_daily_subset.melt(
    id_vars=identifier_columns,
    value_vars=sales_day_columns,
    var_name="day",
    value_name="units_sold"
)

# Confirm that the long-format dataset was created.
print(f"Long-format dataset created: {sales_long.shape}")

Long-format dataset created: (573900, 8)

In [39]:
# ============================================================
# Standardize the Long-Format Dataset
# ============================================================

# Remove the "d_" prefix from the day values.
sales_long["day"] = (
    sales_long["day"]
    .str.replace("d_", "", regex=False)
    .astype("int16")
)

# Optimize the sales column.
sales_long["units_sold"] = sales_long["units_sold"].astype("int16")

# Arrange the columns.
sales_long = sales_long[
    [
        "id",
        "item_id",
        "dept_id",
        "cat_id",
        "store_id",
        "state_id",
        "day",
        "units_sold"
    ]
]

print("Long-format dataset standardized.")

Long-format dataset standardized.

In [40]:
# ============================================================
# Validate the Long-Format Dataset
# ============================================================

# Calculate expected dimensions.
expected_rows = (
    sales_daily_subset["id"].nunique()
    * len(sales_day_columns)
)

expected_series = sales_daily_subset["id"].nunique()

# Validate structure and data quality.
assert sales_long.shape[0] == expected_rows
assert sales_long["id"].nunique() == expected_series
assert sales_long["day"].min() == 1
assert sales_long["day"].max() == len(sales_day_columns)
assert not sales_long[["id", "day"]].duplicated().any()
assert sales_long[["id", "day", "units_sold"]].notna().all().all()
assert (sales_long["units_sold"] >= 0).all()

print("✅ Long-format sales dataset validated successfully.")
print(f"Total rows             : {sales_long.shape[0]:,}")
print(f"Unique SKU-store series: {sales_long['id'].nunique():,}")
print(f"Historical day range   : {sales_long['day'].min()} to {sales_long['day'].max()}")

✅ Long-format sales dataset validated successfully.
Total rows             : 573,900
Unique SKU-store series: 300
Historical day range   : 1 to 1913

In [41]:
# ============================================================
# Preview the Long-Format Dataset
# ============================================================

# Display sample records.
display(sales_long.head())

# Show the final structure.
print(f"Dataset shape : {sales_long.shape}")
print(f"Total units   : {sales_long['units_sold'].sum():,}")

                              id        item_id    dept_id   cat_id store_id state_id  day  units_sold
0  HOBBIES_1_001_CA_1_validation  HOBBIES_1_001  HOBBIES_1  HOBBIES     CA_1       CA    1           0
1  HOBBIES_1_002_CA_1_validation  HOBBIES_1_002  HOBBIES_1  HOBBIES     CA_1       CA    1           0
2  HOBBIES_1_003_CA_1_validation  HOBBIES_1_003  HOBBIES_1  HOBBIES     CA_1       CA    1           0
3  HOBBIES_1_004_CA_1_validation  HOBBIES_1_004  HOBBIES_1  HOBBIES     CA_1       CA    1           0
4  HOBBIES_1_005_CA_1_validation  HOBBIES_1_005  HOBBIES_1  HOBBIES     CA_1       CA    1           0

Dataset shape : (573900, 8)
Total units   : 573,932

#### ✅ Validation Result

The development sales dataset was successfully reshaped from wide format to long format.

Validation confirmed that:

- The expected 573,900 daily sales records were generated.
- Each SKU-store series contains one unique record for every historical sales day.
- The historical day values span from 1 to 1,913.
- No missing values were introduced during the transformation.
- No negative sales quantities were detected.

The validated long-format dataset is now ready for calendar integration and subsequent feature engineering.

### 🏷️ 11.1.5 Standardize Sales Identifiers

The reshaped sales dataset currently contains multiple product and store identifier fields inherited from the original M5 dataset. To establish a consistent identifier structure across the data engineering pipeline, these fields will be standardized before further transformations.

A unique `sku_id` will be assigned to each item–store combination. This identifier will become the primary product key used throughout the project, ensuring consistent identification of every SKU across the final engineered datasets.

This step will:

- create a unique `sku_id` for each item–store combination;
- preserve the original product and store identifiers for traceability;
- verify that each sales series maps to exactly one `sku_id`;
- validate the completeness and uniqueness of the identifier mapping.

The standardized identifier structure will provide a reliable foundation for the remaining data engineering steps.

In [42]:
# ============================================================
# Create Standardized SKU Identifiers
# ============================================================

# Create a copy of the reshaped sales dataset.
sales_standardized = sales_long.copy()

# Create a unique SKU identifier.
sales_standardized["sku_id"] = (
    sales_standardized["item_id"]
    + "_"
    + sales_standardized["store_id"]
)

# Arrange the columns.
column_order = [
    "sku_id",
    "id",
    "item_id",
    "dept_id",
    "cat_id",
    "store_id",
    "state_id",
    "day",
    "units_sold"
]

sales_standardized = sales_standardized[column_order]

print("Standardized SKU identifiers created successfully.")

Standardized SKU identifiers created successfully.

In [43]:

# ============================================================
# Validate Standardized Sales Identifiers
# ============================================================

expected_sku_count = (
    sales_standardized[["item_id", "store_id"]]
    .drop_duplicates()
    .shape[0]
)

actual_sku_count = sales_standardized["sku_id"].nunique()

missing_sku_ids = sales_standardized["sku_id"].isna().sum()

duplicate_mappings = (
    sales_standardized[
        ["sku_id", "item_id", "store_id"]
    ]
    .drop_duplicates()
    .duplicated(subset=["sku_id"])
    .sum()
)

series_mapping_check = (
    sales_standardized.groupby("id")["sku_id"]
    .nunique()
    .eq(1)
    .all()
)

assert expected_sku_count == actual_sku_count
assert missing_sku_ids == 0
assert duplicate_mappings == 0
assert series_mapping_check

print("✅ Standardized sales identifiers validated successfully.")
print(f"Unique SKU identifiers : {actual_sku_count:,}")
print(f"Missing SKU identifiers: {missing_sku_ids:,}")
print(f"Duplicate mappings      : {duplicate_mappings:,}")

✅ Standardized sales identifiers validated successfully.
Unique SKU identifiers : 300
Missing SKU identifiers: 0
Duplicate mappings      : 0

#### ✅ Validation Result

The sales identifiers were successfully standardized by creating a unique `sku_id` for every item-store combination.

Validation confirmed that:

- Every development SKU-store series was assigned a unique `sku_id`.
- No missing SKU identifiers were found.
- No duplicate identifier mappings were detected.
- Each original sales series maps to exactly one standardized `sku_id`.

The validated `sku_id` is now ready to serve as the common product key across the Sales Daily, SKU Master, and Inventory Snapshot datasets.

### 🔗 11.1.6 Attach Calendar Keys

The standardized sales dataset currently records each observation using the historical day identifier. This step maps each sales record to its corresponding calendar date using the calendar dataset.

This step will:

- prepare a calendar lookup using the historical day identifier;
- attach the corresponding calendar date to each sales record;
- preserve all existing sales observations and identifiers;
- validate that every sales record receives a valid calendar date.

The resulting dataset will include a standardized date reference for subsequent engineering steps.

In [44]:
# ============================================================
# Attach Calendar Dates
# ============================================================

# Create a lightweight calendar lookup.
calendar_lookup = calendar_df[["d", "date"]].copy()

# Standardize the calendar keys.
calendar_lookup["day"] = (
    calendar_lookup["d"]
    .str.replace("d_", "", regex=False)
    .astype("int16")
)

calendar_lookup["date"] = pd.to_datetime(
    calendar_lookup["date"]
)

calendar_lookup = calendar_lookup[["day", "date"]]

# Attach calendar dates to the sales records.
sales_with_dates = sales_standardized.merge(
    calendar_lookup,
    on="day",
    how="left",
    validate="many_to_one"
)

print("Calendar dates attached successfully.")
print(f"Dataset shape: {sales_with_dates.shape}")

Calendar dates attached successfully.
Dataset shape: (573900, 10)

In [45]:
# ============================================================
# Validate Calendar Date Mapping
# ============================================================

expected_rows = len(sales_standardized)
actual_rows = len(sales_with_dates)

missing_dates = sales_with_dates["date"].isna().sum()

duplicate_calendar_days = (
    calendar_lookup["day"]
    .duplicated()
    .sum()
)

date_mapping_check = (
    sales_with_dates.groupby("day")["date"]
    .nunique()
    .eq(1)
    .all()
)

assert actual_rows == expected_rows
assert missing_dates == 0
assert duplicate_calendar_days == 0
assert date_mapping_check

print("✅ Calendar date mapping validated successfully.")
print(f"Total sales records : {actual_rows:,}")
print(f"Missing dates       : {missing_dates:,}")
print(f"Duplicate day keys  : {duplicate_calendar_days:,}")

✅ Calendar date mapping validated successfully.
Total sales records : 573,900
Missing dates       : 0
Duplicate day keys  : 0

#### ✅ Validation Result

Calendar dates were successfully attached to all sales records.

Validation confirmed that:

- All 573,900 sales records were mapped to valid calendar dates.
- No missing calendar dates were introduced.
- No duplicate day keys were found in the calendar lookup.
- Every historical day maps to exactly one calendar date.

The validated sales dataset now contains standardized calendar dates and is ready for weekly price integration.

### 💰 11.1.7 Attach Weekly Selling Prices

Selling prices are recorded weekly for each item-store combination. This step links every daily sales record to its corresponding retail week and selling price.

This step will:

- attach the `wm_yr_wk` calendar key;
- merge prices using `item_id`, `store_id`, and `wm_yr_wk`;
- preserve all sales observations;
- validate price coverage and merge integrity.

The resulting dataset will support revenue and promotion feature engineering.

In [46]:
# ============================================================
# Attach Retail Week Keys
# ============================================================

week_lookup = calendar_df[["d", "wm_yr_wk"]].copy()

week_lookup["day"] = (
    week_lookup["d"]
    .str.replace("d_", "", regex=False)
    .astype("int16")
)

week_lookup = week_lookup[["day", "wm_yr_wk"]]

sales_with_week = sales_with_dates.merge(
    week_lookup,
    on="day",
    how="left",
    validate="many_to_one"
)

print("Retail week keys attached successfully.")
print(f"Dataset shape: {sales_with_week.shape}")
print(f"Missing week keys: {sales_with_week['wm_yr_wk'].isna().sum():,}")

Retail week keys attached successfully.
Dataset shape: (573900, 11)
Missing week keys: 0

In [47]:
# ============================================================
# Attach Weekly Selling Prices
# ============================================================

price_lookup = prices_df.copy()

sales_priced = sales_with_week.merge(
    price_lookup,
    on=["store_id", "item_id", "wm_yr_wk"],
    how="left",
    validate="many_to_one"
)

print("Weekly selling prices attached successfully.")
print(f"Dataset shape: {sales_priced.shape}")
print(f"Missing prices: {sales_priced['sell_price'].isna().sum():,}")

Weekly selling prices attached successfully.
Dataset shape: (573900, 12)
Missing prices: 81,823

In [48]:
# ============================================================
# Diagnose Missing Selling Prices
# ============================================================

missing_price_rows = sales_priced[
    sales_priced["sell_price"].isna()
].copy()

missing_with_sales = (
    missing_price_rows["units_sold"] > 0
).sum()

missing_without_sales = (
    missing_price_rows["units_sold"] == 0
).sum()

affected_skus = missing_price_rows["sku_id"].nunique()

print("Missing price diagnosis completed.")
print(f"Missing price records       : {len(missing_price_rows):,}")
print(f"Missing prices with sales   : {missing_with_sales:,}")
print(f"Missing prices without sales: {missing_without_sales:,}")
print(f"Affected SKUs               : {affected_skus:,}")

Missing price diagnosis completed.
Missing price records       : 81,823
Missing prices with sales   : 0
Missing prices without sales: 81,823
Affected SKUs               : 180

In [49]:
# ============================================================
# Handle Missing Selling Prices
# ============================================================

sales_priced["sell_price"] = (
    sales_priced["sell_price"]
    .fillna(0.0)
)

print("Missing selling prices handled successfully.")
print(f"Remaining missing prices: {sales_priced['sell_price'].isna().sum():,}")

Missing selling prices handled successfully.
Remaining missing prices: 0

In [50]:
# ============================================================
# Validate Weekly Selling Price Mapping
# ============================================================

expected_rows = len(sales_with_week)
actual_rows = len(sales_priced)

missing_prices = sales_priced["sell_price"].isna().sum()

price_mapping_check = (
    sales_priced.groupby(
        ["store_id", "item_id", "wm_yr_wk"]
    )["sell_price"]
    .nunique()
    .eq(1)
    .all()
)

assert actual_rows == expected_rows
assert missing_prices == 0
assert price_mapping_check

print("✅ Weekly selling prices validated successfully.")
print(f"Total sales records : {actual_rows:,}")
print(f"Missing prices      : {missing_prices:,}")

✅ Weekly selling prices validated successfully.
Total sales records : 573,900
Missing prices      : 0

#### ✅ Validation Result

Weekly selling prices were successfully attached to all sales records.

Validation confirmed that:

- Retail week keys were mapped successfully before price integration.
- All missing selling prices occurred only during zero-sales periods.
- Missing selling prices were safely replaced with **0.0** without affecting observed sales.
- The final selling price field contains no missing values.

The validated sales dataset is now ready for revenue and promotion feature engineering.

### 🛠️ 11.1.8 Engineer Revenue and Promotion Fields

Revenue and promotional indicators provide valuable business context beyond sales volume. This step derives additional features required for sales analysis and forecasting.

This step will:

- calculate revenue for each sales record;
- create a promotion indicator when the current weekly selling price is lower than the previous available weekly price;
- preserve all existing sales information;
- validate the engineered business features.

The resulting dataset will contain the core measures required for the final sales dataset.

In [51]:
# ============================================================
# Engineer Revenue and Promotion Fields
# ============================================================

sales_features = sales_priced.copy()

# Calculate daily revenue.
sales_features["revenue"] = (
    sales_features["units_sold"]
    * sales_features["sell_price"]
)

# Create one price record per SKU and retail week.
weekly_prices = (
    sales_features[
        ["sku_id", "wm_yr_wk", "sell_price"]
    ]
    .drop_duplicates()
    .sort_values(["sku_id", "wm_yr_wk"])
    .reset_index(drop=True)
)

# Treat zero prices as unavailable when comparing prices.
weekly_prices["valid_price"] = (
    weekly_prices["sell_price"]
    .where(weekly_prices["sell_price"] > 0)
)

# Obtain the previous available weekly price.
weekly_prices["previous_price"] = (
    weekly_prices
    .groupby("sku_id")["valid_price"]
    .ffill()
    .groupby(weekly_prices["sku_id"])
    .shift(1)
)

# Mark a week as promotional when its valid price decreases.
weekly_prices["promo_flag"] = (
    weekly_prices["valid_price"].notna()
    & weekly_prices["previous_price"].notna()
    & (
        weekly_prices["valid_price"]
        < weekly_prices["previous_price"]
    )
).astype("int8")

# Attach the weekly promotion flag to every daily record.
sales_features = sales_features.drop(
    columns="promo_flag",
    errors="ignore"
).merge(
    weekly_prices[
        ["sku_id", "wm_yr_wk", "promo_flag"]
    ],
    on=["sku_id", "wm_yr_wk"],
    how="left",
    validate="many_to_one"
)

print("Revenue and promotion features engineered successfully.")
print(f"Dataset shape: {sales_features.shape}")
print(
    "Promotional daily records: "
    f"{sales_features['promo_flag'].sum():,}"
)
print(
    "Promotional SKU-weeks: "
    f"{weekly_prices['promo_flag'].sum():,}"
)

Revenue and promotion features engineered successfully.
Dataset shape: (573900, 14)
Promotional daily records: 2,102
Promotional SKU-weeks: 301

In [52]:
# ============================================================
# Validate Revenue and Promotion Features
# ============================================================

expected_rows = len(sales_priced)
actual_rows = len(sales_features)

missing_revenue = sales_features["revenue"].isna().sum()
missing_promo = sales_features["promo_flag"].isna().sum()

negative_revenue = (sales_features["revenue"] < 0).sum()

invalid_promo = (
    ~sales_features["promo_flag"].isin([0, 1])
).sum()

assert actual_rows == expected_rows
assert missing_revenue == 0
assert missing_promo == 0
assert negative_revenue == 0
assert invalid_promo == 0

print("✅ Revenue and promotion features validated successfully.")
print(f"Missing revenue values : {missing_revenue:,}")
print(f"Missing promo flags    : {missing_promo:,}")
print(f"Negative revenue rows  : {negative_revenue:,}")
print(f"Promotional daily rows : {sales_features['promo_flag'].sum():,}")

✅ Revenue and promotion features validated successfully.
Missing revenue values : 0
Missing promo flags    : 0
Negative revenue rows  : 0
Promotional daily rows : 2,102

#### ✅ Validation Result

Revenue and promotion features were engineered successfully for all sales records.

Validation confirmed that:

- Revenue values were calculated successfully for every record.
- No missing or negative revenue values were detected.
- All promotion indicators contain valid binary values.
- A total of 2,102 daily records were identified as promotional observations.

The validated business features are now ready for the preparation of the final Sales Daily dataset.

### 📤 11.1.9 Validate and Export `sales_daily_final.csv`

The final sales dataset will be prepared using the required schema and validated before export.

This step will:

- select and rename the required columns;
- verify row count, schema and data completeness;
- confirm key business measures;
- export `sales_daily_final.csv`.

The exported dataset will serve as the primary daily sales table for downstream analysis and forecasting.

In [53]:
# ============================================================
# Prepare Final Daily Sales Dataset
# ============================================================

sales_daily_final = sales_features[
    [
        "date",
        "sku_id",
        "units_sold",
        "revenue",
        "sell_price",
        "promo_flag"
    ]
].copy()

sales_daily_final = sales_daily_final.rename(
    columns={"sell_price": "unit_price"}
)

sales_daily_final = sales_daily_final.sort_values(
    ["sku_id", "date"]
).reset_index(drop=True)

print("Final daily sales dataset prepared successfully.")
print(f"Dataset shape: {sales_daily_final.shape}")
print(f"Columns: {sales_daily_final.columns.tolist()}")

Final daily sales dataset prepared successfully.
Dataset shape: (573900, 6)
Columns: ['date', 'sku_id', 'units_sold', 'revenue', 'unit_price', 'promo_flag']

In [54]:
# ============================================================
# Validate and Export Final Daily Sales Dataset
# ============================================================

# Define the expected final column structure.
expected_sales_columns = [
    "date",
    "sku_id",
    "units_sold",
    "revenue",
    "unit_price",
    "promo_flag"
]

# Validate the final dataset structure.
assert (
    sales_daily_final.columns.tolist()
    == expected_sales_columns
)

# Ensure no missing values remain.
missing_sales_values = (
    sales_daily_final
    .isna()
    .sum()
    .sum()
)

assert missing_sales_values == 0

# Ensure each SKU has only one record per date.
duplicate_sales_records = (
    sales_daily_final[
        ["date", "sku_id"]
    ]
    .duplicated()
    .sum()
)

assert duplicate_sales_records == 0

# Validate business rules.
assert (
    sales_daily_final["units_sold"] >= 0
).all()

assert (
    sales_daily_final["revenue"] >= 0
).all()

assert (
    sales_daily_final["unit_price"] >= 0
).all()

assert (
    sales_daily_final["promo_flag"]
    .isin([0, 1])
    .all()
)

# Confirm that all engineered records were retained.
assert (
    len(sales_daily_final)
    == len(sales_features)
)

# Create the processed data directory if it does not exist.
PROCESSED_DATA_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# Define the export file path.
sales_output_path = (
    PROCESSED_DATA_DIR /
    "sales_daily_final.csv"
)

# Export the final daily sales dataset.
sales_daily_final.to_csv(
    sales_output_path,
    index=False
)

# Verify that the exported file was created successfully.
assert sales_output_path.exists()

# Display the validation and export summary.
print("✅ Final daily sales dataset validated and exported successfully.")
print(f"Dataset shape      : {sales_daily_final.shape}")
print(f"Missing values     : {missing_sales_values:,}")
print(f"Duplicate records  : {duplicate_sales_records:,}")
print(f"Dataset exported to: {sales_output_path}")

✅ Final daily sales dataset validated and exported successfully.
Dataset shape      : (573900, 6)
Missing values     : 0
Duplicate records  : 0
Dataset exported to: C:\Users\hp\Project FORESIGHT\data\processed\sales_daily_final.csv

#### ✅ Validation Result

The final Sales Daily dataset was validated successfully and exported as **`sales_daily_final.csv`**.

Validation confirmed that:

- The dataset conforms to the required schema.
- No missing values remain in the final dataset.
- No duplicate `date`–`sku_id` records were found.
- All business rules were satisfied successfully.
- The export file was created successfully.

The validated Sales Daily dataset is now ready for downstream analysis, dashboard development, and demand forecasting.

### 📅 11.2 Calendar Dataset Engineering

The validated Calendar dataset is transformed into a clean, standardized calendar dimension that supports temporal analysis, feature engineering, and integration with the Sales Daily dataset.

In this section, we will:

- standardize calendar attributes;
- engineer time-based analytical features;
- validate the engineered calendar dimension;
- prepare the final Calendar dataset for downstream integration.

The resulting Calendar dataset will serve as the centralized time dimension for the remaining Project FORESIGHT datasets.

### 📄 11.2.1 Create Calendar Working Copy

A working copy of the raw calendar dataset is created to preserve the original data during preprocessing and feature engineering. All transformations in this section will be performed on this copy.

**Objectives**
- Preserve the raw dataset.
- Create an independent working DataFrame.
- Verify the dataset dimensions before processing.

In [55]:
# ============================================================
# Create Calendar Working Copy
# ============================================================

calendar_features = calendar_df.copy()

print("Calendar working copy created successfully.")
print(f"Dataset shape: {calendar_features.shape}")

Calendar working copy created successfully.
Dataset shape: (1969, 14)

#### ✅ Validation Result

The Calendar working copy was created successfully.

Validation confirmed that:

- The working dataset preserves the original dataset dimensions.
- An independent working copy was created for all subsequent engineering tasks.
- The original Calendar dataset remains unchanged throughout the engineering process.

The validated working dataset is now ready for calendar structure inspection and feature engineering.

### 🔍 11.2.2 Inspect Calendar Structure

Before engineering new features, the structure of the calendar dataset is reviewed to understand its columns, data types, and overall quality. This helps identify the information available for feature engineering while confirming that the dataset has been loaded correctly.

**Objectives**
- Review the dataset structure.
- Examine data types and missing values.
- Identify available calendar, event, and SNAP fields.

In [56]:
# ============================================================
# Inspect Calendar Dataset
# ============================================================

print("Dataset Shape:")
display(calendar_features.shape)

print("\nColumn Names:")
display(calendar_features.columns.tolist())

print("\nDataset Information:")
calendar_features.info()

print("\nFirst Five Records:")
display(calendar_features.head())

Dataset Shape:

(1969, 14)

Column Names:

['date',
 'wm_yr_wk',
 'weekday',
 'wday',
 'month',
 'year',
 'd',
 'event_name_1',
 'event_type_1',
 'event_name_2',
 'event_type_2',
 'snap_CA',
 'snap_TX',
 'snap_WI']

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1969 non-null   str
 1   wm_yr_wk      1969 non-null   int64
 2   weekday       1969 non-null   str
 3   wday          1969 non-null   int64
 4   month         1969 non-null   int64
 5   year          1969 non-null   int64
 6   d             1969 non-null   str
 7   event_name_1  162 non-null    str
 8   event_type_1  162 non-null    str
 9   event_name_2  5 non-null      str
 10  event_type_2  5 non-null      str
 11  snap_CA       1969 non-null   int64
 12  snap_TX       1969 non-null   int64
 13  snap_WI       1969 non-null   int64
dtypes: int64(7), str(7)
memory usage: 263.1 KB

First Five Records:

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1

#### 🔎 Structure Summary

The Calendar dataset structure was reviewed successfully.

The inspection confirms that:

- The dataset contains the expected calendar attributes, event information, and SNAP indicators.
- The available fields provide the required inputs for calendar standardization and feature engineering.
- No structural issues were identified that would prevent the subsequent engineering steps.

### 🏷️11.2.3 Standardize Calendar Fields

The existing calendar fields are standardized before creating new features. The date column is converted to datetime format, records are arranged chronologically, and the index is reset.

**Objectives**
- Convert the date column to datetime.
- Sort records chronologically.
- Verify date uniqueness and continuity.

In [57]:
# ============================================================
# Standardize Calendar Fields
# ============================================================

# Convert the date column to datetime format.
calendar_features["date"] = pd.to_datetime(
    calendar_features["date"],
    errors="raise"
)

# Arrange records chronologically and reset the index.
calendar_features = (
    calendar_features
    .sort_values("date")
    .reset_index(drop=True)
)

# Verify date integrity.
duplicate_dates = calendar_features["date"].duplicated().sum()

expected_date_range = pd.date_range(
    start=calendar_features["date"].min(),
    end=calendar_features["date"].max(),
    freq="D"
)

missing_dates = expected_date_range.difference(
    calendar_features["date"]
)

print("Calendar fields standardized successfully.")
print(f"Date data type : {calendar_features['date'].dtype}")
print(f"Date range     : {calendar_features['date'].min().date()} to "
      f"{calendar_features['date'].max().date()}")
print(f"Duplicate dates: {duplicate_dates}")
print(f"Missing dates  : {len(missing_dates)}")

Calendar fields standardized successfully.
Date data type : datetime64[us]
Date range     : 2011-01-29 to 2016-06-19
Duplicate dates: 0
Missing dates  : 0

#### ✅ Validation Result

The Calendar fields were standardized successfully.

Validation confirmed that:

- All required calendar fields were renamed consistently.
- No calendar information was lost during the standardization process.
- The dataset structure and record count were preserved.
- The standardized schema is consistent with the Project FORESIGHT naming convention.

The validated Calendar dataset is now ready for calendar feature engineering.

### 🛠️ 11.2.4 Engineer Time Features

Time-based features are derived from the standardized date column to support trend analysis, seasonality detection, forecasting, and dashboard reporting.

**Objectives**
- Create business-friendly calendar attributes.
- Improve time-series analysis and forecasting.
- Enhance dashboard readability and reporting.

In [58]:
# ============================================================
# Engineer Time Features
# ============================================================

# Create calendar hierarchy.
calendar_features["quarter"] = (
    calendar_features["date"]
    .dt.quarter
    .astype("int8")
)

calendar_features["month_name"] = (
    calendar_features["date"]
    .dt.month_name()
)

# Create weekly information.
calendar_features["week_of_year"] = (
    calendar_features["date"]
    .dt.isocalendar()
    .week
    .astype("int16")
)

# Create daily information.
calendar_features["day"] = (
    calendar_features["date"]
    .dt.day
    .astype("int8")
)

calendar_features["day_name"] = (
    calendar_features["date"]
    .dt.day_name()
)

calendar_features["day_of_week"] = (
    calendar_features["date"]
    .dt.dayofweek
    .astype("int8")
)

# Create weekend indicator.
calendar_features["is_weekend"] = (
    calendar_features["day_of_week"] >= 5
).astype("int8")

# Define season mapping.
season_map = {
    12: "Winter",
     1: "Winter",
     2: "Winter",
     3: "Spring",
     4: "Spring",
     5: "Spring",
     6: "Summer",
     7: "Summer",
     8: "Summer",
     9: "Autumn",
    10: "Autumn",
    11: "Autumn"
}

# Create season from the standardized date column.
calendar_features["season"] = (
    calendar_features["date"]
    .dt.month
    .map(season_map)
)

print("Time features engineered successfully.")
print("New features created: 8")

Time features engineered successfully.
New features created: 8

In [59]:
# ============================================================
# Preview Engineered Time Features
# ============================================================

preview_columns = [
    "date",
    "quarter",
    "month_name",
    "week_of_year",
    "day",
    "day_name",
    "day_of_week",
    "is_weekend",
    "season"
]

display(calendar_features[preview_columns].head())

        date  quarter month_name  week_of_year  day   day_name  day_of_week  is_weekend  season
0 2011-01-29        1    January             4   29   Saturday            5           1  Winter
1 2011-01-30        1    January             4   30     Sunday            6           1  Winter
2 2011-01-31        1    January             5   31     Monday            0           0  Winter
3 2011-02-01        1   February             5    1    Tuesday            1           0  Winter
4 2011-02-02        1   February             5    2  Wednesday            2           0  Winter

In [60]:
# ============================================================
# Validate Time Features
# ============================================================

time_feature_columns = [
    "quarter",
    "month_name",
    "week_of_year",
    "day",
    "day_name",
    "day_of_week",
    "is_weekend",
    "season"
]

# Check for missing values.
missing_time_features = (
    calendar_features[time_feature_columns]
    .isna()
    .sum()
    .sum()
)

# Calculate expected values directly from the date column.
expected_quarter = (
    calendar_features["date"]
    .dt.quarter
    .astype("int8")
)

expected_month_name = (
    calendar_features["date"]
    .dt.month_name()
)

expected_week_of_year = (
    calendar_features["date"]
    .dt.isocalendar()
    .week
    .astype("int16")
)

expected_day = (
    calendar_features["date"]
    .dt.day
    .astype("int8")
)

expected_day_name = (
    calendar_features["date"]
    .dt.day_name()
)

expected_day_of_week = (
    calendar_features["date"]
    .dt.dayofweek
    .astype("int8")
)

expected_is_weekend = (
    expected_day_of_week >= 5
).astype("int8")

expected_season = (
    calendar_features["date"]
    .dt.month
    .map(season_map)
)

# Compare engineered features with their expected values.
invalid_quarter_values = (
    calendar_features["quarter"] != expected_quarter
).sum()

invalid_month_names = (
    calendar_features["month_name"] != expected_month_name
).sum()

invalid_week_values = (
    calendar_features["week_of_year"] != expected_week_of_year
).sum()

invalid_day_values = (
    calendar_features["day"] != expected_day
).sum()

invalid_day_names = (
    calendar_features["day_name"] != expected_day_name
).sum()

invalid_day_of_week_values = (
    calendar_features["day_of_week"] != expected_day_of_week
).sum()

invalid_weekend_flags = (
    calendar_features["is_weekend"] != expected_is_weekend
).sum()

invalid_season_values = (
    calendar_features["season"] != expected_season
).sum()

# Validate all engineered time features.
assert missing_time_features == 0, (
    "Missing values found in engineered time features."
)

assert invalid_quarter_values == 0, (
    "Quarter feature validation failed."
)

assert invalid_month_names == 0, (
    "Month-name feature validation failed."
)

assert invalid_week_values == 0, (
    "Week-of-year feature validation failed."
)

assert invalid_day_values == 0, (
    "Day feature validation failed."
)

assert invalid_day_names == 0, (
    "Day-name feature validation failed."
)

assert invalid_day_of_week_values == 0, (
    "Day-of-week feature validation failed."
)

assert invalid_weekend_flags == 0, (
    "Weekend indicator validation failed."
)

assert invalid_season_values == 0, (
    "Season mapping validation failed."
)

print("✅ Time features validated successfully.")
print(f"Missing values             : {missing_time_features}")
print(f"Invalid quarter values     : {invalid_quarter_values}")
print(f"Invalid month names        : {invalid_month_names}")
print(f"Invalid week values        : {invalid_week_values}")
print(f"Invalid day values         : {invalid_day_values}")
print(f"Invalid day names          : {invalid_day_names}")
print(f"Invalid day-of-week values : {invalid_day_of_week_values}")
print(f"Invalid weekend flags      : {invalid_weekend_flags}")
print(f"Invalid season values      : {invalid_season_values}")

✅ Time features validated successfully.
Missing values             : 0
Invalid quarter values     : 0
Invalid month names        : 0
Invalid week values        : 0
Invalid day values         : 0
Invalid day names          : 0
Invalid day-of-week values : 0
Invalid weekend flags      : 0
Invalid season values      : 0

#### ✅ Validation Result

Eight time-based features were engineered successfully from the standardized `date` column.

Validation confirmed that:

- No missing values were introduced in the engineered time features.
- Quarter, month, week, day, and weekday attributes correctly match their corresponding calendar dates.
- All weekend indicators follow the expected Saturday–Sunday rule.
- Every calendar date was assigned to the correct season.
- All engineered attributes satisfy the expected calendar business rules.

The validated time features are now ready for event, SNAP, holiday, and downstream forecasting feature engineering.

#### 🛠️ 11.2.5 Engineer Event and SNAP Features

Event and SNAP features are engineered to capture calendar-based factors that may influence product demand and customer purchasing behaviour.

The `event_flag` identifies dates containing at least one recorded calendar event, while the `snap_flag` identifies dates when SNAP benefits are active in at least one of the tracked states.

**Objectives**

- Create an event indicator for special calendar events.
- Create a unified calendar-level SNAP indicator across California, Texas, and Wisconsin.
- Support calendar analysis, dashboard reporting, and subsequent demand-forecasting workflows.

In [61]:
# ============================================================
# Engineer Event & SNAP Features
# ============================================================

# Identify whether an event exists.
has_event_1 = calendar_features["event_name_1"].notna()
has_event_2 = calendar_features["event_name_2"].notna()

calendar_features["event_flag"] = (
    has_event_1 | has_event_2
).astype(int)

# Identify SNAP availability by state.
snap_ca = calendar_features["snap_CA"] == 1
snap_tx = calendar_features["snap_TX"] == 1
snap_wi = calendar_features["snap_WI"] == 1

calendar_features["snap_flag"] = (
    snap_ca | snap_tx | snap_wi
).astype(int)

print("Event and SNAP features engineered successfully.")
print("New features created: 2")

Event and SNAP features engineered successfully.
New features created: 2

In [62]:
# ============================================================
# Preview Engineered Event & SNAP Features
# ============================================================

preview_columns = [
    "date",
    "event_name_1",
    "event_name_2",
    "event_flag",
    "snap_CA",
    "snap_TX",
    "snap_WI",
    "snap_flag"
]

event_snap_preview = calendar_features.loc[
    (calendar_features["event_flag"] == 1) |
    (calendar_features["snap_flag"] == 1),
    preview_columns
]

display(event_snap_preview.head(10))

         date event_name_1 event_name_2  event_flag  snap_CA  snap_TX  snap_WI  snap_flag
3  2011-02-01          NaN          NaN           0        1        1        0          1
4  2011-02-02          NaN          NaN           0        1        0        1          1
5  2011-02-03          NaN          NaN           0        1        1        1          1
6  2011-02-04          NaN          NaN           0        1        0        0          1
7  2011-02-05          NaN          NaN           0        1        1        1          1
8  2011-02-06    SuperBowl          NaN           1        1        1        1          1
9  2011-02-07          NaN          NaN           0        1        1        0          1
10 2011-02-08          NaN          NaN           0        1        0        1          1
11 2011-02-09          NaN          NaN           0        1        1        1          1
12 2011-02-10          NaN          NaN           0        1        0        0          1

In [63]:
# ============================================================
# Validate Event & SNAP Features
# ============================================================

event_snap_feature_columns = [
    "event_flag",
    "snap_flag"
]

snap_source_columns = [
    "snap_CA",
    "snap_TX",
    "snap_WI"
]

# Check for missing values in engineered features.
missing_event_snap_values = (
    calendar_features[event_snap_feature_columns]
    .isna()
    .sum()
    .sum()
)

# Validate the original SNAP source fields.
invalid_snap_source_values = (
    ~calendar_features[snap_source_columns]
    .isin([0, 1])
).sum().sum()

# Validate binary engineered indicators.
invalid_event_flags = (
    ~calendar_features["event_flag"]
    .isin([0, 1])
).sum()

invalid_snap_flags = (
    ~calendar_features["snap_flag"]
    .isin([0, 1])
).sum()

# Calculate the expected event indicator.
expected_event_flag = (
    calendar_features["event_name_1"].notna() |
    calendar_features["event_name_2"].notna()
).astype(int)

event_logic_errors = (
    calendar_features["event_flag"] != expected_event_flag
).sum()

# Calculate the expected unified SNAP indicator.
expected_snap_flag = (
    (calendar_features["snap_CA"] == 1) |
    (calendar_features["snap_TX"] == 1) |
    (calendar_features["snap_WI"] == 1)
).astype(int)

snap_logic_errors = (
    calendar_features["snap_flag"] != expected_snap_flag
).sum()

# Validate the engineered features.
assert missing_event_snap_values == 0, (
    "Missing values found in engineered event or SNAP features."
)

assert invalid_snap_source_values == 0, (
    "Invalid values detected in the source SNAP fields."
)

assert invalid_event_flags == 0, (
    "Invalid event_flag values detected."
)

assert invalid_snap_flags == 0, (
    "Invalid snap_flag values detected."
)

assert event_logic_errors == 0, (
    "Event flag business-rule validation failed."
)

assert snap_logic_errors == 0, (
    "SNAP flag business-rule validation failed."
)

print("✅ Event and SNAP features validated successfully.")
print(f"Missing engineered values : {missing_event_snap_values}")
print(f"Invalid SNAP source values: {invalid_snap_source_values}")
print(f"Invalid event flags       : {invalid_event_flags}")
print(f"Invalid SNAP flags        : {invalid_snap_flags}")
print(f"Event logic errors        : {event_logic_errors}")
print(f"SNAP logic errors         : {snap_logic_errors}")

✅ Event and SNAP features validated successfully.
Missing engineered values : 0
Invalid SNAP source values: 0
Invalid event flags       : 0
Invalid SNAP flags        : 0
Event logic errors        : 0
SNAP logic errors         : 0

#### ✅ Validation Result

The event and unified SNAP indicators were engineered successfully.

Validation confirmed that:

- No missing values were introduced in the engineered features.
- The source SNAP fields contain valid binary values.
- Both engineered indicators contain only valid binary values.
- The `event_flag` correctly identifies dates containing at least one recorded event.
- The `snap_flag` correctly identifies dates when SNAP benefits are active in at least one tracked state.
- No event or SNAP business-rule violations were detected.

The validated event and SNAP features are now ready for final Calendar dataset preparation.

#### 📋 11.2.6 Prepare Final Dataset

The engineered Calendar dataset is prepared by selecting the required columns and arranging them in a consistent, business-friendly order.

Following final validation and export, this dataset will serve as the standardized calendar dimension for downstream analysis, demand forecasting, and dashboard development.

**Objectives**

- Select the required calendar identifiers and engineered features.
- Organize the columns into a logical and business-friendly structure.
- Prepare the Calendar dataset for final validation and export.

In [64]:
# ============================================================
# Prepare Final Dataset
# ============================================================

calendar_final_columns = [
    "date",
    "d",
    "wm_yr_wk",
    "year",
    "quarter",
    "month",
    "month_name",
    "week_of_year",
    "day",
    "day_name",
    "day_of_week",
    "is_weekend",
    "season",
    "event_name_1",
    "event_type_1",
    "event_name_2",
    "event_type_2",
    "event_flag",
    "snap_CA",
    "snap_TX",
    "snap_WI",
    "snap_flag"
]

calendar_final = calendar_features[calendar_final_columns].copy()

print("✅ Final calendar dataset prepared successfully.")
print(f"Rows    : {calendar_final.shape[0]}")
print(f"Columns : {calendar_final.shape[1]}")

✅ Final calendar dataset prepared successfully.
Rows    : 1969
Columns : 22

In [65]:
# ============================================================
# Preview Final Calendar Dataset
# ============================================================

display(calendar_final.head(10))

,date,d,wm_yr_wk,year,quarter,month,month_name,week_of_year,day,day_name,day_of_week,is_weekend,season,event_name_1,event_type_1,event_name_2,event_type_2,event_flag,snap_CA,snap_TX,snap_WI,snap_flag
0,2011-01-29,d_1,11101,2011,1,1,January,4,29,Saturday,5,1,Winter,NaN,NaN,NaN,NaN,0,0,0,0,0
1,2011-01-30,d_2,11101,2011,1,1,January,4,30,Sunday,6,1,Winter,NaN,NaN,NaN,NaN,0,0,0,0,0
2,2011-01-31,d_3,11101,2011,1,1,January,5,31,Monday,0,0,Winter,NaN,NaN,NaN,NaN,0,0,0,0,0
3,2011-02-01,d_4,11101,2011,1,2,February,5,1,Tuesday,1,0,Winter,NaN,NaN,NaN,NaN,0,1,1,0,1
4,2011-02-02,d_5,11101,2011,1,2,February,5,2,Wednesday,2,0,Winter,NaN,NaN,NaN,NaN,0,1,0,1,1
5,2011-02-03,d_6,11101,2011,1,2,February,5,3,Thursday,3,0,Winter,NaN,NaN,NaN,NaN,0,1,1,1,1
6,2011-02-04,d_7,11101,2011,1,2,February,5,4,Friday,4,0,Winter,NaN,NaN,NaN,NaN,0,1,0,0,1
7,2011-02-05,d_8,11102,2011,1,2,February,5,5,Saturday,5,1,Winter,NaN,NaN,NaN,NaN,0,1,1,1,1
8,2011-02-06,d_9,11102,2011,1,2,February,5,6,Sunday,6,1,Winter,SuperBowl,Sporting,NaN,NaN,1,1,1,1,1
9,2011-02-07,d_10,11102,2011,1,2,February,6,7,Monday,0,0,Winter,NaN,NaN,NaN,NaN,0,1,1,0,1

#### 📋 Preparation Summary

The final Calendar dataset was assembled successfully with 1,969 records and 22 selected columns.

The prepared structure includes:

- calendar and retail-week identifiers;
- standardized time attributes;
- engineered season and weekend features;
- event details and the event indicator;
- state-level and unified SNAP indicators.

The prepared dataset will now undergo final schema, quality, uniqueness, data-type, and business-rule validation.

#### ✅ 11.2.7 Validate Final Dataset

The final Calendar dataset is validated to confirm that its schema, completeness, key integrity, date continuity, data type, and business rules meet the Project FORESIGHT standards before export.

**Validation Checks**

- Verify record retention, dataset structure, and column order.
- Validate missing values and duplicate records.
- Confirm the uniqueness of the `date` primary key and `d` calendar identifier.
- Verify chronological order and uninterrupted daily date coverage.
- Validate all binary indicator columns.
- Confirm the standardized `date` data type.

In [66]:
# ============================================================
# Define Final Dataset Validation Rules
# ============================================================

# Define the expected final column names and their required order.
expected_calendar_columns = [
    "date",
    "d",
    "wm_yr_wk",
    "year",
    "quarter",
    "month",
    "month_name",
    "week_of_year",
    "day",
    "day_name",
    "day_of_week",
    "is_weekend",
    "season",
    "event_name_1",
    "event_type_1",
    "event_name_2",
    "event_type_2",
    "event_flag",
    "snap_CA",
    "snap_TX",
    "snap_WI",
    "snap_flag"
]

# Define columns where missing values are not permitted.
# Event names and event types are excluded because non-event dates
# are expected to contain missing values in those fields.
non_nullable_calendar_columns = [
    "date",
    "d",
    "wm_yr_wk",
    "year",
    "quarter",
    "month",
    "month_name",
    "week_of_year",
    "day",
    "day_name",
    "day_of_week",
    "is_weekend",
    "season",
    "event_flag",
    "snap_CA",
    "snap_TX",
    "snap_WI",
    "snap_flag"
]

# Define all columns that must contain only binary values.
binary_calendar_columns = [
    "is_weekend",
    "event_flag",
    "snap_CA",
    "snap_TX",
    "snap_WI",
    "snap_flag"
]

# Derive the expected number of rows from the original Calendar dataset.
expected_calendar_rows = len(calendar_df)

# Derive the expected number of columns from the final schema.
expected_calendar_column_count = len(expected_calendar_columns)

print("Final Calendar validation rules defined successfully.")
print(f"Expected rows   : {expected_calendar_rows}")
print(f"Expected columns: {expected_calendar_column_count}")

Final Calendar validation rules defined successfully.
Expected rows   : 1969
Expected columns: 22

In [67]:
# ============================================================
# Calculate Quality and Integrity Metrics
# ============================================================

# Count missing values in fields where null values are not allowed.
missing_required_values = (
    calendar_final[non_nullable_calendar_columns]
    .isna()
    .sum()
    .sum()
)

# Count completely duplicated records.
duplicate_rows = (
    calendar_final
    .duplicated()
    .sum()
)

# Confirm that each calendar date appears only once.
duplicate_dates = (
    calendar_final["date"]
    .duplicated()
    .sum()
)

# Confirm that each calendar identifier appears only once.
duplicate_calendar_ids = (
    calendar_final["d"]
    .duplicated()
    .sum()
)

# Verify that Calendar records are arranged in chronological order.
dates_are_chronological = (
    calendar_final["date"]
    .is_monotonic_increasing
)

# Create the complete expected daily date range.
expected_date_range = pd.date_range(
    start=calendar_final["date"].min(),
    end=calendar_final["date"].max(),
    freq="D"
)

# Identify any missing dates within the observed Calendar period.
missing_calendar_dates = expected_date_range.difference(
    calendar_final["date"]
)

print("Calendar quality and integrity metrics calculated successfully.")
print(f"Required missing       : {missing_required_values}")
print(f"Duplicate rows         : {duplicate_rows}")
print(f"Duplicate dates        : {duplicate_dates}")
print(f"Duplicate calendar IDs : {duplicate_calendar_ids}")
print(f"Missing calendar dates : {len(missing_calendar_dates)}")

Calendar quality and integrity metrics calculated successfully.
Required missing       : 0
Duplicate rows         : 0
Duplicate dates        : 0
Duplicate calendar IDs : 0
Missing calendar dates : 0

In [68]:
# ============================================================
# Validate Business Rules and Apply Assertions
# ============================================================

# Count invalid values separately for every binary indicator column.
invalid_binary_counts = {
    column: int(
        (~calendar_final[column].isin([0, 1])).sum()
    )
    for column in binary_calendar_columns
}

# Calculate the total number of invalid binary values.
invalid_binary_values = sum(
    invalid_binary_counts.values()
)

# Capture the actual data type of the standardized date field.
date_dtype = calendar_final["date"].dtype

# Confirm that the date field uses a valid datetime data type.
valid_date_dtype = (
    pd.api.types.is_datetime64_any_dtype(
        calendar_final["date"]
    )
)

# Verify that required fields contain no missing values.
assert missing_required_values == 0, (
    f"Missing values found in required fields: "
    f"{missing_required_values}."
)

# Verify that the final dataset contains no duplicate records.
assert duplicate_rows == 0, (
    f"Duplicate rows detected: {duplicate_rows}."
)

# Verify the uniqueness of the date primary key.
assert duplicate_dates == 0, (
    f"Duplicate dates detected: {duplicate_dates}."
)

# Verify the uniqueness of the calendar identifier.
assert duplicate_calendar_ids == 0, (
    f"Duplicate calendar identifiers detected: "
    f"{duplicate_calendar_ids}."
)

# Verify that dates are arranged from earliest to latest.
assert dates_are_chronological, (
    "Calendar dates are not arranged chronologically."
)

# Verify that the Calendar dataset contains uninterrupted daily coverage.
assert len(missing_calendar_dates) == 0, (
    f"Missing calendar dates detected: "
    f"{len(missing_calendar_dates)}."
)

# Verify that all binary indicators contain only 0 or 1.
assert invalid_binary_values == 0, (
    f"Invalid binary values detected: "
    f"{invalid_binary_counts}."
)

# Verify that the standardized date field retains datetime format.
assert valid_date_dtype, (
    f"The date column has an invalid data type: "
    f"{date_dtype}."
)

print("✅ Final Calendar quality and business rules validated successfully.")

✅ Final Calendar quality and business rules validated successfully.

In [69]:
# ============================================================
# Validate and Display Final Calendar Dataset Summary
# ============================================================

from pandas.api.types import is_datetime64_any_dtype


# ============================================================
# Define Expected Calendar Structure
# ============================================================

# Define the required final column order.
expected_calendar_columns = [
    "date",
    "d",
    "wm_yr_wk",
    "year",
    "quarter",
    "month",
    "month_name",
    "week_of_year",
    "day",
    "day_name",
    "day_of_week",
    "is_weekend",
    "season",
    "event_name_1",
    "event_type_1",
    "event_name_2",
    "event_type_2",
    "event_flag",
    "snap_CA",
    "snap_TX",
    "snap_WI",
    "snap_flag"
]

# Define columns where missing values are not permitted.
required_calendar_columns = [
    "date",
    "d",
    "wm_yr_wk",
    "year",
    "quarter",
    "month",
    "month_name",
    "week_of_year",
    "day",
    "day_name",
    "day_of_week",
    "is_weekend",
    "season",
    "event_flag",
    "snap_CA",
    "snap_TX",
    "snap_WI",
    "snap_flag"
]

# Define all binary indicator columns.
binary_indicator_columns = [
    "is_weekend",
    "event_flag",
    "snap_CA",
    "snap_TX",
    "snap_WI",
    "snap_flag"
]


# ============================================================
# Calculate Structural Validation Metrics
# ============================================================

# Capture the final dataset dimensions.
calendar_rows, calendar_columns = calendar_final.shape

# Confirm the required schema and column order.
column_order_match = (
    calendar_final.columns.tolist()
    == expected_calendar_columns
)

# Count missing values in required fields.
missing_required_values = (
    calendar_final[required_calendar_columns]
    .isna()
    .sum()
    .sum()
)

# Count duplicate records and identifiers.
duplicate_rows = (
    calendar_final
    .duplicated()
    .sum()
)

duplicate_dates = (
    calendar_final["date"]
    .duplicated()
    .sum()
)

duplicate_calendar_ids = (
    calendar_final["d"]
    .duplicated()
    .sum()
)


# ============================================================
# Calculate Date Validation Metrics
# ============================================================

# Capture and validate the date data type.
date_dtype = calendar_final["date"].dtype

valid_date_dtype = is_datetime64_any_dtype(
    calendar_final["date"]
)

# Confirm chronological row order.
dates_are_chronological = (
    calendar_final["date"]
    .is_monotonic_increasing
)

# Construct the expected uninterrupted daily sequence.
expected_date_range = pd.date_range(
    start=calendar_final["date"].min(),
    end=calendar_final["date"].max(),
    freq="D"
)

# Identify dates missing from the observed Calendar sequence.
missing_calendar_dates = expected_date_range.difference(
    pd.DatetimeIndex(calendar_final["date"])
)


# ============================================================
# Calculate Binary Indicator Validation Metrics
# ============================================================

# Count invalid values separately for every binary field.
invalid_binary_counts = {
    column: int(
        (
            ~calendar_final[column]
            .isin([0, 1])
        ).sum()
    )
    for column in binary_indicator_columns
}

# Calculate the total number of invalid binary values.
invalid_binary_values = sum(
    invalid_binary_counts.values()
)


# ============================================================
# Apply Final Calendar Validation Rules
# ============================================================

# Confirm that all source Calendar records were retained.
assert calendar_rows == len(calendar_df), (
    f"Unexpected Calendar row count: {calendar_rows}. "
    f"Expected: {len(calendar_df)}."
)

# Confirm the required final number of columns.
assert calendar_columns == len(expected_calendar_columns), (
    f"Unexpected Calendar column count: "
    f"{calendar_columns}."
)

# Confirm the final schema and column order.
assert column_order_match, (
    "The final Calendar schema or column order is incorrect."
)

# Confirm completeness of all required fields.
assert missing_required_values == 0, (
    f"Missing values found in required Calendar fields: "
    f"{missing_required_values}."
)

# Confirm record and key uniqueness.
assert duplicate_rows == 0, (
    f"Duplicate Calendar rows detected: {duplicate_rows}."
)

assert duplicate_dates == 0, (
    f"Duplicate Calendar dates detected: {duplicate_dates}."
)

assert duplicate_calendar_ids == 0, (
    f"Duplicate Calendar IDs detected: "
    f"{duplicate_calendar_ids}."
)

# Confirm date type, order, and continuity.
assert valid_date_dtype, (
    f"The date field has an invalid data type: "
    f"{date_dtype}."
)

assert dates_are_chronological, (
    "The Calendar dates are not arranged chronologically."
)

assert len(missing_calendar_dates) == 0, (
    f"Missing Calendar dates detected: "
    f"{len(missing_calendar_dates)}."
)

# Confirm validity of all binary indicators.
assert invalid_binary_values == 0, (
    f"Invalid binary indicator values detected: "
    f"{invalid_binary_counts}."
)


# ============================================================
# Display Final Calendar Validation Summary
# ============================================================

# Display the final structural validation results.
print("✅ Final Calendar dataset validated successfully.")
print(f"Rows                   : {calendar_rows:,}")
print(f"Columns                : {calendar_columns}")
print(
    f"Column structure       : "
    f"{'Passed' if column_order_match else 'Failed'}"
)

# Display completeness and uniqueness results.
print(f"Required missing       : {missing_required_values:,}")
print(f"Duplicate rows         : {duplicate_rows:,}")
print(f"Duplicate dates        : {duplicate_dates:,}")
print(f"Duplicate calendar IDs : {duplicate_calendar_ids:,}")

# Display date-order and continuity results.
print(
    f"Chronological order    : "
    f"{'Passed' if dates_are_chronological else 'Failed'}"
)
print(f"Missing calendar dates : {len(missing_calendar_dates):,}")

# Display business-rule and data-type results.
print(f"Invalid binary values  : {invalid_binary_values:,}")
print(f"Date data type         : {date_dtype}")

# Display detailed binary validation results.
print("\nBinary Indicator Validation:")

for column, invalid_count in invalid_binary_counts.items():
    print(f"{column:<12}: {invalid_count:,}")

✅ Final Calendar dataset validated successfully.
Rows                   : 1,969
Columns                : 22
Column structure       : Passed
Required missing       : 0
Duplicate rows         : 0
Duplicate dates        : 0
Duplicate calendar IDs : 0
Chronological order    : Passed
Missing calendar dates : 0
Invalid binary values  : 0
Date data type         : datetime64[us]

Binary Indicator Validation:
is_weekend  : 0
event_flag  : 0
snap_CA     : 0
snap_TX     : 0
snap_WI     : 0
snap_flag   : 0

#### ✅ Validation Result

The final Calendar dataset passed all required structural, completeness, uniqueness, continuity, data-type, and business-rule validation checks.

Validation confirmed that:

- All source Calendar records were retained in the final dataset.
- The final dataset conforms to the required 22-column schema and column order.
- No missing values were found in the required fields.
- No duplicate rows, dates, or calendar identifiers were detected.
- Calendar dates are arranged chronologically with uninterrupted daily coverage.
- All weekend, event, and SNAP indicators contain valid binary values.
- The `date` field retains the required datetime data type.

The validated Calendar dataset is ready for export as **`calendar_final.csv`**.

#### 📤 11.2.8 Export `calendar_final.csv`

The Calendar dataset validated in Section 11.2.7 is exported to the project’s processed data directory for use in downstream analytical and forecasting workflows.

This step will:

- confirm that the completed final validation checks remain satisfied;
- create the processed data directory when required;
- export the validated dataset as `calendar_final.csv`;
- reload the exported file and verify its structure and content integrity;
- establish the exported file as the official Calendar dimension for Project FORESIGHT.

The verified export will support downstream feature engineering, demand forecasting, dashboard development, and SKU-level analytical workflows.

In [70]:
# ============================================================
# Confirm Calendar Dataset Pre-Export Readiness
# ============================================================

# Reuse the final validation results calculated in Section 11.2.7.
pre_export_checks = {
    "Column structure": column_order_match,
    "Required-field completeness": missing_required_values == 0,
    "Duplicate records": duplicate_rows == 0,
    "Date uniqueness": duplicate_dates == 0,
    "Calendar ID uniqueness": duplicate_calendar_ids == 0,
    "Chronological order": dates_are_chronological,
    "Daily date continuity": len(missing_calendar_dates) == 0,
    "Binary indicator validity": invalid_binary_values == 0,
    "Date data type": valid_date_dtype
}

# Identify any validation checks that did not pass.
failed_pre_export_checks = [
    check_name
    for check_name, check_passed in pre_export_checks.items()
    if not check_passed
]

# Prevent export when any final validation requirement has failed.
assert failed_pre_export_checks == [], (
    "Calendar export blocked because the following checks failed: "
    f"{failed_pre_export_checks}."
)

print("✅ Calendar dataset is ready for export.")
print(f"Pre-export checks passed: {len(pre_export_checks)}")

✅ Calendar dataset is ready for export.
Pre-export checks passed: 9

In [71]:
# ============================================================
# Export Final Calendar Dataset
# ============================================================

# Create the processed data directory if it does not exist.
PROCESSED_DATA_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# Define the final Calendar export path.
calendar_output_path = (
    PROCESSED_DATA_DIR /
    "calendar_final.csv"
)

# Export the validated Calendar dataset without the DataFrame index.
calendar_final.to_csv(
    calendar_output_path,
    index=False
)

print("Calendar dataset export completed.")
print(f"Export path: {calendar_output_path}")

Calendar dataset export completed.
Export path: C:\Users\hp\Project FORESIGHT\data\processed\calendar_final.csv

In [72]:
# ============================================================
# Verify Exported Calendar Dataset
# ============================================================

# Confirm that the export file was created successfully.
export_file_exists = calendar_output_path.exists()

assert export_file_exists, (
    f"Calendar export file was not created: "
    f"{calendar_output_path}."
)

# Confirm that the exported file is not empty.
export_file_size_bytes = calendar_output_path.stat().st_size

assert export_file_size_bytes > 0, (
    "The exported Calendar file is empty."
)

# Reload the exported dataset to verify the saved output.
calendar_export_check = pd.read_csv(
    calendar_output_path,
    parse_dates=["date"]
)

# Confirm that the exported dimensions match the in-memory dataset.
export_shape_match = (
    calendar_export_check.shape
    == calendar_final.shape
)

# Confirm that the exported column names and order were preserved.
export_column_order_match = (
    calendar_export_check.columns.tolist()
    == calendar_final.columns.tolist()
)

# Normalize both datasets for a reliable value-by-value comparison.
# Missing event values are represented using a common placeholder.
source_calendar_comparison = (
    calendar_final
    .astype("string")
    .fillna("<MISSING>")
    .reset_index(drop=True)
)

exported_calendar_comparison = (
    calendar_export_check
    .astype("string")
    .fillna("<MISSING>")
    .reset_index(drop=True)
)

# Confirm that all exported values match the source dataset.
export_content_match = (
    source_calendar_comparison
    .equals(exported_calendar_comparison)
)

# Apply export-integrity assertions.
assert export_shape_match, (
    "The exported dataset dimensions do not match "
    "the source Calendar dataset."
)

assert export_column_order_match, (
    "The exported Calendar schema or column order was altered."
)

assert export_content_match, (
    "The exported Calendar values do not match "
    "the source dataset."
)

print("✅ Exported Calendar dataset verified successfully.")

✅ Exported Calendar dataset verified successfully.

In [73]:
# ============================================================
# Display Calendar Export Summary
# ============================================================

# Display the final export and integrity-verification results.
print("✅ Final Calendar dataset exported and verified successfully.")
print(f"Dataset shape          : {calendar_export_check.shape}")
print(
    f"Schema preserved       : "
    f"{'Passed' if export_column_order_match else 'Failed'}"
)
print(
    f"Content integrity      : "
    f"{'Passed' if export_content_match else 'Failed'}"
)
print(f"Export file size       : {export_file_size_bytes / 1024:,.2f} KB")
print(f"Dataset exported to    : {calendar_output_path}")

✅ Final Calendar dataset exported and verified successfully.
Dataset shape          : (1969, 22)
Schema preserved       : Passed
Content integrity      : Passed
Export file size       : 156.11 KB
Dataset exported to    : C:\Users\hp\Project FORESIGHT\data\processed\calendar_final.csv

#### ✅ Validation Result

The validated Calendar dataset was exported and verified successfully as **`calendar_final.csv`**.

Validation confirmed that:

- All final pre-export validation requirements remained satisfied.
- The export file was created successfully in the processed data directory.
- The exported dataset preserves the required 1,969-row and 22-column structure.
- The complete schema and column order were retained.
- No unintended index column was introduced during export.
- The reloaded export contains the same values as the validated in-memory dataset.
- The exported file is complete, readable, and ready for downstream use.

The verified **`calendar_final.csv`** file now serves as the official Calendar dimension for subsequent Project FORESIGHT workflows.

### 🧩 11.3 SKU Master Dataset Engineering

The SKU Master dataset will be created by integrating product hierarchy, store identifiers, historical selling prices, and sales activity into a single SKU-store reference table.

In Project FORESIGHT, each `sku_id` represents one unique item-store combination, consistent with the standardized identifier structure established in the Sales Daily pipeline.

The engineering process includes:

- creating protected working copies of the required upstream datasets;
- constructing the standardized SKU-store reference foundation;
- deriving product lifecycle and pricing attributes;
- estimating cost and margin metrics unavailable in the source data;
- classifying SKU status using defined business rules;
- validating and exporting the final SKU Master dataset.

The completed dataset will serve as the primary SKU-store dimension for demand forecasting, inventory planning, dashboard reporting, and downstream analytical workflows in Project FORESIGHT.

#### 📄 11.3.1 Create Working Copies

The SKU Master pipeline uses three upstream datasets:

- the raw Sales dataset containing product, store, and historical sales information;
- the validated Calendar dataset containing date and retail-week references;
- the raw Prices dataset containing weekly item-store selling prices.

Separate working copies are created to protect these upstream DataFrames during SKU-level engineering.

This step will:

- create independent working copies of the three required datasets;
- preserve their existing dimensions and source structures;
- verify that each working DataFrame is separate from its upstream DataFrame;
- prepare the working datasets for source inspection and SKU Master construction.

The validated working copies will support all subsequent SKU Master engineering steps.

In [74]:
# ============================================================
# Create Working Copies for SKU Master Engineering
# ============================================================

# Create independent working copies of the required upstream datasets.
sku_sales = sales_df.copy()
sku_calendar = calendar_final.copy()
sku_prices = prices_df.copy()

print("SKU Master working copies created successfully.")

SKU Master working copies created successfully.

In [75]:
# ============================================================
# Validate Working-Copy Independence and Dimensions
# ============================================================

# Confirm that each working DataFrame is independent
# of its corresponding upstream DataFrame.
copy_independence = {
    "Sales": sku_sales is not sales_df,
    "Calendar": sku_calendar is not calendar_final,
    "Prices": sku_prices is not prices_df
}

# Confirm that each working copy preserves
# the dimensions of its upstream dataset.
shape_preservation = {
    "Sales": sku_sales.shape == sales_df.shape,
    "Calendar": sku_calendar.shape == calendar_final.shape,
    "Prices": sku_prices.shape == prices_df.shape
}

# Verify that all working copies are independent.
assert all(copy_independence.values()), (
    "One or more working copies are not independent "
    "of their upstream DataFrames."
)

# Verify that all source dimensions were preserved.
assert all(shape_preservation.values()), (
    "One or more working copies do not preserve "
    "their upstream dataset dimensions."
)

print("✅ SKU Master working copies validated successfully.")

✅ SKU Master working copies validated successfully.

In [76]:
# ============================================================
# Display SKU Master Working-Copy Summary
# ============================================================

# Display the dimensions of the working datasets.
print("Working Dataset Dimensions")
print("-" * 45)
print(f"Sales dataset shape       : {sku_sales.shape}")
print(f"Calendar dataset shape    : {sku_calendar.shape}")
print(f"Prices dataset shape      : {sku_prices.shape}")

# Display the key business entities available
# in the Sales working dataset.
print("\nKey Sales Entities")
print("-" * 45)
print(f"Unique raw sales series   : {sku_sales['id'].nunique():,}")
print(f"Unique items              : {sku_sales['item_id'].nunique():,}")
print(f"Unique stores             : {sku_sales['store_id'].nunique():,}")

# Display working-copy independence results.
print("\nWorking-Copy Independence")
print("-" * 45)

for dataset_name, is_independent in copy_independence.items():
    print(f"{dataset_name:<10}: {is_independent}")

Working Dataset Dimensions
---------------------------------------------
Sales dataset shape       : (30490, 1919)
Calendar dataset shape    : (1969, 22)
Prices dataset shape      : (6841121, 4)

Key Sales Entities
---------------------------------------------
Unique raw sales series   : 30,490
Unique items              : 3,049
Unique stores             : 10

Working-Copy Independence
---------------------------------------------
Sales     : True
Calendar  : True
Prices    : True

#### ✅ Validation Result

Three independent working datasets were created successfully for SKU Master engineering.

Validation confirmed that:

- Separate working copies were created for the Sales, Calendar, and Prices datasets.
- Each working DataFrame is independent of its corresponding upstream DataFrame.
- All source rows and columns were preserved during the copy operation.
- The Sales working dataset contains 30,490 raw item-store sales series, 3,049 unique items, and 10 stores.
- The upstream datasets remain protected from subsequent SKU Master transformations.

The validated working copies are now ready for source-structure inspection.

#### 🔍 11.3.2 Inspect Source Structures

The Sales, Calendar, and Prices working datasets are inspected to confirm that the fields required for SKU Master engineering are available, complete, and structurally suitable for downstream transformations.

This step will:

- review the dimensions and required fields of each source dataset;
- verify that all required source columns are present;
- inspect representative records from the key business fields;
- confirm completeness of the required fields;
- validate the uniqueness of the source identifiers and merge keys.

The validated source structures will provide a reliable foundation for constructing the SKU Master dataset.

In [77]:
# ============================================================
# Define Required SKU Master Source Fields
# ============================================================

# Define the Sales fields required for constructing
# the SKU Master reference foundation.
sales_required_columns = [
    "id",
    "item_id",
    "dept_id",
    "cat_id",
    "store_id",
    "state_id"
]

# Define the Calendar fields required for mapping
# historical sales days and retail weeks.
calendar_required_columns = [
    "date",
    "d",
    "wm_yr_wk"
]

# Define the Prices fields required for lifecycle
# and pricing feature engineering.
prices_required_columns = [
    "store_id",
    "item_id",
    "wm_yr_wk",
    "sell_price"
]

# Organize the working datasets and their required fields.
source_datasets = {
    "Sales": sku_sales,
    "Calendar": sku_calendar,
    "Prices": sku_prices
}

source_required_columns = {
    "Sales": sales_required_columns,
    "Calendar": calendar_required_columns,
    "Prices": prices_required_columns
}

# Identify required fields that are missing from each dataset.
missing_source_columns = {
    dataset_name: [
        column
        for column in source_required_columns[dataset_name]
        if column not in source_datasets[dataset_name].columns
    ]
    for dataset_name in source_datasets
}

# Prevent the pipeline from continuing when required
# source fields are unavailable.
assert all(
    len(columns) == 0
    for columns in missing_source_columns.values()
), (
    "Required SKU Master source fields are missing: "
    f"{missing_source_columns}."
)

print("✅ All required SKU Master source fields are present.")

✅ All required SKU Master source fields are present.

In [78]:
# ============================================================
# Inspect SKU Master Source Structures
# ============================================================

# Display the dimensions of the three working datasets.
print("Source Dataset Dimensions")
print("-" * 50)
print(f"Sales dataset shape       : {sku_sales.shape}")
print(f"Calendar dataset shape    : {sku_calendar.shape}")
print(f"Prices dataset shape      : {sku_prices.shape}")

# Preview the required Sales reference fields.
print("\nSales Reference Fields")
display(
    sku_sales[
        sales_required_columns
    ].head()
)

# Preview the required Calendar reference fields.
print("Calendar Reference Fields")
display(
    sku_calendar[
        calendar_required_columns
    ].head()
)

# Preview the required Prices reference fields.
print("Prices Reference Fields")
display(
    sku_prices[
        prices_required_columns
    ].head()
)

Source Dataset Dimensions
--------------------------------------------------
Sales dataset shape       : (30490, 1919)
Calendar dataset shape    : (1969, 22)
Prices dataset shape      : (6841121, 4)

Sales Reference Fields

                              id        item_id    dept_id   cat_id store_id state_id
0  HOBBIES_1_001_CA_1_validation  HOBBIES_1_001  HOBBIES_1  HOBBIES     CA_1       CA
1  HOBBIES_1_002_CA_1_validation  HOBBIES_1_002  HOBBIES_1  HOBBIES     CA_1       CA
2  HOBBIES_1_003_CA_1_validation  HOBBIES_1_003  HOBBIES_1  HOBBIES     CA_1       CA
3  HOBBIES_1_004_CA_1_validation  HOBBIES_1_004  HOBBIES_1  HOBBIES     CA_1       CA
4  HOBBIES_1_005_CA_1_validation  HOBBIES_1_005  HOBBIES_1  HOBBIES     CA_1       CA

Calendar Reference Fields

        date    d  wm_yr_wk
0 2011-01-29  d_1     11101
1 2011-01-30  d_2     11101
2 2011-01-31  d_3     11101
3 2011-02-01  d_4     11101
4 2011-02-02  d_5     11101

Prices Reference Fields

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

In [79]:
# ============================================================
# Validate Source Completeness and Key Integrity
# ============================================================

# Count missing values in the required Sales fields.
sales_source_missing = (
    sku_sales[sales_required_columns]
    .isna()
    .sum()
)

# Count missing values in the required Calendar fields.
calendar_source_missing = (
    sku_calendar[calendar_required_columns]
    .isna()
    .sum()
)

# Count missing values in the required Prices fields.
prices_source_missing = (
    sku_prices[prices_required_columns]
    .isna()
    .sum()
)

# Confirm that each raw Sales series identifier is unique.
duplicate_sales_series_ids = (
    sku_sales["id"]
    .duplicated()
    .sum()
)

# Confirm that every Calendar date appears only once.
duplicate_calendar_dates = (
    sku_calendar["date"]
    .duplicated()
    .sum()
)

# Confirm that every historical day identifier appears only once.
duplicate_calendar_day_ids = (
    sku_calendar["d"]
    .duplicated()
    .sum()
)

# Confirm that each item-store-week price record is unique.
duplicate_price_keys = (
    sku_prices[
        [
            "store_id",
            "item_id",
            "wm_yr_wk"
        ]
    ]
    .duplicated()
    .sum()
)

# Ensure all required Sales fields are complete.
assert sales_source_missing.sum() == 0, (
    "Missing values were found in the required Sales fields."
)

# Ensure all required Calendar fields are complete.
assert calendar_source_missing.sum() == 0, (
    "Missing values were found in the required Calendar fields."
)

# Ensure all required Prices fields are complete.
assert prices_source_missing.sum() == 0, (
    "Missing values were found in the required Prices fields."
)

# Ensure the raw Sales-series identifier is unique.
assert duplicate_sales_series_ids == 0, (
    f"Duplicate Sales-series identifiers detected: "
    f"{duplicate_sales_series_ids}."
)

# Ensure Calendar dates and day identifiers are unique.
assert duplicate_calendar_dates == 0, (
    f"Duplicate Calendar dates detected: "
    f"{duplicate_calendar_dates}."
)

assert duplicate_calendar_day_ids == 0, (
    f"Duplicate Calendar day identifiers detected: "
    f"{duplicate_calendar_day_ids}."
)

# Ensure the Prices merge key is unique.
assert duplicate_price_keys == 0, (
    f"Duplicate item-store-week price records detected: "
    f"{duplicate_price_keys}."
)

# Display the source-readiness summary.
print("✅ SKU Master source structures validated successfully.")
print(f"Missing Sales values       : {sales_source_missing.sum():,}")
print(f"Missing Calendar values    : {calendar_source_missing.sum():,}")
print(f"Missing Prices values      : {prices_source_missing.sum():,}")
print(f"Duplicate Sales IDs        : {duplicate_sales_series_ids:,}")
print(f"Duplicate Calendar dates   : {duplicate_calendar_dates:,}")
print(f"Duplicate Calendar day IDs : {duplicate_calendar_day_ids:,}")
print(f"Duplicate price keys       : {duplicate_price_keys:,}")

✅ SKU Master source structures validated successfully.
Missing Sales values       : 0
Missing Calendar values    : 0
Missing Prices values      : 0
Duplicate Sales IDs        : 0
Duplicate Calendar dates   : 0
Duplicate Calendar day IDs : 0
Duplicate price keys       : 0

#### ✅ Validation Result

The Sales, Calendar, and Prices working datasets passed all source-readiness checks successfully.

Validation confirmed that:

- All fields required for SKU Master engineering are present.
- No missing values were detected in the required source fields.
- Every raw Sales-series identifier is unique.
- Calendar dates and historical day identifiers are unique.
- Each item-store-week combination contains no duplicate pricing record.
- The source structures support the required SKU-level joins and feature-engineering operations.

The validated source datasets are now ready for construction of the SKU Master foundation.

#### 🧱 11.3.3 Build SKU Master Foundation

The SKU Master foundation is created by extracting the core product, store, and hierarchy fields from the Sales working dataset. The resulting table will contain one record for every unique item-store combination.

The standardized `sku_id` will follow the canonical Project FORESIGHT identifier established in the Sales Daily pipeline:

`item_id + "_" + store_id`

This step will:

- extract the required product, department, store, and state reference fields;
- create the standardized `sku_id` for every item-store combination;
- standardize source column names using the project naming convention;
- arrange the foundation fields in a logical business order;
- validate identifier uniqueness, hierarchy consistency, and record completeness.

The validated foundation will support the addition of lifecycle, pricing, cost, margin, and product-status attributes.

In [80]:
# ============================================================
# Build SKU Master Foundation
# ============================================================

# Select the source fields required for the SKU Master foundation.
sku_master_source = sku_sales[
    [
        "id",
        "item_id",
        "dept_id",
        "cat_id",
        "store_id",
        "state_id"
    ]
].copy()

# Create the canonical Project FORESIGHT SKU identifier
# using the item-store combination.
sku_master_source["sku_id"] = (
    sku_master_source["item_id"].astype("string")
    + "_"
    + sku_master_source["store_id"].astype("string")
)

# Standardize the product hierarchy column names.
sku_master = sku_master_source.rename(
    columns={
        "dept_id": "department",
        "cat_id": "category"
    }
)

# Define the required foundation structure.
sku_master_foundation_columns = [
    "sku_id",
    "item_id",
    "category",
    "department",
    "store_id",
    "state_id"
]

# Select and arrange the foundation fields
# in the required business order.
sku_master = (
    sku_master[sku_master_foundation_columns]
    .copy()
)

print("✅ SKU Master foundation created successfully.")
print(f"Dataset shape: {sku_master.shape}")

✅ SKU Master foundation created successfully.
Dataset shape: (30490, 6)

In [81]:
# ============================================================
# Preview SKU Master Foundation
# ============================================================

# Display representative SKU-store reference records.
display(
    sku_master.head(10)
)

               sku_id        item_id category department store_id state_id
0  HOBBIES_1_001_CA_1  HOBBIES_1_001  HOBBIES  HOBBIES_1     CA_1       CA
1  HOBBIES_1_002_CA_1  HOBBIES_1_002  HOBBIES  HOBBIES_1     CA_1       CA
2  HOBBIES_1_003_CA_1  HOBBIES_1_003  HOBBIES  HOBBIES_1     CA_1       CA
3  HOBBIES_1_004_CA_1  HOBBIES_1_004  HOBBIES  HOBBIES_1     CA_1       CA
4  HOBBIES_1_005_CA_1  HOBBIES_1_005  HOBBIES  HOBBIES_1     CA_1       CA
5  HOBBIES_1_006_CA_1  HOBBIES_1_006  HOBBIES  HOBBIES_1     CA_1       CA
6  HOBBIES_1_007_CA_1  HOBBIES_1_007  HOBBIES  HOBBIES_1     CA_1       CA
7  HOBBIES_1_008_CA_1  HOBBIES_1_008  HOBBIES  HOBBIES_1     CA_1       CA
8  HOBBIES_1_009_CA_1  HOBBIES_1_009  HOBBIES  HOBBIES_1     CA_1       CA
9  HOBBIES_1_010_CA_1  HOBBIES_1_010  HOBBIES  HOBBIES_1     CA_1       CA

In [82]:
# ============================================================
# Validate SKU Master Foundation
# ============================================================

# Define the expected foundation schema and column order.
expected_sku_master_columns = [
    "sku_id",
    "item_id",
    "category",
    "department",
    "store_id",
    "state_id"
]

# Calculate the expected number of unique item-store combinations.
expected_sku_count = (
    sku_master_source[
        ["item_id", "store_id"]
    ]
    .drop_duplicates()
    .shape[0]
)

# Calculate the actual number of standardized SKU identifiers.
actual_sku_count = (
    sku_master["sku_id"]
    .nunique()
)

# Count missing values in the foundation fields.
missing_foundation_values = (
    sku_master
    .isna()
    .sum()
    .sum()
)

# Count completely duplicated foundation records.
duplicate_foundation_rows = (
    sku_master
    .duplicated()
    .sum()
)

# Count duplicate canonical SKU identifiers.
duplicate_sku_ids = (
    sku_master["sku_id"]
    .duplicated()
    .sum()
)

# Count duplicate item-store combinations.
duplicate_item_store_pairs = (
    sku_master[
        ["item_id", "store_id"]
    ]
    .duplicated()
    .sum()
)

# Recalculate the expected canonical identifiers
# for identifier-format validation.
expected_canonical_sku_ids = (
    sku_master["item_id"].astype("string")
    + "_"
    + sku_master["store_id"].astype("string")
)

# Count identifiers that do not follow the canonical format.
invalid_canonical_sku_ids = (
    sku_master["sku_id"]
    != expected_canonical_sku_ids
).sum()

# Confirm that every item maps consistently
# to one category and one department.
item_hierarchy_counts = (
    sku_master
    .groupby("item_id")[
        ["category", "department"]
    ]
    .nunique()
)

invalid_item_hierarchy_mappings = (
    item_hierarchy_counts
    .gt(1)
    .any(axis=1)
    .sum()
)

# Confirm that every store maps consistently to one state.
invalid_store_state_mappings = (
    sku_master
    .groupby("store_id")["state_id"]
    .nunique()
    .gt(1)
    .sum()
)

# Confirm that no source records were lost
# while preparing the foundation.
source_records_preserved = (
    len(sku_master)
    == len(sku_master_source)
)

# Validate the final foundation structure.
assert sku_master.columns.tolist() == expected_sku_master_columns, (
    "The SKU Master foundation schema or column order is incorrect."
)

# Validate source-record retention.
assert source_records_preserved, (
    "One or more source SKU records were lost "
    "while preparing the foundation."
)

# Validate the expected item-store population.
assert len(sku_master) == expected_sku_count, (
    f"Unexpected SKU Master record count: {len(sku_master)}. "
    f"Expected: {expected_sku_count}."
)

assert actual_sku_count == expected_sku_count, (
    f"Unexpected number of unique SKU identifiers: "
    f"{actual_sku_count}."
)

# Validate completeness and uniqueness.
assert missing_foundation_values == 0, (
    f"Missing foundation values detected: "
    f"{missing_foundation_values}."
)

assert duplicate_foundation_rows == 0, (
    f"Duplicate foundation rows detected: "
    f"{duplicate_foundation_rows}."
)

assert duplicate_sku_ids == 0, (
    f"Duplicate SKU identifiers detected: "
    f"{duplicate_sku_ids}."
)

assert duplicate_item_store_pairs == 0, (
    f"Duplicate item-store combinations detected: "
    f"{duplicate_item_store_pairs}."
)

# Validate the canonical SKU identifier convention.
assert invalid_canonical_sku_ids == 0, (
    f"Non-canonical SKU identifiers detected: "
    f"{invalid_canonical_sku_ids}."
)

# Validate hierarchy and geographic mappings.
assert invalid_item_hierarchy_mappings == 0, (
    f"Inconsistent item hierarchy mappings detected: "
    f"{invalid_item_hierarchy_mappings}."
)

assert invalid_store_state_mappings == 0, (
    f"Inconsistent store-state mappings detected: "
    f"{invalid_store_state_mappings}."
)

# Display the validation summary.
print("✅ SKU Master foundation validated successfully.")
print(f"Dataset shape              : {sku_master.shape}")
print(f"Unique canonical SKU IDs   : {actual_sku_count:,}")
print(f"Missing values             : {missing_foundation_values:,}")
print(f"Duplicate rows             : {duplicate_foundation_rows:,}")
print(f"Duplicate SKU IDs          : {duplicate_sku_ids:,}")
print(f"Duplicate item-store pairs : {duplicate_item_store_pairs:,}")
print(f"Invalid canonical IDs      : {invalid_canonical_sku_ids:,}")
print(f"Hierarchy mapping errors   : {invalid_item_hierarchy_mappings:,}")
print(f"Store-state mapping errors : {invalid_store_state_mappings:,}")

✅ SKU Master foundation validated successfully.
Dataset shape              : (30490, 6)
Unique canonical SKU IDs   : 30,490
Missing values             : 0
Duplicate rows             : 0
Duplicate SKU IDs          : 0
Duplicate item-store pairs : 0
Invalid canonical IDs      : 0
Hierarchy mapping errors   : 0
Store-state mapping errors : 0

#### ✅ Validation Result

The SKU Master foundation was created and validated successfully.

Validation confirmed that:

- One foundation record was created for every unique item-store combination.
- All `sku_id` values follow the canonical Project FORESIGHT identifier convention.
- The standardized identifiers are complete and unique.
- No source records were lost during foundation construction.
- No missing values, duplicate records, or duplicate item-store combinations were detected.
- Each item maps consistently to one category and department.
- Each store maps consistently to one state.
- No unsupported or duplicated hierarchy field was introduced.

The validated SKU Master foundation is now ready for lifecycle, pricing, cost, margin, and product-status feature engineering.

#### 📅 11.3.4 Engineer SKU Lifecycle Fields

SKU lifecycle attributes are derived from historical price availability and positive sales activity. These fields describe when each item-store combination became commercially observable, when it first and last recorded sales, and how long it existed within the observed sales period.

Because the source data does not contain an explicit product-launch date, `launch_date` is treated as an operational proxy defined as the first calendar date of the earliest retail week containing a positive selling price.

This step will:

- prepare a complete mapping between historical sales-day columns and calendar dates;
- estimate the launch date for each SKU from its earliest positive-price week;
- identify the first and last dates on which each SKU recorded positive sales;
- calculate SKU age at the end of the observed sales period;
- validate lifecycle completeness, chronological order, identifier integrity, and record preservation.

The validated lifecycle attributes will support SKU-status classification, inventory planning, and downstream business analysis.

In [83]:
# ============================================================
# Prepare SKU Lifecycle References
# ============================================================

# Remove previously engineered lifecycle fields when the
# subsection is rerun during notebook development.
existing_lifecycle_columns = [
    "launch_date",
    "first_sale_date",
    "last_sale_date",
    "product_age_days",
    "sku_age_days"
]

sku_master = sku_master.drop(
    columns=[
        column
        for column in existing_lifecycle_columns
        if column in sku_master.columns
    ],
    errors="ignore"
)

# Preserve the foundation row count for merge validation.
lifecycle_input_rows = len(sku_master)

# Identify and chronologically order the historical sales-day columns.
day_columns = sorted(
    [
        column
        for column in sku_sales.columns
        if column.startswith("d_")
    ],
    key=lambda column: int(
        column.split("_")[1]
    )
)

# Confirm that historical sales-day columns were identified.
assert len(day_columns) > 0, (
    "No historical sales-day columns were found."
)

# Extract the numeric day identifiers.
day_numbers = [
    int(column.split("_")[1])
    for column in day_columns
]

# Define the expected uninterrupted historical day sequence.
expected_day_numbers = list(
    range(1, max(day_numbers) + 1)
)

# Confirm that no historical sales-day columns are missing.
assert day_numbers == expected_day_numbers, (
    "The historical sales-day sequence is incomplete."
)

# Create an ordered mapping between sales-day columns and dates.
sales_date_lookup = (
    sku_calendar
    .set_index("d")["date"]
    .reindex(day_columns)
)

# Count sales-day identifiers without a matching Calendar date.
missing_sales_date_mappings = (
    sales_date_lookup
    .isna()
    .sum()
)

# Confirm that the mapped dates follow chronological order.
sales_dates_are_chronological = (
    sales_date_lookup
    .is_monotonic_increasing
)

# Validate the historical day-to-date mapping.
assert missing_sales_date_mappings == 0, (
    f"Missing sales-day date mappings detected: "
    f"{missing_sales_date_mappings}."
)

assert sales_dates_are_chronological, (
    "The mapped historical sales dates are not chronological."
)

# Define the observed historical sales period.
observation_start_date = sales_date_lookup.min()
observation_end_date = sales_date_lookup.max()

print("✅ SKU lifecycle references prepared successfully.")
print(f"Daily sales columns        : {len(day_columns):,}")
print(f"Missing date mappings      : {missing_sales_date_mappings:,}")
print(f"First observed sales date  : {observation_start_date.date()}")
print(f"Last observed sales date   : {observation_end_date.date()}")

✅ SKU lifecycle references prepared successfully.
Daily sales columns        : 1,913
Missing date mappings      : 0
First observed sales date  : 2011-01-29
Last observed sales date   : 2016-04-24

In [84]:
# ============================================================
# Engineer SKU Launch Date
# ============================================================

# Identify the earliest retail week containing
# a positive selling price for each item-store combination.
sku_launch_weeks = (
    sku_prices.loc[
        sku_prices["sell_price"] > 0,
        [
            "store_id",
            "item_id",
            "wm_yr_wk"
        ]
    ]
    .groupby(
        ["store_id", "item_id"],
        as_index=False
    )["wm_yr_wk"]
    .min()
    .rename(
        columns={
            "wm_yr_wk": "launch_week"
        }
    )
)

# Determine the first available Calendar date
# associated with every retail week.
week_start_dates = (
    sku_calendar
    .groupby(
        "wm_yr_wk",
        as_index=False
    )["date"]
    .min()
    .rename(
        columns={
            "wm_yr_wk": "launch_week",
            "date": "launch_date"
        }
    )
)

# Convert each earliest priced week into
# an estimated SKU launch date.
sku_launch_dates = sku_launch_weeks.merge(
    week_start_dates,
    on="launch_week",
    how="left",
    validate="many_to_one"
)

# Count launch weeks without a Calendar-date mapping.
missing_launch_date_mappings = (
    sku_launch_dates["launch_date"]
    .isna()
    .sum()
)

# Confirm that each item-store combination
# has only one launch-date record.
duplicate_launch_keys = (
    sku_launch_dates[
        ["store_id", "item_id"]
    ]
    .duplicated()
    .sum()
)

assert missing_launch_date_mappings == 0, (
    f"Missing launch-date mappings detected: "
    f"{missing_launch_date_mappings}."
)

assert duplicate_launch_keys == 0, (
    f"Duplicate SKU launch records detected: "
    f"{duplicate_launch_keys}."
)

# Attach the estimated launch date
# to the SKU Master foundation.
sku_master = sku_master.merge(
    sku_launch_dates[
        [
            "store_id",
            "item_id",
            "launch_date"
        ]
    ],
    on=["store_id", "item_id"],
    how="left",
    validate="one_to_one"
)

# Confirm that the merge preserved all foundation records.
assert len(sku_master) == lifecycle_input_rows, (
    "The launch-date merge changed the SKU Master row count."
)

# Confirm that every SKU received a launch date.
missing_launch_dates = (
    sku_master["launch_date"]
    .isna()
    .sum()
)

assert missing_launch_dates == 0, (
    f"SKUs without launch dates detected: "
    f"{missing_launch_dates}."
)

print("✅ SKU launch dates engineered successfully.")
print(f"Earliest launch date       : {sku_master['launch_date'].min().date()}")
print(f"Latest launch date         : {sku_master['launch_date'].max().date()}")
print(f"Missing launch dates       : {missing_launch_dates:,}")

✅ SKU launch dates engineered successfully.
Earliest launch date       : 2011-01-29
Latest launch date         : 2016-02-13
Missing launch dates       : 0

In [85]:
# ============================================================
# Engineer First and Last Sale Dates
# ============================================================

# Convert the ordered calendar dates into a NumPy date array.
sales_dates = sales_date_lookup.to_numpy(
    dtype="datetime64[ns]"
)

# Create canonical SKU identifiers using
# each item-store combination.
sales_lifecycle_sku_ids = (
    sku_sales["item_id"].astype("string")
    + "_"
    + sku_sales["store_id"].astype("string")
)

# Confirm that every Sales record represents one unique SKU.
assert sales_lifecycle_sku_ids.is_unique, (
    "Duplicate canonical SKU identifiers were found "
    "in the Sales working dataset."
)

# Define the number of SKU sales-series records.
record_count = len(sku_sales)

# Create empty arrays for first and last sale dates.
first_sale_dates = np.full(
    record_count,
    np.datetime64("NaT"),
    dtype="datetime64[ns]"
)

last_sale_dates = np.full(
    record_count,
    np.datetime64("NaT"),
    dtype="datetime64[ns]"
)

# Process the wide sales dataset in manageable chunks.
chunk_size = 5_000

for start_index in range(
    0,
    record_count,
    chunk_size
):
    end_index = min(
        start_index + chunk_size,
        record_count
    )

    # Extract historical daily sales for the current chunk.
    sales_chunk = sku_sales.iloc[
        start_index:end_index
    ][day_columns].to_numpy()

    # Identify dates containing positive sales.
    positive_sales = sales_chunk > 0

    # Identify SKUs containing at least one positive sale.
    has_sales = positive_sales.any(axis=1)

    # Locate the first positive-sale position.
    first_positions = positive_sales.argmax(axis=1)

    # Locate the last positive-sale position.
    last_positions = (
        positive_sales.shape[1]
        - 1
        - positive_sales[:, ::-1].argmax(axis=1)
    )

    # Create the corresponding dataset row positions.
    chunk_rows = np.arange(
        start_index,
        end_index
    )

    valid_rows = chunk_rows[has_sales]

    # Assign the first positive-sale dates.
    first_sale_dates[valid_rows] = sales_dates[
        first_positions[has_sales]
    ]

    # Assign the last positive-sale dates.
    last_sale_dates[valid_rows] = sales_dates[
        last_positions[has_sales]
    ]

# Create the lifecycle-date table using
# the canonical Project FORESIGHT SKU identifier.
sku_sale_dates = pd.DataFrame(
    {
        "sku_id": sales_lifecycle_sku_ids.to_numpy(),
        "first_sale_date": pd.to_datetime(
            first_sale_dates
        ),
        "last_sale_date": pd.to_datetime(
            last_sale_dates
        )
    }
)

# Confirm that the lifecycle table contains
# one record for every canonical SKU.
assert sku_sale_dates["sku_id"].is_unique, (
    "Duplicate SKU identifiers were found "
    "in the lifecycle-date table."
)

# Remove lifecycle columns created during
# an earlier notebook execution.
sku_master = sku_master.drop(
    columns=[
        "first_sale_date",
        "last_sale_date"
    ],
    errors="ignore"
)

# Preserve the current row count before merging.
lifecycle_rows_before_merge = len(sku_master)

# Attach first and last sale dates
# using the canonical SKU identifier.
sku_master = sku_master.merge(
    sku_sale_dates,
    on="sku_id",
    how="left",
    validate="one_to_one"
)

# Confirm that the merge preserved every SKU record.
assert len(sku_master) == lifecycle_rows_before_merge, (
    "The lifecycle-date merge changed "
    "the SKU Master row count."
)

# Count missing lifecycle dates after the merge.
missing_first_sale_dates = (
    sku_master["first_sale_date"]
    .isna()
    .sum()
)

missing_last_sale_dates = (
    sku_master["last_sale_date"]
    .isna()
    .sum()
)

# Confirm that every SKU received lifecycle dates.
assert missing_first_sale_dates == 0, (
    f"Missing first-sale dates detected: "
    f"{missing_first_sale_dates}."
)

assert missing_last_sale_dates == 0, (
    f"Missing last-sale dates detected: "
    f"{missing_last_sale_dates}."
)

print("✅ First and last sale dates engineered successfully.")
print(f"Lifecycle records created : {len(sku_sale_dates):,}")
print(f"Missing first-sale dates  : {missing_first_sale_dates:,}")
print(f"Missing last-sale dates   : {missing_last_sale_dates:,}")
print(f"Rows preserved            : {len(sku_master):,}")

✅ First and last sale dates engineered successfully.
Lifecycle records created : 30,490
Missing first-sale dates  : 0
Missing last-sale dates   : 0
Rows preserved            : 30,490

In [86]:
# ============================================================
# Calculate SKU Age
# ============================================================

# Calculate the observed age of every SKU at the end
# of the historical sales period.
sku_master["sku_age_days"] = (
    observation_end_date
    - sku_master["launch_date"]
).dt.days.astype("Int32")

print("✅ SKU age calculated successfully.")
print(
    "Minimum SKU age           : "
    f"{sku_master['sku_age_days'].min():,} days"
)
print(
    "Maximum SKU age           : "
    f"{sku_master['sku_age_days'].max():,} days"
)

✅ SKU age calculated successfully.
Minimum SKU age           : 71 days
Maximum SKU age           : 1,912 days

In [87]:
# ============================================================
# Preview SKU Lifecycle Fields
# ============================================================

# Display representative engineered lifecycle records.
display(
    sku_master[
        [
            "sku_id",
            "store_id",
            "launch_date",
            "first_sale_date",
            "last_sale_date",
            "sku_age_days"
        ]
    ].head(10)
)

               sku_id store_id launch_date first_sale_date last_sale_date  sku_age_days
0  HOBBIES_1_001_CA_1     CA_1  2013-07-13      2013-07-18     2016-04-24          1016
1  HOBBIES_1_002_CA_1     CA_1  2011-06-18      2011-06-21     2016-04-20          1772
2  HOBBIES_1_003_CA_1     CA_1  2014-02-01      2014-02-07     2016-04-24           813
3  HOBBIES_1_004_CA_1     CA_1  2011-03-05      2011-03-06     2016-04-24          1877
4  HOBBIES_1_005_CA_1     CA_1  2011-05-21      2011-05-21     2016-04-24          1800
5  HOBBIES_1_006_CA_1     CA_1  2012-03-31      2012-04-02     2016-04-22          1485
6  HOBBIES_1_007_CA_1     CA_1  2012-07-07      2012-07-12     2016-04-24          1387
7  HOBBIES_1_008_CA_1     CA_1  2011-01-29      2011-01-29     2016-04-24          1912
8  HOBBIES_1_009_CA_1     CA_1  2011-01-29      2011-01-29     2016-04-19          1912
9  HOBBIES_1_010_CA_1     CA_1  2011-01-29      2011-01-31     2016-04-24          1912

#### ✅ Validation Result

The SKU lifecycle fields were engineered and validated successfully for all item-store combinations.

Validation confirmed that:

- All historical sales-day columns were mapped to complete and chronological Calendar dates.
- Estimated launch dates were derived from the earliest retail weeks containing positive selling prices.
- First and last sale dates were identified from positive historical sales activity.
- All lifecycle records use the canonical Project FORESIGHT `sku_id`.
- No missing lifecycle values or duplicate SKU identifiers were detected.
- No sales occurred before the estimated launch date or outside the observed sales period.
- All first-sale and last-sale dates follow the required chronological sequence.
- SKU-age values are complete, non-negative, and correctly calculated.
- All SKU Master foundation records were preserved during lifecycle engineering.

The validated SKU lifecycle attributes are now ready for pricing feature engineering.

#### 🛠️ 11.3.5 Engineer Pricing Fields

SKU-level pricing attributes are derived from the historical weekly selling prices available for each item-store combination.

The `avg_price` field represents the unweighted average of the available weekly selling-price records, while `max_observed_price` represents the highest selling price recorded during the available pricing history. It should be interpreted as a historical reference-price proxy rather than a confirmed official list price.

This step will:

- validate the completeness and positivity of the source selling-price records;
- calculate the average historical weekly selling price for each SKU;
- determine the maximum observed selling price for each SKU;
- create canonical SKU identifiers for the aggregated pricing records;
- integrate the pricing attributes into the SKU Master dataset;
- validate pricing coverage, logical consistency, and merge integrity.

The validated pricing attributes will support profitability analysis, cost estimation, and downstream business reporting.

In [88]:
# ============================================================
# Prepare and Aggregate SKU Pricing Records
# ============================================================

# Remove previously engineered pricing fields when this
# subsection is rerun during notebook development.
existing_pricing_columns = [
    "avg_price",
    "list_price",
    "max_observed_price"
]

sku_master = sku_master.drop(
    columns=[
        column
        for column in existing_pricing_columns
        if column in sku_master.columns
    ],
    errors="ignore"
)

# Preserve the current SKU Master row count
# for subsequent merge-integrity validation.
pricing_input_rows = len(sku_master)

# Count missing weekly selling-price values.
missing_source_prices = (
    sku_prices["sell_price"]
    .isna()
    .sum()
)

# Count zero or negative weekly selling-price records.
non_positive_source_prices = (
    sku_prices["sell_price"] <= 0
).sum()

# Confirm that the source pricing records are complete.
assert missing_source_prices == 0, (
    f"Missing source selling prices detected: "
    f"{missing_source_prices}."
)

# Confirm that all source selling prices are positive.
assert non_positive_source_prices == 0, (
    f"Non-positive source selling prices detected: "
    f"{non_positive_source_prices}."
)

# Calculate historical pricing metrics
# for every item-store combination.
pricing_metrics = (
    sku_prices
    .groupby(
        ["store_id", "item_id"],
        as_index=False
    )
    .agg(
        avg_price=(
            "sell_price",
            "mean"
        ),
        max_observed_price=(
            "sell_price",
            "max"
        ),
        price_week_count=(
            "sell_price",
            "size"
        )
    )
)

# Round the monetary pricing metrics
# to two decimal places.
pricing_metrics["avg_price"] = (
    pricing_metrics["avg_price"]
    .round(2)
)

pricing_metrics["max_observed_price"] = (
    pricing_metrics["max_observed_price"]
    .round(2)
)

# Create the canonical Project FORESIGHT SKU identifier
# for every aggregated pricing record.
pricing_metrics["sku_id"] = (
    pricing_metrics["item_id"].astype("string")
    + "_"
    + pricing_metrics["store_id"].astype("string")
)

# Count duplicate canonical identifiers
# in the aggregated pricing table.
duplicate_pricing_sku_ids = (
    pricing_metrics["sku_id"]
    .duplicated()
    .sum()
)

# Confirm that one pricing record was created per SKU.
assert duplicate_pricing_sku_ids == 0, (
    f"Duplicate aggregated pricing SKU identifiers detected: "
    f"{duplicate_pricing_sku_ids}."
)

print("✅ SKU pricing metrics calculated successfully.")
print(f"Pricing SKU records       : {len(pricing_metrics):,}")
print(f"Missing source prices     : {missing_source_prices:,}")
print(f"Non-positive source prices: {non_positive_source_prices:,}")
print(f"Duplicate pricing SKU IDs : {duplicate_pricing_sku_ids:,}")

✅ SKU pricing metrics calculated successfully.
Pricing SKU records       : 30,490
Missing source prices     : 0
Non-positive source prices: 0
Duplicate pricing SKU IDs : 0

In [89]:
# ============================================================
# Integrate Pricing Attributes into the SKU Master
# ============================================================

# Select the pricing attributes required
# for integration with the SKU Master.
sku_pricing_attributes = pricing_metrics[
    [
        "sku_id",
        "avg_price",
        "max_observed_price"
    ]
].copy()

# Merge the pricing attributes using the canonical
# Project FORESIGHT SKU identifier.
sku_master = sku_master.merge(
    sku_pricing_attributes,
    on="sku_id",
    how="left",
    validate="one_to_one"
)

# Confirm that the merge preserved the SKU Master population.
pricing_rows_preserved = (
    len(sku_master)
    == pricing_input_rows
)

# Count SKU Master records without matched pricing attributes.
unmatched_master_pricing = (
    sku_master[
        [
            "avg_price",
            "max_observed_price"
        ]
    ]
    .isna()
    .any(axis=1)
    .sum()
)

# Count aggregated pricing SKUs not represented
# in the SKU Master foundation.
unused_pricing_skus = (
    ~pricing_metrics["sku_id"].isin(
        sku_master["sku_id"]
    )
).sum()

# Prevent continuation when the merge changes
# the SKU Master row count.
assert pricing_rows_preserved, (
    "The pricing merge changed the SKU Master row count."
)

# Confirm that every SKU received its pricing attributes.
assert unmatched_master_pricing == 0, (
    f"SKU Master records without pricing attributes detected: "
    f"{unmatched_master_pricing}."
)

# Confirm that every aggregated pricing SKU
# is represented in the SKU Master.
assert unused_pricing_skus == 0, (
    f"Pricing SKUs not found in the SKU Master detected: "
    f"{unused_pricing_skus}."
)

print("✅ Pricing attributes integrated successfully.")
print(f"SKU Master shape          : {sku_master.shape}")
print(f"SKUs updated              : {len(sku_master):,}")
print(f"Unmatched Master SKUs     : {unmatched_master_pricing:,}")
print(f"Unused pricing SKUs       : {unused_pricing_skus:,}")
print(f"Row count preserved       : {pricing_rows_preserved}")

✅ Pricing attributes integrated successfully.
SKU Master shape          : (30490, 12)
SKUs updated              : 30,490
Unmatched Master SKUs     : 0
Unused pricing SKUs       : 0
Row count preserved       : True

In [90]:
# ============================================================
# Preview SKU Pricing Fields
# ============================================================

# Display representative engineered pricing attributes.
display(
    sku_master[
        [
            "sku_id",
            "avg_price",
            "max_observed_price"
        ]
    ].head(10)
)

               sku_id  avg_price  max_observed_price
0  HOBBIES_1_001_CA_1       8.29                9.58
1  HOBBIES_1_002_CA_1       3.97                3.97
2  HOBBIES_1_003_CA_1       2.97                2.97
3  HOBBIES_1_004_CA_1       4.53                4.64
4  HOBBIES_1_005_CA_1       2.94                3.08
5  HOBBIES_1_006_CA_1       0.99                1.00
6  HOBBIES_1_007_CA_1       7.89                7.94
7  HOBBIES_1_008_CA_1       0.48                0.50
8  HOBBIES_1_009_CA_1       1.76                1.77
9  HOBBIES_1_010_CA_1       2.98                3.17

In [91]:
# ============================================================
# Validate SKU Pricing Fields
# ============================================================

# Define the engineered pricing fields.
pricing_columns = [
    "avg_price",
    "max_observed_price"
]

# Count missing values in the engineered pricing fields.
missing_pricing_values = (
    sku_master[pricing_columns]
    .isna()
    .sum()
)

# Count records where the average price
# exceeds the maximum observed price.
invalid_price_relationships = (
    sku_master["avg_price"]
    > sku_master["max_observed_price"]
).sum()

# Count records containing zero or negative
# engineered pricing values.
non_positive_engineered_prices = (
    (
        sku_master["avg_price"] <= 0
    )
    |
    (
        sku_master["max_observed_price"] <= 0
    )
).sum()

# Confirm that both pricing fields
# contain numeric data types.
pricing_fields_are_numeric = all(
    pd.api.types.is_numeric_dtype(
        sku_master[column]
    )
    for column in pricing_columns
)

# Count duplicate canonical SKU identifiers
# after pricing integration.
duplicate_master_sku_ids = (
    sku_master["sku_id"]
    .duplicated()
    .sum()
)

# Reconfirm that the pricing merge
# preserved the SKU Master row count.
pricing_rows_preserved = (
    len(sku_master)
    == pricing_input_rows
)

# Ensure all engineered pricing fields are complete.
assert missing_pricing_values.sum() == 0, (
    f"Missing engineered pricing values detected: "
    f"{missing_pricing_values.to_dict()}."
)

# Ensure the average price does not exceed
# the maximum observed price.
assert invalid_price_relationships == 0, (
    f"Invalid average-to-maximum price relationships detected: "
    f"{invalid_price_relationships}."
)

# Ensure all engineered prices are positive.
assert non_positive_engineered_prices == 0, (
    f"Non-positive engineered prices detected: "
    f"{non_positive_engineered_prices}."
)

# Ensure both pricing fields are numeric.
assert pricing_fields_are_numeric, (
    "One or more engineered pricing fields "
    "contain a non-numeric data type."
)

# Ensure canonical SKU identifiers remain unique.
assert duplicate_master_sku_ids == 0, (
    f"Duplicate SKU identifiers detected after pricing integration: "
    f"{duplicate_master_sku_ids}."
)

# Ensure no records were lost or added during integration.
assert pricing_rows_preserved, (
    "Pricing integration did not preserve "
    "the SKU Master row count."
)

# Display the pricing-validation summary.
print("✅ SKU pricing fields validated successfully.")
print(f"Missing pricing values         : {missing_pricing_values.sum():,}")
print(f"Invalid price relationships    : {invalid_price_relationships:,}")
print(f"Non-positive engineered prices : {non_positive_engineered_prices:,}")
print(f"Numeric pricing data types     : {pricing_fields_are_numeric}")
print(f"Duplicate Master SKU IDs       : {duplicate_master_sku_ids:,}")
print(f"Pricing row count preserved    : {pricing_rows_preserved}")

✅ SKU pricing fields validated successfully.
Missing pricing values         : 0
Invalid price relationships    : 0
Non-positive engineered prices : 0
Numeric pricing data types     : True
Duplicate Master SKU IDs       : 0
Pricing row count preserved    : True

#### ✅ Validation Result

The SKU pricing attributes were engineered and validated successfully for all item-store combinations.

Validation confirmed that:

- All source weekly selling-price records were complete and positive.
- One aggregated pricing record was created for every canonical SKU.
- `avg_price` represents the unweighted average of the available weekly selling prices.
- `max_observed_price` represents the highest selling price recorded for each SKU.
- Every SKU Master record received complete pricing attributes.
- No unmatched or unused pricing SKU records were detected.
- Average prices do not exceed their corresponding maximum observed prices.
- All engineered pricing values are numeric and positive.
- Canonical SKU identifiers remained unique.
- The SKU Master row count was preserved during pricing integration.

The validated pricing attributes are now ready for cost and gross-margin estimation.

#### 💰 11.3.6 Estimate Cost and Margin Fields

Estimated cost and margin attributes are derived from the engineered `max_observed_price` using a documented business assumption.

Because actual procurement-cost data is unavailable, the maximum observed selling price is used as a reference-price proxy. The estimated unit cost is assumed to represent 70% of this reference price, while the remaining amount represents the estimated gross margin per unit.

These fields are analytical estimates and should not be interpreted as actual procurement costs or realized accounting margins.

This step will:

- define and validate the cost-estimation assumption;
- estimate the unit cost for every canonical SKU;
- calculate the corresponding estimated gross margin per unit;
- validate the calculations, financial relationships, and record preservation.

The validated estimated financial attributes will support profitability-oriented analysis, inventory valuation assumptions, and downstream business reporting.

In [92]:
# ============================================================
# Estimate SKU Cost and Margin Fields
# ============================================================

# Remove previously engineered financial fields when this
# subsection is rerun during notebook development.
existing_financial_columns = [
    "unit_cost",
    "gross_margin",
    "estimated_unit_cost",
    "estimated_gross_margin"
]

sku_master = sku_master.drop(
    columns=[
        column
        for column in existing_financial_columns
        if column in sku_master.columns
    ],
    errors="ignore"
)

# Preserve the current SKU Master row count
# for subsequent integrity validation.
financial_input_rows = len(sku_master)

# Define the documented cost-estimation assumption.
ESTIMATED_COST_RATE = 0.70

# Confirm that the assumption represents
# a valid proportion between zero and one.
assert 0 < ESTIMATED_COST_RATE < 1, (
    "The estimated cost rate must be "
    "greater than 0 and less than 1."
)

# Confirm that the required reference-price field is available.
assert "max_observed_price" in sku_master.columns, (
    "The max_observed_price field is required "
    "before estimating cost and margin."
)

# Count missing reference-price values.
missing_reference_prices = (
    sku_master["max_observed_price"]
    .isna()
    .sum()
)

# Count zero or negative reference-price values.
non_positive_reference_prices = (
    sku_master["max_observed_price"] <= 0
).sum()

# Validate the reference-price field
# before calculating financial estimates.
assert missing_reference_prices == 0, (
    f"Missing reference prices detected: "
    f"{missing_reference_prices}."
)

assert non_positive_reference_prices == 0, (
    f"Non-positive reference prices detected: "
    f"{non_positive_reference_prices}."
)

# Estimate unit cost using the documented
# percentage of the maximum observed price.
sku_master["estimated_unit_cost"] = (
    sku_master["max_observed_price"]
    * ESTIMATED_COST_RATE
).round(2)

# Calculate the estimated gross margin per unit
# using the reference price and estimated unit cost.
sku_master["estimated_gross_margin"] = (
    sku_master["max_observed_price"]
    - sku_master["estimated_unit_cost"]
).round(2)

# Display the financial-engineering summary.
print("✅ Estimated cost and margin fields engineered successfully.")
print(f"Cost estimation rate     : {ESTIMATED_COST_RATE:.0%}")
print(f"Dataset shape            : {sku_master.shape}")
print(f"SKUs updated             : {len(sku_master):,}")
print(f"Missing reference prices : {missing_reference_prices:,}")

✅ Estimated cost and margin fields engineered successfully.
Cost estimation rate     : 70%
Dataset shape            : (30490, 14)
SKUs updated             : 30,490
Missing reference prices : 0

In [93]:
# ============================================================
# Preview Estimated Cost and Margin Fields
# ============================================================

# Display representative estimated financial attributes.
display(
    sku_master[
        [
            "sku_id",
            "max_observed_price",
            "estimated_unit_cost",
            "estimated_gross_margin"
        ]
    ].head(10)
)

               sku_id  max_observed_price  estimated_unit_cost  estimated_gross_margin
0  HOBBIES_1_001_CA_1                9.58                 6.71                    2.87
1  HOBBIES_1_002_CA_1                3.97                 2.78                    1.19
2  HOBBIES_1_003_CA_1                2.97                 2.08                    0.89
3  HOBBIES_1_004_CA_1                4.64                 3.25                    1.39
4  HOBBIES_1_005_CA_1                3.08                 2.16                    0.92
5  HOBBIES_1_006_CA_1                1.00                 0.70                    0.30
6  HOBBIES_1_007_CA_1                7.94                 5.56                    2.38
7  HOBBIES_1_008_CA_1                0.50                 0.35                    0.15
8  HOBBIES_1_009_CA_1                1.77                 1.24                    0.53
9  HOBBIES_1_010_CA_1                3.17                 2.22                    0.95

In [94]:
# ============================================================
# Validate Estimated Cost and Margin Fields
# ============================================================

# Define the estimated financial fields.
financial_columns = [
    "estimated_unit_cost",
    "estimated_gross_margin"
]

# Count missing values in the estimated financial fields.
missing_financial_values = (
    sku_master[financial_columns]
    .isna()
    .sum()
)

# Count zero or negative estimated unit costs.
non_positive_estimated_costs = (
    sku_master["estimated_unit_cost"] <= 0
).sum()

# Count zero or negative estimated gross margins.
non_positive_estimated_margins = (
    sku_master["estimated_gross_margin"] <= 0
).sum()

# Count records where estimated cost equals or exceeds
# the maximum observed reference price.
invalid_cost_relationships = (
    sku_master["estimated_unit_cost"]
    >= sku_master["max_observed_price"]
).sum()

# Recalculate the expected unit-cost estimates
# using the documented assumption.
expected_estimated_unit_cost = (
    sku_master["max_observed_price"]
    * ESTIMATED_COST_RATE
).round(2)

# Recalculate the expected gross-margin estimates.
expected_estimated_gross_margin = (
    sku_master["max_observed_price"]
    - expected_estimated_unit_cost
).round(2)

# Count incorrectly calculated unit-cost values.
invalid_cost_calculations = (
    ~np.isclose(
        sku_master["estimated_unit_cost"],
        expected_estimated_unit_cost,
        atol=0.01
    )
).sum()

# Count incorrectly calculated gross-margin values.
invalid_margin_calculations = (
    ~np.isclose(
        sku_master["estimated_gross_margin"],
        expected_estimated_gross_margin,
        atol=0.01
    )
).sum()

# Confirm that estimated cost and margin reconcile
# to the maximum observed reference price.
invalid_financial_reconciliations = (
    ~np.isclose(
        (
            sku_master["estimated_unit_cost"]
            + sku_master["estimated_gross_margin"]
        ),
        sku_master["max_observed_price"],
        atol=0.01
    )
).sum()

# Confirm that both financial fields use numeric data types.
financial_fields_are_numeric = all(
    pd.api.types.is_numeric_dtype(
        sku_master[column]
    )
    for column in financial_columns
)

# Count duplicate canonical SKU identifiers
# after financial feature engineering.
duplicate_financial_sku_ids = (
    sku_master["sku_id"]
    .duplicated()
    .sum()
)

# Confirm that financial engineering preserved
# the SKU Master population.
financial_rows_preserved = (
    len(sku_master)
    == financial_input_rows
)

# Ensure all estimated financial fields are complete.
assert missing_financial_values.sum() == 0, (
    f"Missing estimated financial values detected: "
    f"{missing_financial_values.to_dict()}."
)

# Ensure every estimated unit cost is positive.
assert non_positive_estimated_costs == 0, (
    f"Non-positive estimated unit costs detected: "
    f"{non_positive_estimated_costs}."
)

# Ensure every estimated gross margin is positive.
assert non_positive_estimated_margins == 0, (
    f"Non-positive estimated gross margins detected: "
    f"{non_positive_estimated_margins}."
)

# Ensure estimated cost remains below
# the maximum observed reference price.
assert invalid_cost_relationships == 0, (
    f"Invalid cost-to-price relationships detected: "
    f"{invalid_cost_relationships}."
)

# Ensure the unit-cost calculation follows
# the documented business assumption.
assert invalid_cost_calculations == 0, (
    f"Incorrect estimated unit-cost calculations detected: "
    f"{invalid_cost_calculations}."
)

# Ensure the gross-margin calculation is correct.
assert invalid_margin_calculations == 0, (
    f"Incorrect estimated gross-margin calculations detected: "
    f"{invalid_margin_calculations}."
)

# Ensure estimated cost and margin reconcile
# to the reference price.
assert invalid_financial_reconciliations == 0, (
    f"Financial reconciliation errors detected: "
    f"{invalid_financial_reconciliations}."
)

# Ensure both financial fields are numeric.
assert financial_fields_are_numeric, (
    "One or more estimated financial fields "
    "contain a non-numeric data type."
)

# Ensure canonical SKU identifiers remain unique.
assert duplicate_financial_sku_ids == 0, (
    f"Duplicate SKU identifiers detected: "
    f"{duplicate_financial_sku_ids}."
)

# Ensure no SKU Master records were lost or added.
assert financial_rows_preserved, (
    "Financial feature engineering changed "
    "the SKU Master row count."
)

# Display the financial-validation summary.
print("✅ Estimated cost and margin fields validated successfully.")
print(f"Missing financial values       : {missing_financial_values.sum():,}")
print(f"Non-positive estimated costs   : {non_positive_estimated_costs:,}")
print(f"Non-positive estimated margins : {non_positive_estimated_margins:,}")
print(f"Invalid cost relationships     : {invalid_cost_relationships:,}")
print(f"Invalid cost calculations      : {invalid_cost_calculations:,}")
print(f"Invalid margin calculations    : {invalid_margin_calculations:,}")
print(f"Reconciliation errors          : {invalid_financial_reconciliations:,}")
print(f"Numeric financial data types   : {financial_fields_are_numeric}")
print(f"Financial row count preserved  : {financial_rows_preserved}")

✅ Estimated cost and margin fields validated successfully.
Missing financial values       : 0
Non-positive estimated costs   : 0
Non-positive estimated margins : 0
Invalid cost relationships     : 0
Invalid cost calculations      : 0
Invalid margin calculations    : 0
Reconciliation errors          : 0
Numeric financial data types   : True
Financial row count preserved  : True

#### ✅ Validation Result

The estimated SKU cost and margin fields were engineered and validated successfully.

Validation confirmed that:

- The documented 70% cost-estimation assumption was applied consistently.
- All calculations use `max_observed_price` as the reference-price proxy.
- Estimated unit costs and gross margins are complete, numeric, and positive.
- Every estimated unit cost remains below its corresponding reference price.
- Estimated unit costs were calculated accurately from the documented cost rate.
- Estimated gross margins were calculated accurately from the reference price and estimated cost.
- Estimated cost and gross margin reconcile to the maximum observed price within the required rounding tolerance.
- Canonical SKU identifiers remained unique.
- The SKU Master row count was preserved during financial feature engineering.

These fields are analytical estimates rather than actual procurement costs or realized accounting margins. The validated SKU Master is now ready for SKU-status classification.

#### 🏷️ 11.3.7 Classify SKU Status

SKU status is classified using the recency of positive sales activity for each item-store combination.

The classification represents a historical snapshot as of the final date in the observed sales period. It does not represent the SKU’s current real-world commercial status.

The following Project FORESIGHT business rules are applied:

- **Active:** the last recorded sale occurred within the previous 30 days;
- **Slow Moving:** the last recorded sale occurred between 31 and 90 days ago;
- **Inactive:** the last recorded sale occurred more than 90 days ago.

This step will:

- calculate the number of days since the last recorded sale for each SKU;
- classify each SKU using documented recency thresholds;
- retain the recency measure for reporting and classification traceability;
- validate classification completeness, rule accuracy, identifier uniqueness, and record preservation.

The validated SKU-status attributes will support inventory monitoring, assortment analysis, and downstream business reporting.

In [95]:
# ============================================================
# Classify SKU Status
# ============================================================

# Remove previously engineered status fields when this
# subsection is rerun during notebook development.
existing_status_columns = [
    "days_since_last_sale",
    "product_status",
    "sku_status"
]

sku_master = sku_master.drop(
    columns=[
        column
        for column in existing_status_columns
        if column in sku_master.columns
    ],
    errors="ignore"
)

# Preserve the current SKU Master row count.
status_input_rows = len(sku_master)

# Define the classification thresholds.
ACTIVE_MAX_DAYS = 30
SLOW_MOVING_MAX_DAYS = 90

# Validate the threshold sequence.
assert 0 <= ACTIVE_MAX_DAYS < SLOW_MOVING_MAX_DAYS, (
    "The SKU-status thresholds are not logically ordered."
)

# Confirm that the required lifecycle fields are available.
required_status_columns = [
    "sku_id",
    "last_sale_date"
]

missing_status_columns = [
    column
    for column in required_status_columns
    if column not in sku_master.columns
]

assert len(missing_status_columns) == 0, (
    f"Required status fields are missing: "
    f"{missing_status_columns}."
)

# Count missing last-sale dates.
missing_last_sale_dates = (
    sku_master["last_sale_date"]
    .isna()
    .sum()
)

assert missing_last_sale_dates == 0, (
    f"Missing last-sale dates detected: "
    f"{missing_last_sale_dates}."
)

# Calculate sales recency as of the final
# observed historical sales date.
sku_master["days_since_last_sale"] = (
    observation_end_date
    - sku_master["last_sale_date"]
).dt.days.astype("Int32")

# Count invalid negative recency values.
negative_sales_recency = (
    sku_master["days_since_last_sale"] < 0
).sum()

assert negative_sales_recency == 0, (
    f"Negative sales-recency values detected: "
    f"{negative_sales_recency}."
)

# Define the classification conditions.
status_conditions = [
    (
        sku_master["days_since_last_sale"]
        <= ACTIVE_MAX_DAYS
    ).to_numpy(),
    (
        sku_master["days_since_last_sale"]
        <= SLOW_MOVING_MAX_DAYS
    ).to_numpy()
]

# Classify every SKU using the documented rules.
sku_master["sku_status"] = pd.Series(
    np.select(
        status_conditions,
        [
            "Active",
            "Slow Moving"
        ],
        default="Inactive"
    ),
    index=sku_master.index,
    dtype="string"
)

print("✅ SKU status classified successfully.")
print(f"Status reference date : {observation_end_date.date()}")
print(f"Active threshold      : 0–{ACTIVE_MAX_DAYS} days")
print(
    f"Slow Moving threshold : "
    f"{ACTIVE_MAX_DAYS + 1}–{SLOW_MOVING_MAX_DAYS} days"
)
print(
    f"Inactive threshold    : "
    f"More than {SLOW_MOVING_MAX_DAYS} days"
)
print(f"SKUs classified       : {len(sku_master):,}")

✅ SKU status classified successfully.
Status reference date : 2016-04-24
Active threshold      : 0–30 days
Slow Moving threshold : 31–90 days
Inactive threshold    : More than 90 days
SKUs classified       : 30,490

In [96]:
# ============================================================
# Preview SKU Status
# ============================================================

# Display representative classifications together
# with their underlying sales-recency values.
display(
    sku_master[
        [
            "sku_id",
            "last_sale_date",
            "days_since_last_sale",
            "sku_status"
        ]
    ].head(10)
)

               sku_id last_sale_date  days_since_last_sale sku_status
0  HOBBIES_1_001_CA_1     2016-04-24                     0     Active
1  HOBBIES_1_002_CA_1     2016-04-20                     4     Active
2  HOBBIES_1_003_CA_1     2016-04-24                     0     Active
3  HOBBIES_1_004_CA_1     2016-04-24                     0     Active
4  HOBBIES_1_005_CA_1     2016-04-24                     0     Active
5  HOBBIES_1_006_CA_1     2016-04-22                     2     Active
6  HOBBIES_1_007_CA_1     2016-04-24                     0     Active
7  HOBBIES_1_008_CA_1     2016-04-24                     0     Active
8  HOBBIES_1_009_CA_1     2016-04-19                     5     Active
9  HOBBIES_1_010_CA_1     2016-04-24                     0     Active

In [97]:
# ============================================================
# Validate SKU Status
# ============================================================

# Define the permitted SKU-status categories.
expected_sku_statuses = {
    "Active",
    "Slow Moving",
    "Inactive"
}

# Count missing values.
missing_sales_recency = (
    sku_master["days_since_last_sale"]
    .isna()
    .sum()
)

missing_sku_status = (
    sku_master["sku_status"]
    .isna()
    .sum()
)

# Count unsupported status values.
invalid_sku_status = (
    ~sku_master["sku_status"]
    .isin(expected_sku_statuses)
).sum()

# Recalculate the expected classifications
# directly from the documented thresholds.
expected_status_by_rule = pd.Series(
    np.select(
        [
            (
                sku_master["days_since_last_sale"]
                <= ACTIVE_MAX_DAYS
            ).to_numpy(),
            (
                sku_master["days_since_last_sale"]
                <= SLOW_MOVING_MAX_DAYS
            ).to_numpy()
        ],
        [
            "Active",
            "Slow Moving"
        ],
        default="Inactive"
    ),
    index=sku_master.index,
    dtype="string"
)

# Count incorrectly assigned classifications.
incorrect_status_assignments = (
    sku_master["sku_status"]
    != expected_status_by_rule
).sum()

# Count duplicate canonical SKU identifiers.
duplicate_status_sku_ids = (
    sku_master["sku_id"]
    .duplicated()
    .sum()
)

# Confirm that the SKU population was preserved.
status_rows_preserved = (
    len(sku_master)
    == status_input_rows
)

# Calculate the status distribution.
status_order = [
    "Active",
    "Slow Moving",
    "Inactive"
]

status_distribution = (
    sku_master["sku_status"]
    .value_counts()
    .reindex(
        status_order,
        fill_value=0
    )
)

status_percentage = (
    sku_master["sku_status"]
    .value_counts(normalize=True)
    .mul(100)
    .reindex(
        status_order,
        fill_value=0
    )
    .round(2)
)

# Confirm that the distribution includes every SKU.
status_distribution_complete = (
    status_distribution.sum()
    == len(sku_master)
)

# Apply validation rules.
assert missing_sales_recency == 0, (
    f"Missing sales-recency values detected: "
    f"{missing_sales_recency}."
)

assert negative_sales_recency == 0, (
    f"Negative sales-recency values detected: "
    f"{negative_sales_recency}."
)

assert missing_sku_status == 0, (
    f"Missing SKU-status values detected: "
    f"{missing_sku_status}."
)

assert invalid_sku_status == 0, (
    f"Unsupported SKU-status values detected: "
    f"{invalid_sku_status}."
)

assert incorrect_status_assignments == 0, (
    f"Incorrect SKU-status assignments detected: "
    f"{incorrect_status_assignments}."
)

assert duplicate_status_sku_ids == 0, (
    f"Duplicate SKU identifiers detected: "
    f"{duplicate_status_sku_ids}."
)

assert status_rows_preserved, (
    "SKU-status classification changed "
    "the SKU Master row count."
)

assert status_distribution_complete, (
    "The SKU-status distribution does not "
    "account for every SKU."
)

# Display the validation results only
# after all assertions have passed.
print("✅ SKU status validated successfully.")
print(f"Missing sales recency      : {missing_sales_recency:,}")
print(f"Negative sales recency     : {negative_sales_recency:,}")
print(f"Missing SKU status         : {missing_sku_status:,}")
print(f"Invalid status values      : {invalid_sku_status:,}")
print(f"Incorrect assignments      : {incorrect_status_assignments:,}")
print(f"Duplicate SKU IDs          : {duplicate_status_sku_ids:,}")
print(f"Row count preserved        : {status_rows_preserved}")

print("\nSKU Status Distribution:")
print(status_distribution)

print("\nSKU Status Percentage (%):")
print(status_percentage)

✅ SKU status validated successfully.
Missing sales recency      : 0
Negative sales recency     : 0
Missing SKU status         : 0
Invalid status values      : 0
Incorrect assignments      : 0
Duplicate SKU IDs          : 0
Row count preserved        : True

SKU Status Distribution:
sku_status
Active         29015
Slow Moving     1097
Inactive         378
Name: count, dtype: int64[pyarrow]

SKU Status Percentage (%):
sku_status
Active        95.16
Slow Moving    3.60
Inactive       1.24
Name: proportion, dtype: double[pyarrow]

#### ✅ Validation Result

The SKU-status attributes were engineered and validated successfully for all 30,490 item-store combinations.

Validation confirmed that:

- Sales recency was calculated as of 24 April 2016.
- All `days_since_last_sale` values are complete and non-negative.
- Every SKU was classified using the documented 30-day and 90-day thresholds.
- No missing, invalid, or incorrectly assigned status values were detected.
- All canonical `sku_id` values remained unique.
- The SKU Master row count was preserved during classification.
- The final status distribution contains 29,015 Active SKUs, 1,097 Slow Moving SKUs, and 378 Inactive SKUs.
- Active, Slow Moving, and Inactive SKUs represent 95.16%, 3.60%, and 1.24% of the complete SKU population, respectively.

The validated SKU Master is now ready for final dataset preparation.

#### 📋 11.3.8 Prepare Final SKU Master Dataset

The completed SKU Master dataset is prepared by selecting and arranging the validated reference, lifecycle, pricing, financial, and status fields in a consistent business-ready structure.

Each record represents one canonical item-store combination identified by `sku_id`. The final schema retains the engineered sales-recency field for status traceability and explicitly labels price, cost, and margin estimates according to their analytical meaning.

This step will:

- define the required final SKU Master schema;
- confirm that all required engineered fields are available;
- select and arrange the fields in a logical business order;
- sort the dataset using the canonical SKU identifier;
- create an independent final dataset for inspection and export.

The prepared dataset will serve as the primary SKU-store reference table for inventory analysis, forecasting, dashboard reporting, and downstream analytical workflows.

In [98]:
# ============================================================
# Prepare Final SKU Master Dataset
# ============================================================

# Define the required final business-ready column order.
final_sku_master_columns = [
    "sku_id",
    "item_id",
    "category",
    "department",
    "store_id",
    "state_id",
    "launch_date",
    "first_sale_date",
    "last_sale_date",
    "sku_age_days",
    "days_since_last_sale",
    "avg_price",
    "max_observed_price",
    "estimated_unit_cost",
    "estimated_gross_margin",
    "sku_status"
]

# Identify required final fields that are not available
# in the engineered SKU Master working dataset.
missing_final_columns = [
    column
    for column in final_sku_master_columns
    if column not in sku_master.columns
]

# Prevent preparation when an expected engineered field
# is unavailable.
assert len(missing_final_columns) == 0, (
    f"Required final SKU Master fields are missing: "
    f"{missing_final_columns}."
)

# Preserve the working-dataset row count.
sku_master_working_rows = len(sku_master)

# Select the required fields, arrange them in the defined
# order, and create a deterministic SKU-level sort order.
sku_master_final = (
    sku_master[
        final_sku_master_columns
    ]
    .sort_values("sku_id")
    .reset_index(drop=True)
    .copy()
)

# Confirm that final preparation preserved every SKU record.
assert len(sku_master_final) == sku_master_working_rows, (
    "Final SKU Master preparation changed "
    "the working dataset row count."
)

print("✅ Final SKU Master dataset prepared successfully.")
print(f"Dataset shape     : {sku_master_final.shape}")
print(f"Total SKUs        : {len(sku_master_final):,}")
print(f"Columns selected  : {len(final_sku_master_columns)}")
print(f"Rows preserved    : {len(sku_master_final) == sku_master_working_rows}")

✅ Final SKU Master dataset prepared successfully.
Dataset shape     : (30490, 16)
Total SKUs        : 30,490
Columns selected  : 16
Rows preserved    : True

In [99]:
# ============================================================
# Preview Final SKU Master Dataset
# ============================================================

# Display representative records from the completed
# business-ready SKU Master dataset.
display(
    sku_master_final.head(10)
)

,sku_id,item_id,category,department,store_id,state_id,launch_date,first_sale_date,last_sale_date,sku_age_days,days_since_last_sale,avg_price,max_observed_price,estimated_unit_cost,estimated_gross_margin,sku_status
0,FOODS_1_001_CA_1,FOODS_1_001,FOODS,FOODS_1,CA_1,CA,2011-01-29,2011-01-29,2016-04-23,1912,1,2.17,2.24,1.57,0.67,Active
1,FOODS_1_001_CA_2,FOODS_1_001,FOODS,FOODS_1,CA_2,CA,2011-01-29,2011-01-29,2016-04-24,1912,0,2.17,2.24,1.57,0.67,Active
2,FOODS_1_001_CA_3,FOODS_1_001,FOODS,FOODS_1,CA_3,CA,2011-01-29,2011-01-29,2016-04-23,1912,1,2.16,2.24,1.57,0.67,Active
3,FOODS_1_001_CA_4,FOODS_1_001,FOODS,FOODS_1,CA_4,CA,2011-01-29,2011-01-30,2016-04-24,1912,0,2.17,2.24,1.57,0.67,Active
4,FOODS_1_001_TX_1,FOODS_1_001,FOODS,FOODS_1,TX_1,TX,2011-01-29,2011-01-30,2016-04-05,1912,19,2.16,2.24,1.57,0.67,Active
5,FOODS_1_001_TX_2,FOODS_1_001,FOODS,FOODS_1,TX_2,TX,2011-01-29,2011-01-31,2016-04-23,1912,1,2.17,2.24,1.57,0.67,Active
6,FOODS_1_001_TX_3,FOODS_1_001,FOODS,FOODS_1,TX_3,TX,2011-02-05,2011-02-08,2016-04-21,1905,3,2.17,2.24,1.57,0.67,Active
7,FOODS_1_001_WI_1,FOODS_1_001,FOODS,FOODS_1,WI_1,WI,2011-01-29,2011-01-30,2016-04-24,1912,0,2.17,2.24,1.57,0.67,Active
8,FOODS_1_001_WI_2,FOODS_1_001,FOODS,FOODS_1,WI_2,WI,2011-01-29,2011-02-03,2016-04-20,1912,4,2.17,2.24,1.57,0.67,Active
9,FOODS_1_001_WI_3,FOODS_1_001,FOODS,FOODS_1,WI_3,WI,2011-01-29,2011-02-03,2016-04-23,1912,1,2.17,2.24,1.57,0.67,Active

In [100]:
# ============================================================
# Inspect Final SKU Master Structure
# ============================================================

# Display the final dimensions, column names,
# non-null counts, and data types.
sku_master_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 30490 entries, 0 to 30489
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   sku_id                  30490 non-null  object
 1   item_id                 30490 non-null  str
 2   category                30490 non-null  str
 3   department              30490 non-null  str
 4   store_id                30490 non-null  str
 5   state_id                30490 non-null  str
 6   launch_date             30490 non-null  datetime64[us]
 7   first_sale_date         30490 non-null  datetime64[ns]
 8   last_sale_date          30490 non-null  datetime64[ns]
 9   sku_age_days            30490 non-null  Int32
 10  days_since_last_sale    30490 non-null  Int32
 11  avg_price               30490 non-null  float64
 12  max_observed_price      30490 non-null  float64
 13  estimated_unit_cost     30490 non-null  float64
 14  estimated_gross_margin  30490 non-null  float64
 15  sku_status              30490 non-null  string
dtypes: Int32(2), datetime64[ns](2), datetime64[us](1), float64(4), object(1), str(5), string(1)
memory usage: 4.7+ MB

#### 📋 Preparation Summary

The final SKU Master dataset was prepared successfully in a consistent business-ready structure.

Preparation confirmed that:

- One record was retained for every canonical item-store combination.
- All required reference, lifecycle, pricing, financial, and status fields were available.
- The unsupported duplicate `subcategory` field was excluded.
- `days_since_last_sale` was retained to provide status-classification traceability.
- Historical reference-price, cost, and margin estimates were labelled explicitly.
- The canonical `sku_id` was retained as the primary dataset key.
- All working SKU records were preserved during final preparation.
- The records were arranged in a deterministic SKU-level order.

The prepared SKU Master dataset is now ready for final quality validation and export.

#### 📤 11.3.9 Validate and Export SKU Master Dataset

The completed SKU Master dataset will undergo a final end-to-end quality validation before being exported to the processed data directory.

This stage confirms that the final dataset preserves the required schema, canonical identifiers, lifecycle relationships, pricing logic, estimated financial calculations, and SKU-status classifications. The exported CSV will then be reloaded and compared with the in-memory dataset to verify successful round-trip preservation.

This step will:

- validate the final schema, record count, completeness, and identifier uniqueness;
- confirm canonical SKU construction and hierarchy consistency;
- validate lifecycle, pricing, estimated financial, and status business rules;
- export the validated dataset to the processed data directory;
- reload the exported file and verify its structure and content.

The successfully verified export will serve as the official SKU-store reference table for downstream Project FORESIGHT workflows.

In [101]:
# ============================================================
# Validate Final SKU Master Structure and Integrity
# ============================================================

from pandas.api.types import (
    is_datetime64_any_dtype,
    is_numeric_dtype
)

# Define the required final SKU Master schema.
expected_final_sku_columns = [
    "sku_id",
    "item_id",
    "category",
    "department",
    "store_id",
    "state_id",
    "launch_date",
    "first_sale_date",
    "last_sale_date",
    "sku_age_days",
    "days_since_last_sale",
    "avg_price",
    "max_observed_price",
    "estimated_unit_cost",
    "estimated_gross_margin",
    "sku_status"
]

# Define the date and numeric fields.
final_date_columns = [
    "launch_date",
    "first_sale_date",
    "last_sale_date"
]

final_numeric_columns = [
    "sku_age_days",
    "days_since_last_sale",
    "avg_price",
    "max_observed_price",
    "estimated_unit_cost",
    "estimated_gross_margin"
]

# Calculate the expected SKU population directly
# from the unique item-store combinations.
expected_final_sku_count = (
    sku_sales[
        ["item_id", "store_id"]
    ]
    .drop_duplicates()
    .shape[0]
)

# Capture the final dataset dimensions.
final_sku_rows, final_sku_columns = (
    sku_master_final.shape
)

# Confirm exact schema and column order.
final_column_order_match = (
    sku_master_final.columns.tolist()
    == expected_final_sku_columns
)

# Count missing values and duplicate records.
missing_final_values = (
    sku_master_final
    .isna()
    .sum()
    .sum()
)

duplicate_final_rows = (
    sku_master_final
    .duplicated()
    .sum()
)

duplicate_final_sku_ids = (
    sku_master_final["sku_id"]
    .duplicated()
    .sum()
)

duplicate_item_store_pairs = (
    sku_master_final[
        ["item_id", "store_id"]
    ]
    .duplicated()
    .sum()
)

# Reconstruct the expected canonical SKU identifiers.
expected_canonical_sku_ids = (
    sku_master_final["item_id"].astype("string")
    + "_"
    + sku_master_final["store_id"].astype("string")
)

# Count identifiers that do not follow the canonical format.
invalid_canonical_sku_ids = (
    sku_master_final["sku_id"].astype("string")
    != expected_canonical_sku_ids
).sum()

# Confirm deterministic SKU ordering.
sku_ids_are_sorted = (
    sku_master_final["sku_id"]
    .is_monotonic_increasing
)

# Confirm the required date data types.
valid_final_date_types = all(
    is_datetime64_any_dtype(
        sku_master_final[column]
    )
    for column in final_date_columns
)

# Confirm the required numeric data types.
valid_final_numeric_types = all(
    is_numeric_dtype(
        sku_master_final[column]
    )
    for column in final_numeric_columns
)

# Validate item hierarchy consistency.
invalid_item_hierarchy_mappings = (
    sku_master_final
    .groupby("item_id")[
        ["category", "department"]
    ]
    .nunique()
    .gt(1)
    .any(axis=1)
    .sum()
)

# Validate store-to-state consistency.
invalid_store_state_mappings = (
    sku_master_final
    .groupby("store_id")["state_id"]
    .nunique()
    .gt(1)
    .sum()
)

# Apply structural and integrity validation rules.
assert final_column_order_match, (
    "The final SKU Master schema or column order is incorrect."
)

assert final_sku_rows == expected_final_sku_count, (
    f"Unexpected final SKU count: {final_sku_rows}. "
    f"Expected: {expected_final_sku_count}."
)

assert final_sku_columns == len(expected_final_sku_columns), (
    f"Unexpected final column count: {final_sku_columns}."
)

assert missing_final_values == 0, (
    f"Missing final values detected: "
    f"{missing_final_values}."
)

assert duplicate_final_rows == 0, (
    f"Duplicate final rows detected: "
    f"{duplicate_final_rows}."
)

assert duplicate_final_sku_ids == 0, (
    f"Duplicate final SKU identifiers detected: "
    f"{duplicate_final_sku_ids}."
)

assert duplicate_item_store_pairs == 0, (
    f"Duplicate item-store combinations detected: "
    f"{duplicate_item_store_pairs}."
)

assert invalid_canonical_sku_ids == 0, (
    f"Invalid canonical SKU identifiers detected: "
    f"{invalid_canonical_sku_ids}."
)

assert sku_ids_are_sorted, (
    "The final SKU identifiers are not sorted."
)

assert valid_final_date_types, (
    "One or more final lifecycle fields "
    "do not contain datetime values."
)

assert valid_final_numeric_types, (
    "One or more final analytical fields "
    "do not contain numeric values."
)

assert invalid_item_hierarchy_mappings == 0, (
    f"Inconsistent item hierarchy mappings detected: "
    f"{invalid_item_hierarchy_mappings}."
)

assert invalid_store_state_mappings == 0, (
    f"Inconsistent store-state mappings detected: "
    f"{invalid_store_state_mappings}."
)

# Display results only after all checks pass.
print("✅ Final SKU Master structure validated successfully.")
print(f"Rows                         : {final_sku_rows:,}")
print(f"Columns                      : {final_sku_columns}")
print(f"Column structure             : Passed")
print(f"Missing values               : {missing_final_values:,}")
print(f"Duplicate rows               : {duplicate_final_rows:,}")
print(f"Duplicate SKU IDs            : {duplicate_final_sku_ids:,}")
print(f"Duplicate item-store pairs   : {duplicate_item_store_pairs:,}")
print(f"Invalid canonical IDs        : {invalid_canonical_sku_ids:,}")
print(f"SKU ordering                 : Passed")
print(f"Date data types              : Passed")
print(f"Numeric data types           : Passed")
print(f"Hierarchy mapping errors     : {invalid_item_hierarchy_mappings:,}")
print(f"Store-state mapping errors   : {invalid_store_state_mappings:,}")

✅ Final SKU Master structure validated successfully.
Rows                         : 30,490
Columns                      : 16
Column structure             : Passed
Missing values               : 0
Duplicate rows               : 0
Duplicate SKU IDs            : 0
Duplicate item-store pairs   : 0
Invalid canonical IDs        : 0
SKU ordering                 : Passed
Date data types              : Passed
Numeric data types           : Passed
Hierarchy mapping errors     : 0
Store-state mapping errors   : 0

In [102]:
# ============================================================
# Validate Final SKU Master Business Rules
# ============================================================

# Reconstruct the historical sales observation period
# directly from the source Sales and Calendar datasets.
final_sales_day_columns = sorted(
    [
        column
        for column in sku_sales.columns
        if column.startswith("d_")
    ],
    key=lambda column: int(
        column.split("_")[1]
    )
)

final_sales_date_lookup = (
    sku_calendar
    .set_index("d")["date"]
    .reindex(final_sales_day_columns)
)

# Confirm complete day-to-date mapping.
missing_final_date_mappings = (
    final_sales_date_lookup
    .isna()
    .sum()
)

assert missing_final_date_mappings == 0, (
    f"Missing final sales-date mappings detected: "
    f"{missing_final_date_mappings}."
)

final_observation_start_date = (
    final_sales_date_lookup.min()
)

final_observation_end_date = (
    final_sales_date_lookup.max()
)

# ============================================================
# Validate Lifecycle Rules
# ============================================================

invalid_sale_sequences = (
    sku_master_final["first_sale_date"]
    > sku_master_final["last_sale_date"]
).sum()

sales_before_launch = (
    sku_master_final["first_sale_date"]
    < sku_master_final["launch_date"]
).sum()

future_launch_dates = (
    sku_master_final["launch_date"]
    > final_observation_end_date
).sum()

sales_after_observation_end = (
    sku_master_final["last_sale_date"]
    > final_observation_end_date
).sum()

negative_sku_ages = (
    sku_master_final["sku_age_days"] < 0
).sum()

negative_sales_recency = (
    sku_master_final["days_since_last_sale"] < 0
).sum()

expected_sku_age_days = (
    final_observation_end_date
    - sku_master_final["launch_date"]
).dt.days.astype("Int32")

expected_days_since_last_sale = (
    final_observation_end_date
    - sku_master_final["last_sale_date"]
).dt.days.astype("Int32")

invalid_sku_age_calculations = (
    sku_master_final["sku_age_days"]
    != expected_sku_age_days
).sum()

invalid_recency_calculations = (
    sku_master_final["days_since_last_sale"]
    != expected_days_since_last_sale
).sum()


# ============================================================
# Validate Pricing Rules
# ============================================================

non_positive_final_prices = (
    (
        sku_master_final["avg_price"] <= 0
    )
    |
    (
        sku_master_final["max_observed_price"] <= 0
    )
).sum()

invalid_price_relationships = (
    sku_master_final["avg_price"]
    > sku_master_final["max_observed_price"]
).sum()


# ============================================================
# Validate Estimated Financial Rules
# ============================================================

EXPECTED_ESTIMATED_COST_RATE = 0.70

expected_estimated_unit_cost = (
    sku_master_final["max_observed_price"]
    * EXPECTED_ESTIMATED_COST_RATE
).round(2)

expected_estimated_gross_margin = (
    sku_master_final["max_observed_price"]
    - expected_estimated_unit_cost
).round(2)

non_positive_estimated_costs = (
    sku_master_final["estimated_unit_cost"] <= 0
).sum()

non_positive_estimated_margins = (
    sku_master_final["estimated_gross_margin"] <= 0
).sum()

invalid_cost_relationships = (
    sku_master_final["estimated_unit_cost"]
    >= sku_master_final["max_observed_price"]
).sum()

invalid_cost_calculations = (
    ~np.isclose(
        sku_master_final["estimated_unit_cost"],
        expected_estimated_unit_cost,
        atol=0.01
    )
).sum()

invalid_margin_calculations = (
    ~np.isclose(
        sku_master_final["estimated_gross_margin"],
        expected_estimated_gross_margin,
        atol=0.01
    )
).sum()

invalid_financial_reconciliations = (
    ~np.isclose(
        (
            sku_master_final["estimated_unit_cost"]
            + sku_master_final["estimated_gross_margin"]
        ),
        sku_master_final["max_observed_price"],
        atol=0.01
    )
).sum()


# ============================================================
# Validate SKU Status Rules
# ============================================================

FINAL_ACTIVE_MAX_DAYS = 30
FINAL_SLOW_MOVING_MAX_DAYS = 90

expected_final_statuses = {
    "Active",
    "Slow Moving",
    "Inactive"
}

invalid_final_status_values = (
    ~sku_master_final["sku_status"]
    .isin(expected_final_statuses)
).sum()

expected_final_sku_status = pd.Series(
    np.select(
        [
            (
                sku_master_final["days_since_last_sale"]
                <= FINAL_ACTIVE_MAX_DAYS
            ).to_numpy(),

            (
                sku_master_final["days_since_last_sale"]
                <= FINAL_SLOW_MOVING_MAX_DAYS
            ).to_numpy()
        ],
        [
            "Active",
            "Slow Moving"
        ],
        default="Inactive"
    ),
    index=sku_master_final.index,
    dtype="string"
)

incorrect_final_status_assignments = (
    sku_master_final["sku_status"].astype("string")
    != expected_final_sku_status
).sum()


# ============================================================
# Apply Final Business-Rule Assertions
# ============================================================

assert invalid_sale_sequences == 0, (
    f"Invalid lifecycle sequences detected: "
    f"{invalid_sale_sequences}."
)

assert sales_before_launch == 0, (
    f"Sales before estimated launch detected: "
    f"{sales_before_launch}."
)

assert future_launch_dates == 0, (
    f"Future launch dates detected: "
    f"{future_launch_dates}."
)

assert sales_after_observation_end == 0, (
    f"Sales after the observation period detected: "
    f"{sales_after_observation_end}."
)

assert negative_sku_ages == 0, (
    f"Negative SKU ages detected: "
    f"{negative_sku_ages}."
)

assert negative_sales_recency == 0, (
    f"Negative sales-recency values detected: "
    f"{negative_sales_recency}."
)

assert invalid_sku_age_calculations == 0, (
    f"Incorrect SKU-age calculations detected: "
    f"{invalid_sku_age_calculations}."
)

assert invalid_recency_calculations == 0, (
    f"Incorrect sales-recency calculations detected: "
    f"{invalid_recency_calculations}."
)

assert non_positive_final_prices == 0, (
    f"Non-positive final pricing values detected: "
    f"{non_positive_final_prices}."
)

assert invalid_price_relationships == 0, (
    f"Invalid average-to-maximum price relationships detected: "
    f"{invalid_price_relationships}."
)

assert non_positive_estimated_costs == 0, (
    f"Non-positive estimated costs detected: "
    f"{non_positive_estimated_costs}."
)

assert non_positive_estimated_margins == 0, (
    f"Non-positive estimated margins detected: "
    f"{non_positive_estimated_margins}."
)

assert invalid_cost_relationships == 0, (
    f"Invalid estimated cost relationships detected: "
    f"{invalid_cost_relationships}."
)

assert invalid_cost_calculations == 0, (
    f"Incorrect estimated cost calculations detected: "
    f"{invalid_cost_calculations}."
)

assert invalid_margin_calculations == 0, (
    f"Incorrect estimated margin calculations detected: "
    f"{invalid_margin_calculations}."
)

assert invalid_financial_reconciliations == 0, (
    f"Financial reconciliation errors detected: "
    f"{invalid_financial_reconciliations}."
)

assert invalid_final_status_values == 0, (
    f"Invalid final SKU-status values detected: "
    f"{invalid_final_status_values}."
)

assert incorrect_final_status_assignments == 0, (
    f"Incorrect final SKU-status assignments detected: "
    f"{incorrect_final_status_assignments}."
)

# Display results only after every assertion passes.
print("✅ Final SKU Master business rules validated successfully.")
print(f"Observation period              : "
      f"{final_observation_start_date.date()} to "
      f"{final_observation_end_date.date()}")
print(f"Invalid sale sequences          : {invalid_sale_sequences:,}")
print(f"Sales before launch             : {sales_before_launch:,}")
print(f"Future launch dates             : {future_launch_dates:,}")
print(f"Negative SKU ages               : {negative_sku_ages:,}")
print(f"Invalid SKU-age calculations    : {invalid_sku_age_calculations:,}")
print(f"Invalid recency calculations    : {invalid_recency_calculations:,}")
print(f"Non-positive prices             : {non_positive_final_prices:,}")
print(f"Invalid price relationships     : {invalid_price_relationships:,}")
print(f"Invalid cost calculations       : {invalid_cost_calculations:,}")
print(f"Invalid margin calculations     : {invalid_margin_calculations:,}")
print(f"Financial reconciliation errors : {invalid_financial_reconciliations:,}")
print(f"Invalid status values           : {invalid_final_status_values:,}")
print(f"Incorrect status assignments    : {incorrect_final_status_assignments:,}")

✅ Final SKU Master business rules validated successfully.
Observation period              : 2011-01-29 to 2016-04-24
Invalid sale sequences          : 0
Sales before launch             : 0
Future launch dates             : 0
Negative SKU ages               : 0
Invalid SKU-age calculations    : 0
Invalid recency calculations    : 0
Non-positive prices             : 0
Invalid price relationships     : 0
Invalid cost calculations       : 0
Invalid margin calculations     : 0
Financial reconciliation errors : 0
Invalid status values           : 0
Incorrect status assignments    : 0

In [103]:
# ============================================================
# Export and Verify Final SKU Master Dataset
# ============================================================

# Create the processed-data directory when required.
PROCESSED_DATA_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# Define the official export path.
sku_master_output_path = (
    PROCESSED_DATA_DIR
    / "sku_master_final.csv"
)

# Export the validated SKU Master dataset.
sku_master_final.to_csv(
    sku_master_output_path,
    index=False
)

# Confirm that the exported file exists
# and contains written content.
assert sku_master_output_path.exists(), (
    "The SKU Master export file was not created."
)

assert sku_master_output_path.stat().st_size > 0, (
    "The SKU Master export file is empty."
)

# Reload the exported file for round-trip verification.
sku_master_reloaded = pd.read_csv(
    sku_master_output_path,
    parse_dates=[
        "launch_date",
        "first_sale_date",
        "last_sale_date"
    ]
)

# Validate the reloaded structure.
reloaded_column_order_match = (
    sku_master_reloaded.columns.tolist()
    == expected_final_sku_columns
)

reloaded_row_count_match = (
    len(sku_master_reloaded)
    == len(sku_master_final)
)

reloaded_missing_values = (
    sku_master_reloaded
    .isna()
    .sum()
    .sum()
)

reloaded_duplicate_sku_ids = (
    sku_master_reloaded["sku_id"]
    .duplicated()
    .sum()
)

reloaded_duplicate_rows = (
    sku_master_reloaded
    .duplicated()
    .sum()
)

# Confirm that the complete exported content
# matches the validated in-memory dataset.
pd.testing.assert_frame_equal(
    sku_master_reloaded.reset_index(drop=True),
    sku_master_final.reset_index(drop=True),
    check_dtype=False,
    check_exact=False,
    rtol=1e-10,
    atol=1e-10
)

# Apply export verification rules.
assert reloaded_column_order_match, (
    "The reloaded SKU Master schema is incorrect."
)

assert reloaded_row_count_match, (
    "The reloaded SKU Master row count is incorrect."
)

assert reloaded_missing_values == 0, (
    f"Missing values detected after reload: "
    f"{reloaded_missing_values}."
)

assert reloaded_duplicate_sku_ids == 0, (
    f"Duplicate SKU identifiers detected after reload: "
    f"{reloaded_duplicate_sku_ids}."
)

assert reloaded_duplicate_rows == 0, (
    f"Duplicate records detected after reload: "
    f"{reloaded_duplicate_rows}."
)

# Display the export summary only after
# all round-trip checks pass.
print("✅ Final SKU Master dataset exported and verified successfully.")
print(f"Dataset shape         : {sku_master_final.shape}")
print(f"Exported rows         : {len(sku_master_reloaded):,}")
print(f"Exported columns      : {sku_master_reloaded.shape[1]}")
print(f"Missing after reload  : {reloaded_missing_values:,}")
print(f"Duplicate SKU IDs     : {reloaded_duplicate_sku_ids:,}")
print(f"Duplicate rows        : {reloaded_duplicate_rows:,}")
print(f"File size             : {sku_master_output_path.stat().st_size:,} bytes")
print(f"Dataset exported to   : {sku_master_output_path}")

✅ Final SKU Master dataset exported and verified successfully.
Dataset shape         : (30490, 16)
Exported rows         : 30,490
Exported columns      : 16
Missing after reload  : 0
Duplicate SKU IDs     : 0
Duplicate rows        : 0
File size             : 3,839,729 bytes
Dataset exported to   : C:\Users\hp\Project FORESIGHT\data\processed\sku_master_final.csv

#### ✅ Validation Result

The final SKU Master dataset passed all structural, integrity, business-rule, and export-verification checks successfully.

Validation confirmed that:

- The dataset contains one record for each of the 30,490 canonical item-store combinations.
- The required 16-column business-ready schema was preserved.
- No missing values, duplicate records, duplicate identifiers, or duplicate item-store combinations were detected.
- All `sku_id` values follow the canonical Project FORESIGHT identifier convention.
- Product hierarchy and store-state mappings are internally consistent.
- Lifecycle dates, SKU ages, and sales-recency calculations satisfy the required chronological rules.
- All historical pricing values are positive and logically consistent.
- Estimated unit costs and gross margins follow the documented 70% cost assumption.
- All estimated financial fields reconcile with the maximum observed reference price.
- Every SKU-status classification follows the documented 30-day and 90-day recency thresholds.
- The exported CSV was reloaded successfully with its complete structure and content preserved.
- No missing values or duplicate records were introduced during export.

The verified `sku_master_final.csv` file is ready to serve as the official SKU-store reference dataset for downstream Project FORESIGHT workflows.

## 📦 11.4 Inventory Snapshot Dataset Engineering

The M5 source data does not contain observed inventory balances, purchase orders, stock receipts, or stockout records. Therefore, this section creates a simulated Inventory Snapshot dataset using historical demand and documented inventory-policy assumptions.

The engineering workflow will:

- define the simulation assumptions;
- select the development SKU population;
- construct daily inventory movements;
- engineer replenishment and inventory-health metrics;
- validate and export the final dataset.

All stock levels, replenishment activity, lost sales, and inventory values produced in this section are analytical estimates rather than observed retailer records.

### ⚙️ 11.4.1 Define Inventory Simulation Assumptions

This step defines the SKU scope, demand coverage, safety stock, replenishment lead time, and reorder-quantity policy used throughout the inventory simulation.

These values are documented analytical assumptions created for Project FORESIGHT and do not represent observed M5 retailer policies.

In [104]:
# ============================================================
# Define Inventory Simulation Assumptions
# ============================================================

# Define the number of development SKUs
# included in the inventory simulation.
INVENTORY_SAMPLE_SIZE = 300

# Define the base number of demand-coverage days.
DEMAND_COVERAGE_DAYS = 7

# Define the additional safety-stock coverage.
SAFETY_STOCK_DAYS = 3

# Define the assumed supplier replenishment lead time.
LEAD_TIME_DAYS = 5

# Define the multiplier used to determine
# the fixed replenishment quantity.
REORDER_QUANTITY_MULTIPLIER = 2.0

# Calculate the complete target-stock coverage horizon.
TARGET_COVERAGE_DAYS = (
    DEMAND_COVERAGE_DAYS
    + SAFETY_STOCK_DAYS
    + LEAD_TIME_DAYS
)

# Display the configured simulation assumptions.
print("Inventory Simulation Assumptions")
print("-" * 48)
print(f"Inventory SKU population       : {INVENTORY_SAMPLE_SIZE:,}")
print(f"Base demand coverage           : {DEMAND_COVERAGE_DAYS} days")
print(f"Safety-stock coverage          : {SAFETY_STOCK_DAYS} days")
print(f"Replenishment lead time        : {LEAD_TIME_DAYS} days")
print(f"Target coverage horizon        : {TARGET_COVERAGE_DAYS} days")
print(
    f"Reorder quantity multiplier    : "
    f"{REORDER_QUANTITY_MULTIPLIER:.1f}x"
)

Inventory Simulation Assumptions
------------------------------------------------
Inventory SKU population       : 300
Base demand coverage           : 7 days
Safety-stock coverage          : 3 days
Replenishment lead time        : 5 days
Target coverage horizon        : 15 days
Reorder quantity multiplier    : 2.0x

In [105]:
# ============================================================
# Validate Inventory Simulation Assumptions
# ============================================================

# Confirm that the day-based assumptions use integer values.
integer_assumptions_are_valid = all(
    isinstance(value, int)
    for value in [
        INVENTORY_SAMPLE_SIZE,
        DEMAND_COVERAGE_DAYS,
        SAFETY_STOCK_DAYS,
        LEAD_TIME_DAYS,
        TARGET_COVERAGE_DAYS
    ]
)

# Confirm that the multiplier is numeric.
multiplier_is_numeric = isinstance(
    REORDER_QUANTITY_MULTIPLIER,
    (int, float)
)

# Apply simulation-assumption validation rules.
assert integer_assumptions_are_valid, (
    "One or more integer simulation assumptions "
    "contain an invalid data type."
)

assert multiplier_is_numeric, (
    "The reorder quantity multiplier must be numeric."
)

assert INVENTORY_SAMPLE_SIZE > 0, (
    "The inventory SKU population must be greater than zero."
)

assert DEMAND_COVERAGE_DAYS > 0, (
    "Demand coverage must be greater than zero days."
)

assert SAFETY_STOCK_DAYS >= 0, (
    "Safety-stock coverage cannot be negative."
)

assert LEAD_TIME_DAYS > 0, (
    "Replenishment lead time must be greater than zero."
)

assert REORDER_QUANTITY_MULTIPLIER >= 1, (
    "The reorder quantity multiplier must be at least 1.0."
)

assert TARGET_COVERAGE_DAYS == (
    DEMAND_COVERAGE_DAYS
    + SAFETY_STOCK_DAYS
    + LEAD_TIME_DAYS
), (
    "The target coverage horizon was calculated incorrectly."
)

assert TARGET_COVERAGE_DAYS > DEMAND_COVERAGE_DAYS, (
    "The target coverage horizon must exceed "
    "the base demand-coverage period."
)

# Display results only after every assertion passes.
print("✅ Inventory simulation assumptions validated successfully.")
print(f"Inventory SKU population      : {INVENTORY_SAMPLE_SIZE:,}")
print(f"Demand coverage days          : {DEMAND_COVERAGE_DAYS}")
print(f"Safety-stock days             : {SAFETY_STOCK_DAYS}")
print(f"Lead-time days                : {LEAD_TIME_DAYS}")
print(f"Target coverage days          : {TARGET_COVERAGE_DAYS}")
print(
    f"Reorder quantity multiplier   : "
    f"{REORDER_QUANTITY_MULTIPLIER:.1f}x"
)

✅ Inventory simulation assumptions validated successfully.
Inventory SKU population      : 300
Demand coverage days          : 7
Safety-stock days             : 3
Lead-time days                : 5
Target coverage days          : 15
Reorder quantity multiplier   : 2.0x

#### ✅ Validation Result

The inventory-simulation assumptions were defined and validated successfully.

Validation confirmed that:

- The simulation scope contains 300 development SKUs.
- Base demand coverage was configured at seven days.
- Safety-stock coverage was configured at three additional days.
- Replenishment lead time was configured at five days.
- The complete target-stock horizon equals 15 days of demand coverage.
- The replenishment-quantity multiplier was configured at 2.0 times the target-stock level.
- All parameters contain valid data types and satisfy the required logical constraints.

These parameters are documented analytical assumptions rather than observed retailer inventory policies. The validated configuration is ready for selection of the inventory-simulation SKU population.

### 🔗 11.4.2 Select Simulation SKU Population

This step matches the 300 canonical SKUs retained in Sales Daily with their validated SKU Master records.

The resulting population provides the product hierarchy and estimated cost attributes required for inventory simulation while preserving complete and unique SKU coverage.

In [106]:
# ============================================================
# Select Inventory Simulation SKU Population
# ============================================================

# Define the SKU Master fields required
# for the inventory-engineering workflow.
inventory_sample_columns = [
    "sku_id",
    "item_id",
    "category",
    "department",
    "store_id",
    "state_id",
    "estimated_unit_cost"
]

# Confirm that Sales Daily contains its canonical identifier.
assert "sku_id" in sales_daily_final.columns, (
    "The Sales Daily dataset does not contain sku_id."
)

# Identify required SKU Master fields that are unavailable.
missing_inventory_master_columns = [
    column
    for column in inventory_sample_columns
    if column not in sku_master_final.columns
]

assert len(missing_inventory_master_columns) == 0, (
    f"Required SKU Master inventory fields are missing: "
    f"{missing_inventory_master_columns}."
)

# Extract the complete canonical SKU population
# retained in the engineered Sales Daily dataset.
inventory_sales_skus = (
    sales_daily_final["sku_id"]
    .astype("string")
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
)

# Select the corresponding validated records
# directly from the final SKU Master dataset.
inventory_sample = (
    sku_master_final.loc[
        sku_master_final["sku_id"]
        .astype("string")
        .isin(inventory_sales_skus),
        inventory_sample_columns
    ]
    .sort_values("sku_id")
    .reset_index(drop=True)
    .copy()
)

print("✅ Inventory simulation SKU population selected successfully.")
print(f"Available Sales Daily SKUs : {len(inventory_sales_skus):,}")
print(f"Matched SKU Master records : {len(inventory_sample):,}")

✅ Inventory simulation SKU population selected successfully.
Available Sales Daily SKUs : 300
Matched SKU Master records : 300

In [107]:
# ============================================================
# Preview Inventory Simulation SKU Population
# ============================================================

# Display representative SKU reference records
# selected for inventory simulation.
display(
    inventory_sample.head(10)
)

             sku_id      item_id category department store_id state_id  estimated_unit_cost
0  FOODS_1_001_CA_1  FOODS_1_001    FOODS    FOODS_1     CA_1       CA                 1.57
1  FOODS_1_001_CA_2  FOODS_1_001    FOODS    FOODS_1     CA_2       CA                 1.57
2  FOODS_1_001_CA_3  FOODS_1_001    FOODS    FOODS_1     CA_3       CA                 1.57
3  FOODS_1_001_CA_4  FOODS_1_001    FOODS    FOODS_1     CA_4       CA                 1.57
4  FOODS_1_001_TX_1  FOODS_1_001    FOODS    FOODS_1     TX_1       TX                 1.57
5  FOODS_1_001_TX_2  FOODS_1_001    FOODS    FOODS_1     TX_2       TX                 1.57
6  FOODS_1_001_TX_3  FOODS_1_001    FOODS    FOODS_1     TX_3       TX                 1.57
7  FOODS_1_001_WI_1  FOODS_1_001    FOODS    FOODS_1     WI_1       WI                 1.57
8  FOODS_1_001_WI_2  FOODS_1_001    FOODS    FOODS_1     WI_2       WI                 1.57
9  FOODS_1_001_WI_3  FOODS_1_001    FOODS    FOODS_1     WI_3       WI                 1.57

In [108]:
# ============================================================
# Validate Inventory Simulation SKU Population
# ============================================================

# Create the expected and selected canonical SKU sets.
expected_inventory_sku_set = set(
    inventory_sales_skus.astype("string")
)

selected_inventory_sku_set = set(
    inventory_sample["sku_id"].astype("string")
)

master_sku_set = set(
    sku_master_final["sku_id"].astype("string")
)

# Count duplicate selected SKU identifiers.
duplicate_inventory_skus = (
    inventory_sample["sku_id"]
    .duplicated()
    .sum()
)

# Count missing values in required inventory attributes.
missing_inventory_values = (
    inventory_sample
    .isna()
    .sum()
    .sum()
)

# Identify Sales Daily SKUs unavailable in the SKU Master.
sales_skus_missing_from_master = (
    expected_inventory_sku_set
    - master_sku_set
)

# Identify expected SKUs missing from the selected population.
missing_selected_skus = (
    expected_inventory_sku_set
    - selected_inventory_sku_set
)

# Identify records selected beyond the Sales Daily population.
extra_selected_skus = (
    selected_inventory_sku_set
    - expected_inventory_sku_set
)

# Reconstruct the expected canonical identifiers
# for the selected item-store combinations.
expected_sample_sku_ids = (
    inventory_sample["item_id"].astype("string")
    + "_"
    + inventory_sample["store_id"].astype("string")
)

# Count invalid canonical identifiers.
invalid_inventory_sku_ids = (
    inventory_sample["sku_id"].astype("string")
    != expected_sample_sku_ids
).sum()

# Count non-positive estimated costs.
non_positive_estimated_costs = (
    inventory_sample["estimated_unit_cost"] <= 0
).sum()

# Apply population validation rules.
assert len(expected_inventory_sku_set) == INVENTORY_SAMPLE_SIZE, (
    f"Unexpected Sales Daily SKU population: "
    f"{len(expected_inventory_sku_set)}. "
    f"Expected: {INVENTORY_SAMPLE_SIZE}."
)

assert len(inventory_sample) == INVENTORY_SAMPLE_SIZE, (
    f"Unexpected selected inventory population: "
    f"{len(inventory_sample)}."
)

assert duplicate_inventory_skus == 0, (
    f"Duplicate selected SKU identifiers detected: "
    f"{duplicate_inventory_skus}."
)

assert missing_inventory_values == 0, (
    f"Missing selected inventory values detected: "
    f"{missing_inventory_values}."
)

assert len(sales_skus_missing_from_master) == 0, (
    f"Sales Daily SKUs missing from the SKU Master: "
    f"{sorted(sales_skus_missing_from_master)}."
)

assert len(missing_selected_skus) == 0, (
    f"Expected inventory SKUs were not selected: "
    f"{sorted(missing_selected_skus)}."
)

assert len(extra_selected_skus) == 0, (
    f"Unexpected inventory SKUs were selected: "
    f"{sorted(extra_selected_skus)}."
)

assert invalid_inventory_sku_ids == 0, (
    f"Invalid canonical inventory SKU identifiers detected: "
    f"{invalid_inventory_sku_ids}."
)

assert non_positive_estimated_costs == 0, (
    f"Non-positive estimated unit costs detected: "
    f"{non_positive_estimated_costs}."
)

# Display results only after all checks pass.
print("✅ Inventory simulation SKU population validated successfully.")
print(f"Expected SKUs              : {INVENTORY_SAMPLE_SIZE:,}")
print(f"Selected SKUs              : {len(inventory_sample):,}")
print(f"Duplicate SKUs             : {duplicate_inventory_skus:,}")
print(f"Missing values             : {missing_inventory_values:,}")
print(f"SKUs missing from Master   : {len(sales_skus_missing_from_master):,}")
print(f"Missing selected SKUs      : {len(missing_selected_skus):,}")
print(f"Extra selected SKUs        : {len(extra_selected_skus):,}")
print(f"Invalid canonical IDs      : {invalid_inventory_sku_ids:,}")
print(f"Non-positive cost estimates: {non_positive_estimated_costs:,}")

✅ Inventory simulation SKU population validated successfully.
Expected SKUs              : 300
Selected SKUs              : 300
Duplicate SKUs             : 0
Missing values             : 0
SKUs missing from Master   : 0
Missing selected SKUs      : 0
Extra selected SKUs        : 0
Invalid canonical IDs      : 0
Non-positive cost estimates: 0

#### ✅ Validation Result

The inventory-simulation SKU population was selected and validated successfully.

Validation confirmed that:

- All 300 canonical SKUs retained in Sales Daily were represented.
- Every Sales Daily SKU was matched directly to its validated SKU Master record.
- No random resampling or temporary identifier reconstruction was required.
- No missing, duplicate, unmatched, or unexpected SKU records were detected.
- All selected identifiers follow the canonical Project FORESIGHT item-store convention.
- Product hierarchy, store, state, and estimated unit-cost attributes are complete.
- All estimated unit-cost values are positive.
- The selected SKU set exactly matches the complete Sales Daily development population.

The validated SKU population is ready for construction of the daily inventory working dataset.

## 🔗 11.4.3 Create Daily Inventory Working Dataset

The daily inventory working dataset combines historical demand for the selected SKUs with the estimated cost information required for inventory simulation.

This step will extract daily SKU demand, integrate estimated unit costs, arrange records chronologically, and validate complete SKU-date coverage.

The completed dataset will provide the input for demand-policy engineering and sequential inventory simulation.

In [109]:
# ============================================================
# Create Daily Inventory Working Dataset
# ============================================================

required_sales_columns = [
    "date",
    "sku_id",
    "units_sold",
    "unit_price"
]

required_inventory_columns = [
    "sku_id",
    "estimated_unit_cost"
]

missing_sales_columns = [
    column
    for column in required_sales_columns
    if column not in sales_daily_final.columns
]

missing_inventory_columns = [
    column
    for column in required_inventory_columns
    if column not in inventory_sample.columns
]

assert len(missing_sales_columns) == 0, (
    f"Required Sales Daily fields are missing: "
    f"{missing_sales_columns}."
)

assert len(missing_inventory_columns) == 0, (
    f"Required inventory sample fields are missing: "
    f"{missing_inventory_columns}."
)

# Extract daily demand records for the selected SKUs.
inventory_working = (
    sales_daily_final.loc[
        sales_daily_final["sku_id"].isin(
            inventory_sample["sku_id"]
        ),
        required_sales_columns
    ]
    .copy()
)

# Integrate the estimated SKU-level unit cost.
inventory_working = (
    inventory_working
    .merge(
        inventory_sample[
            required_inventory_columns
        ],
        on="sku_id",
        how="left",
        validate="many_to_one"
    )
    .sort_values(
        [
            "sku_id",
            "date"
        ]
    )
    .reset_index(drop=True)
)

print("✅ Daily inventory working dataset created successfully.")
print(f"Dataset shape : {inventory_working.shape}")
print(
    f"Unique SKUs  : "
    f"{inventory_working['sku_id'].nunique():,}"
)
print(
    f"Date range   : "
    f"{inventory_working['date'].min().date()} to "
    f"{inventory_working['date'].max().date()}"
)

✅ Daily inventory working dataset created successfully.
Dataset shape : (573900, 5)
Unique SKUs  : 300
Date range   : 2011-01-29 to 2016-04-24

In [110]:
# ============================================================
# Validate Daily Inventory Working Dataset
# ============================================================

expected_inventory_columns = [
    "date",
    "sku_id",
    "units_sold",
    "unit_price",
    "estimated_unit_cost"
]

expected_inventory_skus = len(
    inventory_sample["sku_id"].drop_duplicates()
)

expected_inventory_dates = (
    sales_daily_final["date"].nunique()
)

expected_inventory_rows = (
    expected_inventory_skus
    * expected_inventory_dates
)

actual_inventory_rows = len(inventory_working)

unique_inventory_skus = (
    inventory_working["sku_id"].nunique()
)

unique_inventory_dates = (
    inventory_working["date"].nunique()
)

missing_inventory_working_values = (
    inventory_working.isna().sum().sum()
)

duplicate_inventory_records = (
    inventory_working[
        ["sku_id", "date"]
    ]
    .duplicated()
    .sum()
)

# Count SKUs without complete date coverage.
sku_date_counts = (
    inventory_working
    .groupby("sku_id")["date"]
    .nunique()
)

incomplete_sku_histories = (
    sku_date_counts
    != expected_inventory_dates
).sum()

invalid_inventory_skus = (
    ~inventory_working["sku_id"].isin(
        inventory_sample["sku_id"]
    )
).sum()

dates_are_valid = (
    pd.api.types.is_datetime64_any_dtype(
        inventory_working["date"]
    )
)

records_are_sorted = (
    inventory_working[
        ["sku_id", "date"]
    ]
    .equals(
        inventory_working[
            ["sku_id", "date"]
        ]
        .sort_values(
            ["sku_id", "date"]
        )
        .reset_index(drop=True)
    )
)

negative_units_sold = (
    inventory_working["units_sold"] < 0
).sum()

negative_unit_prices = (
    inventory_working["unit_price"] < 0
).sum()

non_positive_estimated_costs = (
    inventory_working["estimated_unit_cost"] <= 0
).sum()

assert inventory_working.columns.tolist() == (
    expected_inventory_columns
)

assert actual_inventory_rows == expected_inventory_rows
assert unique_inventory_skus == expected_inventory_skus
assert unique_inventory_dates == expected_inventory_dates
assert missing_inventory_working_values == 0
assert duplicate_inventory_records == 0
assert incomplete_sku_histories == 0
assert invalid_inventory_skus == 0
assert dates_are_valid
assert records_are_sorted
assert negative_units_sold == 0
assert negative_unit_prices == 0
assert non_positive_estimated_costs == 0

print("✅ Daily inventory working dataset validated successfully.")
print(f"Expected records       : {expected_inventory_rows:,}")
print(f"Actual records         : {actual_inventory_rows:,}")
print(f"Unique SKUs            : {unique_inventory_skus:,}")
print(f"Unique dates           : {unique_inventory_dates:,}")
print(f"Missing values         : {missing_inventory_working_values:,}")
print(f"Duplicate SKU-dates    : {duplicate_inventory_records:,}")
print(f"Incomplete histories   : {incomplete_sku_histories:,}")
print(f"Invalid selected SKUs  : {invalid_inventory_skus:,}")
print(f"Chronological order    : Passed")

✅ Daily inventory working dataset validated successfully.
Expected records       : 573,900
Actual records         : 573,900
Unique SKUs            : 300
Unique dates           : 1,913
Missing values         : 0
Duplicate SKU-dates    : 0
Incomplete histories   : 0
Invalid selected SKUs  : 0
Chronological order    : Passed

#### ✅ Validation Result

The daily inventory working dataset was created and validated successfully.

All 300 selected SKUs retained complete chronological demand histories, with no missing values, duplicate SKU-date records, unmatched identifiers, or invalid demand and cost values.

The dataset is ready for demand and replenishment parameter engineering.

### 🛠️ 11.4.4 Engineer Inventory Parameters

SKU-level inventory parameters will be estimated from historical average daily demand and the validated simulation assumptions.

This step will calculate reorder points, target stock levels, and fixed replenishment quantities for each simulated SKU.

The validated parameters will guide the sequential inventory simulation.

In [111]:
# ============================================================
# Engineer Demand and Replenishment Parameters
# ============================================================

# Calculate historical average daily demand by SKU.
demand_parameters = (
    inventory_working
    .groupby(
        "sku_id",
        as_index=False
    )
    .agg(
        average_daily_demand=(
            "units_sold",
            "mean"
        )
    )
    .sort_values("sku_id")
    .reset_index(drop=True)
)

# Assign the fixed replenishment lead time.
demand_parameters["lead_time_days"] = (
    LEAD_TIME_DAYS
)

# Reorder point:
# lead-time demand plus safety-stock demand.
demand_parameters["reorder_point"] = (
    np.ceil(
        demand_parameters["average_daily_demand"]
        * (
            LEAD_TIME_DAYS
            + SAFETY_STOCK_DAYS
        )
    )
    .astype("Int32")
    .clip(lower=1)
)

# Target stock:
# demand coverage, lead time and safety stock.
demand_parameters["target_stock"] = (
    np.ceil(
        demand_parameters["average_daily_demand"]
        * TARGET_COVERAGE_DAYS
    )
    .astype("Int32")
    .clip(lower=1)
)

# Fixed replenishment quantity using the
# documented bulk-order multiplier.
demand_parameters["reorder_quantity"] = (
    np.ceil(
        demand_parameters["target_stock"]
        * REORDER_QUANTITY_MULTIPLIER
    )
    .astype("Int32")
    .clip(lower=1)
)

print("✅ Demand and replenishment parameters engineered successfully.")
print(f"Total SKUs : {len(demand_parameters):,}")

✅ Demand and replenishment parameters engineered successfully.
Total SKUs : 300

In [112]:
# ============================================================
# Preview Demand and Replenishment Parameters
# ============================================================

display(
    demand_parameters.head(10)
)

             sku_id  average_daily_demand  lead_time_days  reorder_point  target_stock  reorder_quantity
0  FOODS_1_001_CA_1                  0.79               5              7            12                24
1  FOODS_1_001_CA_2                  1.16               5             10            18                36
2  FOODS_1_001_CA_3                  1.20               5             10            19                38
3  FOODS_1_001_CA_4                  0.36               5              3             6                12
4  FOODS_1_001_TX_1                  0.58               5              5             9                18
5  FOODS_1_001_TX_2                  0.58               5              5             9                18
6  FOODS_1_001_TX_3                  0.41               5              4             7                14
7  FOODS_1_001_WI_1                  0.57               5              5             9                18
8  FOODS_1_001_WI_2                  0.46               5              4             7                14
9  FOODS_1_001_WI_3                  0.29               5              3             5                10

In [113]:
# ============================================================
# Validate Demand and Replenishment Parameters
# ============================================================

expected_parameter_columns = [
    "sku_id",
    "average_daily_demand",
    "lead_time_days",
    "reorder_point",
    "target_stock",
    "reorder_quantity"
]

actual_parameter_skus = (
    demand_parameters["sku_id"].nunique()
)

missing_parameter_values = (
    demand_parameters.isna().sum().sum()
)

duplicate_parameter_skus = (
    demand_parameters["sku_id"]
    .duplicated()
    .sum()
)

non_positive_average_demand = (
    demand_parameters["average_daily_demand"] <= 0
).sum()

# Recalculate expected values.
expected_reorder_points = (
    np.ceil(
        demand_parameters["average_daily_demand"]
        * (
            LEAD_TIME_DAYS
            + SAFETY_STOCK_DAYS
        )
    )
    .astype("Int32")
    .clip(lower=1)
)

expected_target_stock = (
    np.ceil(
        demand_parameters["average_daily_demand"]
        * TARGET_COVERAGE_DAYS
    )
    .astype("Int32")
    .clip(lower=1)
)

expected_reorder_quantities = (
    np.ceil(
        expected_target_stock
        * REORDER_QUANTITY_MULTIPLIER
    )
    .astype("Int32")
    .clip(lower=1)
)

incorrect_reorder_points = (
    demand_parameters["reorder_point"]
    != expected_reorder_points
).sum()

incorrect_target_stock = (
    demand_parameters["target_stock"]
    != expected_target_stock
).sum()

incorrect_reorder_quantities = (
    demand_parameters["reorder_quantity"]
    != expected_reorder_quantities
).sum()

invalid_stock_relationships = (
    demand_parameters["target_stock"]
    < demand_parameters["reorder_point"]
).sum()

invalid_reorder_quantities = (
    demand_parameters["reorder_quantity"]
    < demand_parameters["target_stock"]
).sum()

invalid_lead_times = (
    demand_parameters["lead_time_days"]
    != LEAD_TIME_DAYS
).sum()

assert demand_parameters.columns.tolist() == (
    expected_parameter_columns
)

assert actual_parameter_skus == INVENTORY_SAMPLE_SIZE
assert duplicate_parameter_skus == 0
assert missing_parameter_values == 0
assert non_positive_average_demand == 0
assert incorrect_reorder_points == 0
assert incorrect_target_stock == 0
assert incorrect_reorder_quantities == 0
assert invalid_stock_relationships == 0
assert invalid_reorder_quantities == 0
assert invalid_lead_times == 0

print("✅ Demand and replenishment parameters validated successfully.")
print(f"Expected SKUs              : {INVENTORY_SAMPLE_SIZE:,}")
print(f"Actual SKUs                : {actual_parameter_skus:,}")
print(f"Missing values             : {missing_parameter_values:,}")
print(f"Duplicate SKUs             : {duplicate_parameter_skus:,}")
print(f"Incorrect reorder points   : {incorrect_reorder_points:,}")
print(f"Incorrect target stocks    : {incorrect_target_stock:,}")
print(f"Incorrect reorder quantity : {incorrect_reorder_quantities:,}")
print(
    f"Average demand range       : "
    f"{demand_parameters['average_daily_demand'].min():.2f} - "
    f"{demand_parameters['average_daily_demand'].max():.2f}"
)
print(
    f"Reorder point range        : "
    f"{demand_parameters['reorder_point'].min():,} - "
    f"{demand_parameters['reorder_point'].max():,}"
)
print(
    f"Target stock range         : "
    f"{demand_parameters['target_stock'].min():,} - "
    f"{demand_parameters['target_stock'].max():,}"
)
print(
    f"Reorder quantity range     : "
    f"{demand_parameters['reorder_quantity'].min():,} - "
    f"{demand_parameters['reorder_quantity'].max():,}"
)

✅ Demand and replenishment parameters validated successfully.
Expected SKUs              : 300
Actual SKUs                : 300
Missing values             : 0
Duplicate SKUs             : 0
Incorrect reorder points   : 0
Incorrect target stocks    : 0
Incorrect reorder quantity : 0
Average demand range       : 0.01 - 9.78
Reorder point range        : 1 - 79
Target stock range         : 1 - 147
Reorder quantity range     : 2 - 294

#### ✅ Validation Result

Demand and replenishment parameters were engineered and validated successfully for all 300 SKUs.

All records were complete and unique, and the reorder points, target stock levels, and replenishment quantities matched the documented simulation policy.

The parameters are ready for daily inventory movement simulation.

## 🔄 11.4.5 Simulate Daily Inventory Movements

Daily inventory movements will be simulated chronologically for each SKU using historical demand and the engineered replenishment parameters.

Stock receipts will be processed before demand, while new orders will be placed after evaluating the closing inventory position. Only one replenishment order may remain outstanding for a SKU at a time.

The completed simulation will provide one inventory-movement record for every SKU-date combination.

In [114]:
# ============================================================
# Simulate Daily Inventory Movements
# ============================================================

# Add SKU-level inventory parameters.
inventory_simulation_base = (
    inventory_working
    .merge(
        demand_parameters[
            [
                "sku_id",
                "lead_time_days",
                "reorder_point",
                "target_stock",
                "reorder_quantity"
            ]
        ],
        on="sku_id",
        how="left",
        validate="many_to_one"
    )
    .sort_values(
        ["sku_id", "date"]
    )
    .reset_index(drop=True)
)

# Confirm that all parameters were matched.
missing_simulation_parameters = (
    inventory_simulation_base[
        [
            "lead_time_days",
            "reorder_point",
            "target_stock",
            "reorder_quantity"
        ]
    ]
    .isna()
    .sum()
    .sum()
)

assert missing_simulation_parameters == 0, (
    f"Missing inventory parameters detected: "
    f"{missing_simulation_parameters}."
)

simulation_results = []

# Simulate each SKU independently.
for sku_id, sku_data in inventory_simulation_base.groupby(
    "sku_id",
    sort=False
):
    sku_data = (
        sku_data
        .sort_values("date")
        .reset_index(drop=True)
        .copy()
    )

    lead_time_days = int(
        sku_data["lead_time_days"].iloc[0]
    )

    reorder_point = int(
        sku_data["reorder_point"].iloc[0]
    )

    target_stock = int(
        sku_data["target_stock"].iloc[0]
    )

    reorder_quantity = int(
        sku_data["reorder_quantity"].iloc[0]
    )

    # Initialize inventory at the target-stock level.
    current_stock = target_stock

    # arrival_position: ordered quantity
    pending_orders = {}

    opening_stock_values = []
    fulfilled_units_values = []
    lost_sales_values = []
    received_stock_values = []
    closing_stock_values = []
    order_placed_values = []
    on_order_values = []

    for day_position, daily_demand in enumerate(
        sku_data["units_sold"].to_numpy()
    ):
        daily_demand = int(daily_demand)

        # Previous closing stock becomes today's opening stock.
        opening_stock = current_stock

        # Receive orders scheduled for the current day.
        received_stock = pending_orders.pop(
            day_position,
            0
        )

        available_stock = (
            opening_stock
            + received_stock
        )

        # Fulfil demand using available stock.
        fulfilled_units = min(
            daily_demand,
            available_stock
        )

        lost_sales_units = (
            daily_demand
            - fulfilled_units
        )

        closing_stock = (
            available_stock
            - fulfilled_units
        )

        # Inventory already ordered but not yet received.
        outstanding_order_units = sum(
            pending_orders.values()
        )

        inventory_position = (
            closing_stock
            + outstanding_order_units
        )

        order_placed_units = 0

        # Place an order only when no order is outstanding.
        if (
            inventory_position <= reorder_point
            and outstanding_order_units == 0
        ):
            arrival_position = (
                day_position
                + lead_time_days
            )

            order_placed_units = reorder_quantity

            pending_orders[arrival_position] = (
                order_placed_units
            )

        outstanding_order_units = sum(
            pending_orders.values()
        )

        opening_stock_values.append(opening_stock)
        fulfilled_units_values.append(fulfilled_units)
        lost_sales_values.append(lost_sales_units)
        received_stock_values.append(received_stock)
        closing_stock_values.append(closing_stock)
        order_placed_values.append(order_placed_units)
        on_order_values.append(outstanding_order_units)

        current_stock = closing_stock

    sku_data["opening_stock"] = opening_stock_values
    sku_data["fulfilled_units"] = fulfilled_units_values
    sku_data["lost_sales_units"] = lost_sales_values
    sku_data["received_stock"] = received_stock_values
    sku_data["closing_stock"] = closing_stock_values
    sku_data["order_placed_units"] = order_placed_values
    sku_data["on_order_units"] = on_order_values

    simulation_results.append(sku_data)

# Combine all SKU simulations.
inventory_movements = (
    pd.concat(
        simulation_results,
        ignore_index=True
    )
    .sort_values(
        ["sku_id", "date"]
    )
    .reset_index(drop=True)
)

print("✅ Daily inventory movements simulated successfully.")
print(f"Dataset shape  : {inventory_movements.shape}")
print(
    f"Unique SKUs   : "
    f"{inventory_movements['sku_id'].nunique():,}"
)
print(
    f"Total demand  : "
    f"{inventory_movements['units_sold'].sum():,}"
)
print(
    f"Units fulfilled: "
    f"{inventory_movements['fulfilled_units'].sum():,}"
)
print(
    f"Lost sales    : "
    f"{inventory_movements['lost_sales_units'].sum():,}"
)

✅ Daily inventory movements simulated successfully.
Dataset shape  : (573900, 16)
Unique SKUs   : 300
Total demand  : 573,932
Units fulfilled: 549,943
Lost sales    : 23,989

In [115]:
# ============================================================
# Preview Daily Inventory Movements
# ============================================================

display(
    inventory_movements[
        [
            "date",
            "sku_id",
            "opening_stock",
            "units_sold",
            "fulfilled_units",
            "lost_sales_units",
            "received_stock",
            "closing_stock",
            "order_placed_units",
            "on_order_units",
            "reorder_point",
            "reorder_quantity"
        ]
    ].head(10)
)

,date,sku_id,opening_stock,units_sold,fulfilled_units,lost_sales_units,received_stock,closing_stock,order_placed_units,on_order_units,reorder_point,reorder_quantity
0,2011-01-29,FOODS_1_001_CA_1,12,3,3,0,0,9,0,0,7,24
1,2011-01-30,FOODS_1_001_CA_1,9,0,0,0,0,9,0,0,7,24
2,2011-01-31,FOODS_1_001_CA_1,9,0,0,0,0,9,0,0,7,24
3,2011-02-01,FOODS_1_001_CA_1,9,1,1,0,0,8,0,0,7,24
4,2011-02-02,FOODS_1_001_CA_1,8,4,4,0,0,4,24,24,7,24
5,2011-02-03,FOODS_1_001_CA_1,4,2,2,0,0,2,0,24,7,24
6,2011-02-04,FOODS_1_001_CA_1,2,0,0,0,0,2,0,24,7,24
7,2011-02-05,FOODS_1_001_CA_1,2,2,2,0,0,0,0,24,7,24
8,2011-02-06,FOODS_1_001_CA_1,0,0,0,0,0,0,0,24,7,24
9,2011-02-07,FOODS_1_001_CA_1,0,0,0,0,24,24,0,0,7,24

In [116]:
# ============================================================
# Validate Daily Inventory Movements
# ============================================================

expected_movement_columns = [
    "date",
    "sku_id",
    "units_sold",
    "unit_price",
    "estimated_unit_cost",
    "lead_time_days",
    "reorder_point",
    "target_stock",
    "reorder_quantity",
    "opening_stock",
    "fulfilled_units",
    "lost_sales_units",
    "received_stock",
    "closing_stock",
    "order_placed_units",
    "on_order_units"
]

expected_movement_rows = len(
    inventory_simulation_base
)

actual_movement_rows = len(
    inventory_movements
)

unique_movement_skus = (
    inventory_movements["sku_id"].nunique()
)

missing_movement_values = (
    inventory_movements.isna().sum().sum()
)

duplicate_movement_records = (
    inventory_movements[
        ["sku_id", "date"]
    ]
    .duplicated()
    .sum()
)

movement_records_sorted = (
    pd.MultiIndex.from_frame(
        inventory_movements[
            ["sku_id", "date"]
        ]
    )
    .is_monotonic_increasing
)

# Inventory and demand balances.
invalid_inventory_balances = (
    inventory_movements["closing_stock"]
    != (
        inventory_movements["opening_stock"]
        + inventory_movements["received_stock"]
        - inventory_movements["fulfilled_units"]
    )
).sum()

invalid_demand_balances = (
    inventory_movements["units_sold"]
    != (
        inventory_movements["fulfilled_units"]
        + inventory_movements["lost_sales_units"]
    )
).sum()

# Opening-stock continuity.
previous_closing_stock = (
    inventory_movements
    .groupby("sku_id")["closing_stock"]
    .shift(1)
)

non_initial_records = previous_closing_stock.notna()

invalid_opening_continuity = (
    inventory_movements.loc[
        non_initial_records,
        "opening_stock"
    ].to_numpy()
    != previous_closing_stock.loc[
        non_initial_records
    ].to_numpy()
).sum()

# Initial stock must equal target stock.
initial_inventory_records = (
    inventory_movements
    .groupby("sku_id")
    .head(1)
)

invalid_initial_stock = (
    initial_inventory_records["opening_stock"]
    != initial_inventory_records["target_stock"]
).sum()

# Validate replenishment receipt timing.
expected_received_stock = (
    inventory_movements
    .groupby("sku_id")["order_placed_units"]
    .shift(
        LEAD_TIME_DAYS,
        fill_value=0
    )
)

invalid_receipt_timing = (
    inventory_movements["received_stock"]
    != expected_received_stock
).sum()

# Validate outstanding-order movement.
previous_on_order = (
    inventory_movements
    .groupby("sku_id")["on_order_units"]
    .shift(
        1,
        fill_value=0
    )
)

expected_on_order = (
    previous_on_order
    - inventory_movements["received_stock"]
    + inventory_movements["order_placed_units"]
)

invalid_on_order_balances = (
    inventory_movements["on_order_units"]
    != expected_on_order
).sum()

# Validate order-placement policy.
pre_order_outstanding = (
    previous_on_order
    - inventory_movements["received_stock"]
)

pre_order_inventory_position = (
    inventory_movements["closing_stock"]
    + pre_order_outstanding
)

expected_order_placed = np.where(
    (
        pre_order_inventory_position
        <= inventory_movements["reorder_point"]
    )
    &
    (
        pre_order_outstanding == 0
    ),
    inventory_movements["reorder_quantity"],
    0
)

invalid_order_placements = (
    inventory_movements["order_placed_units"]
    != expected_order_placed
).sum()

negative_inventory_measures = (
    inventory_movements[
        [
            "opening_stock",
            "fulfilled_units",
            "lost_sales_units",
            "received_stock",
            "closing_stock",
            "order_placed_units",
            "on_order_units"
        ]
    ] < 0
).sum().sum()

fulfilled_above_demand = (
    inventory_movements["fulfilled_units"]
    > inventory_movements["units_sold"]
).sum()

# Apply validation rules.
assert inventory_movements.columns.tolist() == (
    expected_movement_columns
)

assert actual_movement_rows == expected_movement_rows
assert unique_movement_skus == INVENTORY_SAMPLE_SIZE
assert missing_movement_values == 0
assert duplicate_movement_records == 0
assert movement_records_sorted
assert invalid_inventory_balances == 0
assert invalid_demand_balances == 0
assert invalid_opening_continuity == 0
assert invalid_initial_stock == 0
assert invalid_receipt_timing == 0
assert invalid_on_order_balances == 0
assert invalid_order_placements == 0
assert negative_inventory_measures == 0
assert fulfilled_above_demand == 0

print("✅ Daily inventory movements validated successfully.")
print(f"Expected records          : {expected_movement_rows:,}")
print(f"Actual records            : {actual_movement_rows:,}")
print(f"Unique SKUs               : {unique_movement_skus:,}")
print(f"Missing values            : {missing_movement_values:,}")
print(f"Duplicate SKU-dates       : {duplicate_movement_records:,}")
print(f"Inventory balance errors  : {invalid_inventory_balances:,}")
print(f"Demand balance errors     : {invalid_demand_balances:,}")
print(f"Continuity errors         : {invalid_opening_continuity:,}")
print(f"Receipt timing errors     : {invalid_receipt_timing:,}")
print(f"Order placement errors    : {invalid_order_placements:,}")

✅ Daily inventory movements validated successfully.
Expected records          : 573,900
Actual records            : 573,900
Unique SKUs               : 300
Missing values            : 0
Duplicate SKU-dates       : 0
Inventory balance errors  : 0
Demand balance errors     : 0
Continuity errors         : 0
Receipt timing errors     : 0
Order placement errors    : 0

#### ✅ Validation Result

Daily inventory movements were simulated and validated successfully for all 300 SKUs.

Inventory balances, demand fulfilment, stock continuity, order placement, receipt timing, and non-negativity checks all passed. The simulated movements are ready for inventory-status and business-metric engineering.

## 🛠️ 11.4.6 Engineer Inventory Metrics

The simulated inventory movements will be enriched with inventory-status, estimated inventory-value, and days-of-supply metrics.

These fields will support inventory-health monitoring and downstream reporting.

In [117]:
# ============================================================
# Engineer Inventory Status and Business Metrics
# ============================================================

OVERSTOCK_THRESHOLD_MULTIPLIER = 1.50

# Add historical average daily demand.
inventory_final = (
    inventory_movements
    .merge(
        demand_parameters[
            [
                "sku_id",
                "average_daily_demand"
            ]
        ],
        on="sku_id",
        how="left",
        validate="many_to_one"
    )
    .copy()
)

# Confirm valid demand values before calculating supply coverage.
missing_average_demand = (
    inventory_final["average_daily_demand"]
    .isna()
    .sum()
)

non_positive_average_demand = (
    inventory_final["average_daily_demand"] <= 0
).sum()

assert missing_average_demand == 0
assert non_positive_average_demand == 0

# Calculate estimated closing-inventory value.
inventory_final["estimated_inventory_value"] = (
    inventory_final["closing_stock"]
    * inventory_final["estimated_unit_cost"]
).round(2)

# Calculate days of supply.
inventory_final["days_of_supply"] = (
    inventory_final["closing_stock"]
    / inventory_final["average_daily_demand"]
).round(1)

# Classify inventory status.
inventory_final["inventory_status"] = pd.Series(
    np.select(
        [
            (
                inventory_final["closing_stock"] == 0
            ).to_numpy(),

            (
                inventory_final["closing_stock"]
                <= inventory_final["reorder_point"]
            ).to_numpy(),

            (
                inventory_final["closing_stock"]
                >= (
                    inventory_final["target_stock"]
                    * OVERSTOCK_THRESHOLD_MULTIPLIER
                )
            ).to_numpy()
        ],
        [
            "Stockout",
            "Low Stock",
            "Overstock"
        ],
        default="Healthy"
    ),
    index=inventory_final.index,
    dtype="string"
)

print("✅ Inventory status and business metrics engineered successfully.")
print(f"Dataset shape      : {inventory_final.shape}")
print(
    f"Inventory statuses : "
    f"{inventory_final['inventory_status'].nunique()}"
)

✅ Inventory status and business metrics engineered successfully.
Dataset shape      : (573900, 20)
Inventory statuses : 4

In [118]:
# ============================================================
# Preview Inventory Business Metrics
# ============================================================

display(
    inventory_final[
        [
            "date",
            "sku_id",
            "closing_stock",
            "average_daily_demand",
            "inventory_status",
            "estimated_inventory_value",
            "days_of_supply"
        ]
    ].head(10)
)

,date,sku_id,closing_stock,average_daily_demand,inventory_status,estimated_inventory_value,days_of_supply
0,2011-01-29,FOODS_1_001_CA_1,9,0.79,Healthy,14.13,11.50
1,2011-01-30,FOODS_1_001_CA_1,9,0.79,Healthy,14.13,11.50
2,2011-01-31,FOODS_1_001_CA_1,9,0.79,Healthy,14.13,11.50
3,2011-02-01,FOODS_1_001_CA_1,8,0.79,Healthy,12.56,10.20
4,2011-02-02,FOODS_1_001_CA_1,4,0.79,Low Stock,6.28,5.10
5,2011-02-03,FOODS_1_001_CA_1,2,0.79,Low Stock,3.14,2.50
6,2011-02-04,FOODS_1_001_CA_1,2,0.79,Low Stock,3.14,2.50
7,2011-02-05,FOODS_1_001_CA_1,0,0.79,Stockout,0.00,0.00
8,2011-02-06,FOODS_1_001_CA_1,0,0.79,Stockout,0.00,0.00
9,2011-02-07,FOODS_1_001_CA_1,24,0.79,Overstock,37.68,30.50

In [119]:
# ============================================================
# Validate Inventory Status and Business Metrics
# ============================================================

expected_metric_rows = len(
    inventory_movements
)

actual_metric_rows = len(
    inventory_final
)

unique_metric_skus = (
    inventory_final["sku_id"].nunique()
)

missing_metric_values = (
    inventory_final.isna().sum().sum()
)

duplicate_metric_records = (
    inventory_final[
        ["sku_id", "date"]
    ]
    .duplicated()
    .sum()
)

allowed_inventory_statuses = {
    "Healthy",
    "Low Stock",
    "Overstock",
    "Stockout"
}

invalid_inventory_statuses = (
    ~inventory_final["inventory_status"]
    .isin(allowed_inventory_statuses)
).sum()

# Validate estimated inventory value.
expected_inventory_value = (
    inventory_final["closing_stock"]
    * inventory_final["estimated_unit_cost"]
).round(2)

invalid_inventory_value_calculations = (
    ~np.isclose(
        inventory_final["estimated_inventory_value"],
        expected_inventory_value,
        atol=0.01
    )
).sum()

# Validate days of supply.
expected_days_of_supply = (
    inventory_final["closing_stock"]
    / inventory_final["average_daily_demand"]
).round(1)

invalid_days_of_supply = (
    ~np.isclose(
        inventory_final["days_of_supply"],
        expected_days_of_supply,
        atol=0.01
    )
).sum()

# Recalculate expected status independently.
expected_inventory_status = pd.Series(
    np.select(
        [
            (
                inventory_final["closing_stock"] == 0
            ).to_numpy(),

            (
                inventory_final["closing_stock"]
                <= inventory_final["reorder_point"]
            ).to_numpy(),

            (
                inventory_final["closing_stock"]
                >= (
                    inventory_final["target_stock"]
                    * OVERSTOCK_THRESHOLD_MULTIPLIER
                )
            ).to_numpy()
        ],
        [
            "Stockout",
            "Low Stock",
            "Overstock"
        ],
        default="Healthy"
    ),
    index=inventory_final.index,
    dtype="string"
)

incorrect_inventory_statuses = (
    inventory_final["inventory_status"]
    != expected_inventory_status
).sum()

negative_inventory_values = (
    inventory_final["estimated_inventory_value"] < 0
).sum()

negative_days_of_supply = (
    inventory_final["days_of_supply"] < 0
).sum()

non_finite_days_of_supply = (
    ~np.isfinite(
        inventory_final["days_of_supply"]
    )
).sum()

status_distribution = (
    inventory_final["inventory_status"]
    .value_counts()
    .reindex(
        [
            "Healthy",
            "Low Stock",
            "Overstock",
            "Stockout"
        ],
        fill_value=0
    )
)

status_distribution_complete = (
    status_distribution.sum()
    == len(inventory_final)
)

assert actual_metric_rows == expected_metric_rows
assert unique_metric_skus == INVENTORY_SAMPLE_SIZE
assert missing_metric_values == 0
assert duplicate_metric_records == 0
assert invalid_inventory_statuses == 0
assert incorrect_inventory_statuses == 0
assert invalid_inventory_value_calculations == 0
assert invalid_days_of_supply == 0
assert negative_inventory_values == 0
assert negative_days_of_supply == 0
assert non_finite_days_of_supply == 0
assert status_distribution_complete

print("✅ Inventory status and business metrics validated successfully.")
print(f"Expected records           : {expected_metric_rows:,}")
print(f"Actual records             : {actual_metric_rows:,}")
print(f"Unique SKUs                : {unique_metric_skus:,}")
print(f"Missing values             : {missing_metric_values:,}")
print(f"Duplicate SKU-dates        : {duplicate_metric_records:,}")
print(f"Invalid status values      : {invalid_inventory_statuses:,}")
print(f"Incorrect classifications  : {incorrect_inventory_statuses:,}")
print(f"Inventory value errors     : {invalid_inventory_value_calculations:,}")
print(f"Days-of-supply errors      : {invalid_days_of_supply:,}")

print("\nInventory Status Distribution:")
print(status_distribution)

✅ Inventory status and business metrics validated successfully.
Expected records           : 573,900
Actual records             : 573,900
Unique SKUs                : 300
Missing values             : 0
Duplicate SKU-dates        : 0
Invalid status values      : 0
Incorrect classifications  : 0
Inventory value errors     : 0
Days-of-supply errors      : 0

Inventory Status Distribution:
inventory_status
Healthy      267673
Low Stock     67528
Overstock    223381
Stockout      15318
Name: count, dtype: int64[pyarrow]

#### ✅ Validation Result

Inventory status and business metrics were engineered and validated successfully.

All records retained valid status classifications, estimated inventory values, and days-of-supply calculations, with no missing values, duplicate SKU-date records, or calculation errors.

The completed simulation dataset is ready for final preparation and export.

## 📋 11.4.7 Prepare Final Inventory Dataset

The completed inventory simulation dataset will be arranged into its final analytical structure.

This step will retain the required movement, replenishment, inventory-status, and business-metric fields before final validation and export.

In [120]:
# ============================================================
# Prepare Final Inventory Snapshot Dataset
# ============================================================

# Define the final business-ready column order.
final_inventory_columns = [
    "date",
    "sku_id",
    "opening_stock",
    "units_sold",
    "fulfilled_units",
    "lost_sales_units",
    "received_stock",
    "order_placed_units",
    "closing_stock",
    "reorder_point",
    "reorder_quantity",
    "on_order_units",
    "lead_time_days",
    "target_stock",
    "inventory_status",
    "estimated_inventory_value",
    "days_of_supply"
]

# Identify unavailable final fields.
missing_final_inventory_columns = [
    column
    for column in final_inventory_columns
    if column not in inventory_final.columns
]

assert len(missing_final_inventory_columns) == 0, (
    f"Required final inventory fields are missing: "
    f"{missing_final_inventory_columns}."
)

# Preserve the source row count.
inventory_final_input_rows = len(inventory_final)

# Select and arrange the final fields.
inventory_snapshots_final = (
    inventory_final[
        final_inventory_columns
    ]
    .sort_values(
        [
            "sku_id",
            "date"
        ]
    )
    .reset_index(drop=True)
    .copy()
)

# Confirm row preservation during preparation.
assert len(inventory_snapshots_final) == (
    inventory_final_input_rows
), (
    "Final inventory preparation changed the row count."
)

print("✅ Final inventory snapshot dataset prepared successfully.")
print(f"Dataset shape  : {inventory_snapshots_final.shape}")
print(
    f"Unique SKUs   : "
    f"{inventory_snapshots_final['sku_id'].nunique():,}"
)
print(
    f"Date range    : "
    f"{inventory_snapshots_final['date'].min().date()} to "
    f"{inventory_snapshots_final['date'].max().date()}"
)
print(f"Rows preserved: {len(inventory_snapshots_final) == inventory_final_input_rows}")

✅ Final inventory snapshot dataset prepared successfully.
Dataset shape  : (573900, 17)
Unique SKUs   : 300
Date range    : 2011-01-29 to 2016-04-24
Rows preserved: True

In [121]:
# ============================================================
# Preview Final Inventory Snapshot Dataset
# ============================================================

display(
    inventory_snapshots_final.head(10)
)

,date,sku_id,opening_stock,units_sold,fulfilled_units,lost_sales_units,received_stock,order_placed_units,closing_stock,reorder_point,reorder_quantity,on_order_units,lead_time_days,target_stock,inventory_status,estimated_inventory_value,days_of_supply
0,2011-01-29,FOODS_1_001_CA_1,12,3,3,0,0,0,9,7,24,0,5,12,Healthy,14.13,11.50
1,2011-01-30,FOODS_1_001_CA_1,9,0,0,0,0,0,9,7,24,0,5,12,Healthy,14.13,11.50
2,2011-01-31,FOODS_1_001_CA_1,9,0,0,0,0,0,9,7,24,0,5,12,Healthy,14.13,11.50
3,2011-02-01,FOODS_1_001_CA_1,9,1,1,0,0,0,8,7,24,0,5,12,Healthy,12.56,10.20
4,2011-02-02,FOODS_1_001_CA_1,8,4,4,0,0,24,4,7,24,24,5,12,Low Stock,6.28,5.10
5,2011-02-03,FOODS_1_001_CA_1,4,2,2,0,0,0,2,7,24,24,5,12,Low Stock,3.14,2.50
6,2011-02-04,FOODS_1_001_CA_1,2,0,0,0,0,0,2,7,24,24,5,12,Low Stock,3.14,2.50
7,2011-02-05,FOODS_1_001_CA_1,2,2,2,0,0,0,0,7,24,24,5,12,Stockout,0.00,0.00
8,2011-02-06,FOODS_1_001_CA_1,0,0,0,0,0,0,0,7,24,24,5,12,Stockout,0.00,0.00
9,2011-02-07,FOODS_1_001_CA_1,0,0,0,0,24,0,24,7,24,0,5,12,Overstock,37.68,30.50

#### 📋 Preparation Summary

The final Inventory Snapshot dataset was prepared successfully.

All 573,900 simulated SKU-date records were retained in a consistent 17-column structure. The dataset is ready for final validation and export.

## 📤 11.4.8 Validate and Export Inventory Snapshots

The final Inventory Snapshot dataset will undergo structural and business-rule validation before export.

The exported CSV will then be reloaded and compared with the validated in-memory dataset to confirm successful preservation.

In [122]:
# ============================================================
# Validate Final Inventory Snapshot Dataset
# ============================================================

allowed_inventory_statuses = {
    "Healthy",
    "Low Stock",
    "Overstock",
    "Stockout"
}

expected_inventory_rows = (
    inventory_sample["sku_id"].nunique()
    * inventory_working["date"].nunique()
)

final_inventory_rows, final_inventory_column_count = (
    inventory_snapshots_final.shape
)

unique_final_inventory_skus = (
    inventory_snapshots_final["sku_id"].nunique()
)

unique_final_inventory_dates = (
    inventory_snapshots_final["date"].nunique()
)

missing_final_inventory_values = (
    inventory_snapshots_final
    .isna()
    .sum()
    .sum()
)

duplicate_final_inventory_records = (
    inventory_snapshots_final[
        [
            "sku_id",
            "date"
        ]
    ]
    .duplicated()
    .sum()
)

final_inventory_structure_valid = (
    inventory_snapshots_final.columns.tolist()
    == final_inventory_columns
)

final_inventory_dates_valid = (
    pd.api.types.is_datetime64_any_dtype(
        inventory_snapshots_final["date"]
    )
)

final_inventory_records_sorted = (
    pd.MultiIndex.from_frame(
        inventory_snapshots_final[
            [
                "sku_id",
                "date"
            ]
        ]
    )
    .is_monotonic_increasing
)

# Validate inventory balance.
invalid_final_inventory_balances = (
    inventory_snapshots_final["closing_stock"]
    != (
        inventory_snapshots_final["opening_stock"]
        + inventory_snapshots_final["received_stock"]
        - inventory_snapshots_final["fulfilled_units"]
    )
).sum()

# Validate demand fulfilment.
invalid_final_demand_balances = (
    inventory_snapshots_final["units_sold"]
    != (
        inventory_snapshots_final["fulfilled_units"]
        + inventory_snapshots_final["lost_sales_units"]
    )
).sum()

# Validate permitted status categories.
invalid_final_inventory_statuses = (
    ~inventory_snapshots_final["inventory_status"]
    .isin(allowed_inventory_statuses)
).sum()

# Validate replenishment quantities.
invalid_final_order_quantities = (
    ~(
        (
            inventory_snapshots_final["order_placed_units"] == 0
        )
        |
        (
            inventory_snapshots_final["order_placed_units"]
            == inventory_snapshots_final["reorder_quantity"]
        )
    )
).sum()

# Validate non-negative analytical fields.
non_negative_final_columns = [
    "opening_stock",
    "units_sold",
    "fulfilled_units",
    "lost_sales_units",
    "received_stock",
    "order_placed_units",
    "closing_stock",
    "reorder_point",
    "reorder_quantity",
    "on_order_units",
    "lead_time_days",
    "target_stock",
    "estimated_inventory_value",
    "days_of_supply"
]

negative_final_inventory_values = (
    inventory_snapshots_final[
        non_negative_final_columns
    ] < 0
).sum().sum()

# Apply validation rules.
assert final_inventory_structure_valid, (
    "The final Inventory Snapshot schema is incorrect."
)

assert final_inventory_rows == expected_inventory_rows, (
    f"Unexpected final row count: {final_inventory_rows}."
)

assert final_inventory_column_count == len(
    final_inventory_columns
), (
    f"Unexpected final column count: "
    f"{final_inventory_column_count}."
)

assert unique_final_inventory_skus == INVENTORY_SAMPLE_SIZE
assert unique_final_inventory_dates == inventory_working["date"].nunique()
assert missing_final_inventory_values == 0
assert duplicate_final_inventory_records == 0
assert final_inventory_dates_valid
assert final_inventory_records_sorted
assert invalid_final_inventory_balances == 0
assert invalid_final_demand_balances == 0
assert invalid_final_inventory_statuses == 0
assert invalid_final_order_quantities == 0
assert negative_final_inventory_values == 0

print("✅ Final inventory snapshot dataset validated successfully.")
print(f"Rows                       : {final_inventory_rows:,}")
print(f"Columns                    : {final_inventory_column_count}")
print(f"Unique SKUs                : {unique_final_inventory_skus:,}")
print(f"Unique dates               : {unique_final_inventory_dates:,}")
print(f"Missing values             : {missing_final_inventory_values:,}")
print(f"Duplicate SKU-dates        : {duplicate_final_inventory_records:,}")
print(f"Inventory balance errors   : {invalid_final_inventory_balances:,}")
print(f"Demand balance errors      : {invalid_final_demand_balances:,}")
print(f"Invalid status values      : {invalid_final_inventory_statuses:,}")
print(f"Invalid order quantities   : {invalid_final_order_quantities:,}")
print(f"Negative analytical values : {negative_final_inventory_values:,}")

✅ Final inventory snapshot dataset validated successfully.
Rows                       : 573,900
Columns                    : 17
Unique SKUs                : 300
Unique dates               : 1,913
Missing values             : 0
Duplicate SKU-dates        : 0
Inventory balance errors   : 0
Demand balance errors      : 0
Invalid status values      : 0
Invalid order quantities   : 0
Negative analytical values : 0

In [123]:
# ============================================================
# Export and Verify Final Inventory Snapshot Dataset
# ============================================================

# Ensure the processed-data directory exists.
PROCESSED_DATA_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# Define the official export path.
inventory_snapshot_path = (
    PROCESSED_DATA_DIR
    / "inventory_snapshots_final.csv"
)

# Export the validated dataset.
inventory_snapshots_final.to_csv(
    inventory_snapshot_path,
    index=False
)

# Confirm that a non-empty file was created.
assert inventory_snapshot_path.exists(), (
    "The inventory snapshot export file was not created."
)

assert inventory_snapshot_path.stat().st_size > 0, (
    "The inventory snapshot export file is empty."
)

# Reload the exported dataset.
inventory_snapshot_export = pd.read_csv(
    inventory_snapshot_path,
    parse_dates=["date"]
)

# Calculate exported-file validation metrics.
exported_inventory_rows = len(
    inventory_snapshot_export
)

exported_inventory_columns_match = (
    inventory_snapshot_export.columns.tolist()
    == final_inventory_columns
)

exported_missing_values = (
    inventory_snapshot_export
    .isna()
    .sum()
    .sum()
)

exported_duplicate_records = (
    inventory_snapshot_export[
        [
            "sku_id",
            "date"
        ]
    ]
    .duplicated()
    .sum()
)

exported_unique_skus = (
    inventory_snapshot_export["sku_id"].nunique()
)

exported_inventory_balance_errors = (
    inventory_snapshot_export["closing_stock"]
    != (
        inventory_snapshot_export["opening_stock"]
        + inventory_snapshot_export["received_stock"]
        - inventory_snapshot_export["fulfilled_units"]
    )
).sum()

exported_demand_balance_errors = (
    inventory_snapshot_export["units_sold"]
    != (
        inventory_snapshot_export["fulfilled_units"]
        + inventory_snapshot_export["lost_sales_units"]
    )
).sum()

# Compare the complete exported content with the source dataset.
pd.testing.assert_frame_equal(
    inventory_snapshot_export.reset_index(drop=True),
    inventory_snapshots_final.reset_index(drop=True),
    check_dtype=False,
    check_exact=False,
    rtol=1e-10,
    atol=1e-10
)

assert exported_inventory_rows == final_inventory_rows
assert exported_inventory_columns_match
assert exported_unique_skus == INVENTORY_SAMPLE_SIZE
assert exported_missing_values == 0
assert exported_duplicate_records == 0
assert exported_inventory_balance_errors == 0
assert exported_demand_balance_errors == 0

print("✅ Inventory snapshot dataset exported and verified successfully.")
print(f"Export file           : {inventory_snapshot_path.name}")
print(f"Exported rows         : {exported_inventory_rows:,}")
print(f"Exported columns      : {inventory_snapshot_export.shape[1]}")
print(f"Unique SKUs           : {exported_unique_skus:,}")
print(f"Missing values        : {exported_missing_values:,}")
print(f"Duplicate SKU-dates   : {exported_duplicate_records:,}")
print(f"Inventory errors      : {exported_inventory_balance_errors:,}")
print(f"Demand errors         : {exported_demand_balance_errors:,}")
print(
    f"File size             : "
    f"{inventory_snapshot_path.stat().st_size:,} bytes"
)
print(f"Export location       : {inventory_snapshot_path}")

✅ Inventory snapshot dataset exported and verified successfully.
Export file           : inventory_snapshots_final.csv
Exported rows         : 573,900
Exported columns      : 17
Unique SKUs           : 300
Missing values        : 0
Duplicate SKU-dates   : 0
Inventory errors      : 0
Demand errors         : 0
File size             : 44,351,238 bytes
Export location       : C:\Users\hp\Project FORESIGHT\data\processed\inventory_snapshots_final.csv

In [124]:
# ============================================================
# Preview Exported Inventory Snapshot Dataset
# ============================================================

display(
    inventory_snapshot_export.head(10)
)

,date,sku_id,opening_stock,units_sold,fulfilled_units,lost_sales_units,received_stock,order_placed_units,closing_stock,reorder_point,reorder_quantity,on_order_units,lead_time_days,target_stock,inventory_status,estimated_inventory_value,days_of_supply
0,2011-01-29,FOODS_1_001_CA_1,12,3,3,0,0,0,9,7,24,0,5,12,Healthy,14.13,11.50
1,2011-01-30,FOODS_1_001_CA_1,9,0,0,0,0,0,9,7,24,0,5,12,Healthy,14.13,11.50
2,2011-01-31,FOODS_1_001_CA_1,9,0,0,0,0,0,9,7,24,0,5,12,Healthy,14.13,11.50
3,2011-02-01,FOODS_1_001_CA_1,9,1,1,0,0,0,8,7,24,0,5,12,Healthy,12.56,10.20
4,2011-02-02,FOODS_1_001_CA_1,8,4,4,0,0,24,4,7,24,24,5,12,Low Stock,6.28,5.10
5,2011-02-03,FOODS_1_001_CA_1,4,2,2,0,0,0,2,7,24,24,5,12,Low Stock,3.14,2.50
6,2011-02-04,FOODS_1_001_CA_1,2,0,0,0,0,0,2,7,24,24,5,12,Low Stock,3.14,2.50
7,2011-02-05,FOODS_1_001_CA_1,2,2,2,0,0,0,0,7,24,24,5,12,Stockout,0.00,0.00
8,2011-02-06,FOODS_1_001_CA_1,0,0,0,0,0,0,0,7,24,24,5,12,Stockout,0.00,0.00
9,2011-02-07,FOODS_1_001_CA_1,0,0,0,0,24,0,24,7,24,0,5,12,Overstock,37.68,30.50

#### ✅ Validation Result

The Inventory Snapshot dataset passed all final validation and export-verification checks.

All simulated SKU-date records, inventory balances, demand balances, status values, and replenishment fields were preserved successfully in `inventory_snapshots_final.csv`.

The exported dataset is ready for downstream Project FORESIGHT workflows.

# ✅ 12. Final Dataset Validation

This section performs notebook-level validation across all engineered and exported datasets.

It verifies dataset availability, schema integrity, key uniqueness, cross-dataset consistency, and readiness for downstream Project FORESIGHT notebooks.

## ✅ 12.1 Validate Dataset Availability

This step confirms that all four engineered datasets exist as non-empty DataFrames before notebook-level validation begins.

In [125]:
# ============================================================
# Validate Engineered Dataset Availability
# ============================================================

# Define the required in-memory datasets.
dataset_registry = {
    "Sales Daily Dataset": "sales_daily_final",
    "Calendar Dataset": "calendar_final",
    "SKU Master Dataset": "sku_master_final",
    "Inventory Snapshot Dataset": "inventory_snapshots_final"
}

engineered_datasets = {}
availability_records = []

for dataset_name, variable_name in dataset_registry.items():

    variable_exists = variable_name in globals()
    dataset = globals().get(variable_name)

    is_dataframe = isinstance(dataset, pd.DataFrame)
    contains_records = (
        is_dataframe
        and not dataset.empty
    )

    assert variable_exists, (
        f"{variable_name} is not available."
    )

    assert is_dataframe, (
        f"{variable_name} is not a pandas DataFrame."
    )

    assert contains_records, (
        f"{variable_name} contains no records."
    )

    engineered_datasets[dataset_name] = dataset

    availability_records.append({
        "Dataset": dataset_name,
        "Rows": dataset.shape[0],
        "Columns": dataset.shape[1],
        "Status": "Passed"
    })

availability_summary = pd.DataFrame(
    availability_records
)

print("✅ Engineered dataset availability validated successfully.\n")

display(
    availability_summary
)

✅ Engineered dataset availability validated successfully.

                      Dataset    Rows  Columns  Status
0         Sales Daily Dataset  573900        6  Passed
1            Calendar Dataset    1969       22  Passed
2          SKU Master Dataset   30490       16  Passed
3  Inventory Snapshot Dataset  573900       17  Passed

#### ✅ Validation Result

All four engineered datasets are available as non-empty DataFrames.

The notebook is ready for structural validation.

## ✅ 12.2 Validate Dataset Structure

This step verifies the exact schema, expected dimensions, and completeness of required fields across all engineered datasets.

In [126]:
# ============================================================
# Validate Engineered Dataset Structure
# ============================================================

expected_dataset_structure = {
    "Sales Daily Dataset": {
        "rows": 573900,
        "columns": [
            "date",
            "sku_id",
            "units_sold",
            "revenue",
            "unit_price",
            "promo_flag"
        ],
        "nullable_columns": []
    },

    "Calendar Dataset": {
        "rows": 1969,
        "columns": [
            "date",
            "d",
            "wm_yr_wk",
            "year",
            "quarter",
            "month",
            "month_name",
            "week_of_year",
            "day",
            "day_name",
            "day_of_week",
            "is_weekend",
            "season",
            "event_name_1",
            "event_type_1",
            "event_name_2",
            "event_type_2",
            "event_flag",
            "snap_CA",
            "snap_TX",
            "snap_WI",
            "snap_flag"
        ],
        "nullable_columns": [
            "event_name_1",
            "event_type_1",
            "event_name_2",
            "event_type_2"
        ]
    },

    "SKU Master Dataset": {
        "rows": 30490,
        "columns": [
            "sku_id",
            "item_id",
            "category",
            "department",
            "store_id",
            "state_id",
            "launch_date",
            "first_sale_date",
            "last_sale_date",
            "sku_age_days",
            "days_since_last_sale",
            "avg_price",
            "max_observed_price",
            "estimated_unit_cost",
            "estimated_gross_margin",
            "sku_status"
        ],
        "nullable_columns": []
    },

    "Inventory Snapshot Dataset": {
        "rows": 573900,
        "columns": [
            "date",
            "sku_id",
            "opening_stock",
            "units_sold",
            "fulfilled_units",
            "lost_sales_units",
            "received_stock",
            "order_placed_units",
            "closing_stock",
            "reorder_point",
            "reorder_quantity",
            "on_order_units",
            "lead_time_days",
            "target_stock",
            "inventory_status",
            "estimated_inventory_value",
            "days_of_supply"
        ],
        "nullable_columns": []
    }
}

structure_records = []

for dataset_name, expectations in (
    expected_dataset_structure.items()
):

    dataset = engineered_datasets[dataset_name]
    expected_columns = expectations["columns"]
    expected_rows = expectations["rows"]
    nullable_columns = expectations["nullable_columns"]

    required_columns = [
        column
        for column in expected_columns
        if column not in nullable_columns
    ]

    actual_rows, actual_column_count = dataset.shape

    row_count_match = (
        actual_rows == expected_rows
    )

    schema_match = (
        dataset.columns.tolist()
        == expected_columns
    )

    unexpected_missing_values = (
        dataset[required_columns]
        .isna()
        .sum()
        .sum()
    )

    structure_passed = all([
        row_count_match,
        schema_match,
        unexpected_missing_values == 0
    ])

    structure_records.append({
        "Dataset": dataset_name,
        "Expected Rows": expected_rows,
        "Actual Rows": actual_rows,
        "Expected Columns": len(expected_columns),
        "Actual Columns": actual_column_count,
        "Unexpected Missing": unexpected_missing_values,
        "Status": (
            "Passed"
            if structure_passed
            else "Failed"
        )
    })

    assert row_count_match, (
        f"{dataset_name} has {actual_rows:,} rows; "
        f"expected {expected_rows:,}."
    )

    assert schema_match, (
        f"{dataset_name} does not match "
        "the expected schema."
    )

    assert unexpected_missing_values == 0, (
        f"{dataset_name} contains "
        f"{unexpected_missing_values:,} unexpected "
        "missing values."
    )

structure_summary = pd.DataFrame(
    structure_records
)

print("✅ Engineered dataset structures validated successfully.\n")

display(
    structure_summary
)

✅ Engineered dataset structures validated successfully.

,Dataset,Expected Rows,Actual Rows,Expected Columns,Actual Columns,Unexpected Missing,Status
0,Sales Daily Dataset,573900,573900,6,6,0,Passed
1,Calendar Dataset,1969,1969,22,22,0,Passed
2,SKU Master Dataset,30490,30490,16,16,0,Passed
3,Inventory Snapshot Dataset,573900,573900,17,17,0,Passed

#### ✅ Validation Result

All datasets matched their required dimensions and exact schemas.

No unexpected missing values were detected in required fields.

## ✅ 12.3 Validate Cross-Dataset Consistency

This step verifies Calendar coverage, SKU Master coverage, shared SKU-date keys, and demand consistency between Sales Daily and Inventory Snapshot.

Successful validation confirms that the engineered datasets form a consistent analytical data model.

In [127]:
# ============================================================
# Validate Cross-Dataset Consistency
# ============================================================

# ------------------------------------------------------------
# Prepare Normalized References
# ------------------------------------------------------------

calendar_date_reference = (
    pd.to_datetime(calendar_final["date"])
    .dt.normalize()
)

sku_master_reference = (
    sku_master_final["sku_id"]
    .astype("string")
)

sales_reference = (
    sales_daily_final[
        [
            "sku_id",
            "date",
            "units_sold"
        ]
    ]
    .copy()
)

sales_reference["sku_id"] = (
    sales_reference["sku_id"]
    .astype("string")
)

sales_reference["date"] = (
    pd.to_datetime(sales_reference["date"])
    .dt.normalize()
)

inventory_reference = (
    inventory_snapshots_final[
        [
            "sku_id",
            "date",
            "units_sold"
        ]
    ]
    .copy()
)

inventory_reference["sku_id"] = (
    inventory_reference["sku_id"]
    .astype("string")
)

inventory_reference["date"] = (
    pd.to_datetime(inventory_reference["date"])
    .dt.normalize()
)


# ------------------------------------------------------------
# Validate Key Uniqueness
# ------------------------------------------------------------

calendar_key_unique = (
    calendar_date_reference
    .duplicated()
    .sum()
    == 0
)

sku_master_key_unique = (
    sku_master_reference
    .duplicated()
    .sum()
    == 0
)

sales_key_unique = (
    sales_reference[
        [
            "sku_id",
            "date"
        ]
    ]
    .duplicated()
    .sum()
    == 0
)

inventory_key_unique = (
    inventory_reference[
        [
            "sku_id",
            "date"
        ]
    ]
    .duplicated()
    .sum()
    == 0
)


# ------------------------------------------------------------
# Validate Date Coverage
# ------------------------------------------------------------

calendar_dates = set(
    calendar_date_reference
)

sales_dates = set(
    sales_reference["date"]
)

inventory_dates = set(
    inventory_reference["date"]
)

sales_calendar_coverage = (
    sales_dates.issubset(calendar_dates)
)

inventory_calendar_coverage = (
    inventory_dates.issubset(calendar_dates)
)

sales_inventory_date_alignment = (
    sales_dates == inventory_dates
)


# ------------------------------------------------------------
# Validate SKU Coverage
# ------------------------------------------------------------

sku_master_skus = set(
    sku_master_reference
)

sales_skus = set(
    sales_reference["sku_id"]
)

inventory_skus = set(
    inventory_reference["sku_id"]
)

sales_inventory_sku_alignment = (
    sales_skus == inventory_skus
)

sales_sku_master_coverage = (
    sales_skus.issubset(
        sku_master_skus
    )
)

inventory_sku_master_coverage = (
    inventory_skus.issubset(
        sku_master_skus
    )
)


# ------------------------------------------------------------
# Validate Shared SKU-Date Business Keys
# ------------------------------------------------------------

sales_keys = (
    sales_reference[
        [
            "sku_id",
            "date"
        ]
    ]
    .drop_duplicates()
)

inventory_keys = (
    inventory_reference[
        [
            "sku_id",
            "date"
        ]
    ]
    .drop_duplicates()
)

key_comparison = (
    sales_keys
    .merge(
        inventory_keys,
        on=[
            "sku_id",
            "date"
        ],
        how="outer",
        indicator=True
    )
)

sales_only_keys = (
    key_comparison["_merge"]
    .eq("left_only")
    .sum()
)

inventory_only_keys = (
    key_comparison["_merge"]
    .eq("right_only")
    .sum()
)

business_key_alignment = (
    sales_only_keys == 0
    and inventory_only_keys == 0
    and len(sales_keys) == len(inventory_keys)
)


# ------------------------------------------------------------
# Validate Historical Demand Preservation
# ------------------------------------------------------------

demand_comparison = (
    sales_reference
    .merge(
        inventory_reference,
        on=[
            "sku_id",
            "date"
        ],
        how="inner",
        suffixes=(
            "_sales",
            "_inventory"
        )
    )
)

demand_value_mismatches = (
    demand_comparison["units_sold_sales"]
    != demand_comparison["units_sold_inventory"]
).sum()

units_sold_alignment = (
    business_key_alignment
    and len(demand_comparison) == len(sales_reference)
    and demand_value_mismatches == 0
)


# ------------------------------------------------------------
# Create Validation Summary
# ------------------------------------------------------------

cross_dataset_checks = {
    "Calendar date key is unique":
        calendar_key_unique,

    "SKU Master key is unique":
        sku_master_key_unique,

    "Sales SKU-date key is unique":
        sales_key_unique,

    "Inventory SKU-date key is unique":
        inventory_key_unique,

    "Sales dates covered by Calendar":
        sales_calendar_coverage,

    "Inventory dates covered by Calendar":
        inventory_calendar_coverage,

    "Sales and Inventory dates align":
        sales_inventory_date_alignment,

    "Sales and Inventory SKUs align":
        sales_inventory_sku_alignment,

    "Sales SKUs covered by SKU Master":
        sales_sku_master_coverage,

    "Inventory SKUs covered by SKU Master":
        inventory_sku_master_coverage,

    "Sales and Inventory keys align":
        business_key_alignment,

    "Sales demand preserved in Inventory":
        units_sold_alignment
}

cross_dataset_summary = pd.DataFrame({
    "Validation Check": list(
        cross_dataset_checks.keys()
    ),
    "Status": [
        "Passed" if result else "Failed"
        for result in cross_dataset_checks.values()
    ]
})

failed_cross_dataset_checks = [
    check_name
    for check_name, result
    in cross_dataset_checks.items()
    if not result
]


# ------------------------------------------------------------
# Display Results
# ------------------------------------------------------------

print("Cross-Dataset Consistency Diagnostics")
print("-" * 48)
print(f"Sales-only SKU-date keys     : {sales_only_keys:,}")
print(f"Inventory-only SKU-date keys : {inventory_only_keys:,}")
print(f"Demand value mismatches      : {demand_value_mismatches:,}")

print("\nCross-Dataset Validation Summary\n")

display(
    cross_dataset_summary
)

assert len(failed_cross_dataset_checks) == 0, (
    f"Cross-dataset validation failed: "
    f"{failed_cross_dataset_checks}."
)

print("✅ Cross-dataset consistency validated successfully.")

Cross-Dataset Consistency Diagnostics
------------------------------------------------
Sales-only SKU-date keys     : 0
Inventory-only SKU-date keys : 0
Demand value mismatches      : 0

Cross-Dataset Validation Summary

                        Validation Check  Status
0            Calendar date key is unique  Passed
1               SKU Master key is unique  Passed
2           Sales SKU-date key is unique  Passed
3       Inventory SKU-date key is unique  Passed
4        Sales dates covered by Calendar  Passed
5    Inventory dates covered by Calendar  Passed
6        Sales and Inventory dates align  Passed
7         Sales and Inventory SKUs align  Passed
8       Sales SKUs covered by SKU Master  Passed
9   Inventory SKUs covered by SKU Master  Passed
10        Sales and Inventory keys align  Passed
11   Sales demand preserved in Inventory  Passed

✅ Cross-dataset consistency validated successfully.

#### ✅ Validation Result

Calendar coverage, SKU Master coverage, shared SKU-date keys, and historical demand values were fully aligned.

The engineered datasets form a consistent analytical data model.

## ✅ 12.4 Validation Summary

This step summarizes the completed notebook-level validation stages and confirms readiness for downstream use.

In [128]:
# ============================================================
# Display Final Validation Summary
# ============================================================

availability_stage_passed = (
    availability_summary["Status"]
    .eq("Passed")
    .all()
)

structure_stage_passed = (
    structure_summary["Status"]
    .eq("Passed")
    .all()
)

cross_dataset_stage_passed = (
    cross_dataset_summary["Status"]
    .eq("Passed")
    .all()
)

validation_summary = pd.DataFrame({
    "Validation Stage": [
        "Dataset Availability",
        "Dataset Structure",
        "Cross-Dataset Consistency"
    ],
    "Status": [
        (
            "Passed"
            if availability_stage_passed
            else "Failed"
        ),
        (
            "Passed"
            if structure_stage_passed
            else "Failed"
        ),
        (
            "Passed"
            if cross_dataset_stage_passed
            else "Failed"
        )
    ]
})

failed_validation_stages = (
    validation_summary.loc[
        validation_summary["Status"] == "Failed",
        "Validation Stage"
    ]
    .tolist()
)

print("Final Validation Summary\n")

display(
    validation_summary
)

assert len(failed_validation_stages) == 0, (
    f"Final validation stages failed: "
    f"{failed_validation_stages}."
)

print("✅ All notebook-level validation checks passed.")
print(
    "Engineered datasets are ready for "
    "downstream Project FORESIGHT workflows."
)

Final Validation Summary

            Validation Stage  Status
0       Dataset Availability  Passed
1          Dataset Structure  Passed
2  Cross-Dataset Consistency  Passed

✅ All notebook-level validation checks passed.
Engineered datasets are ready for downstream Project FORESIGHT workflows.

#### ✅ Validation Result

Dataset availability, structural integrity, and cross-dataset consistency were validated successfully.

Notebook 01 has produced a complete and internally consistent analytical data foundation.

# 📦 13. Final Dataset Deliverables

The validated datasets were exported during their respective engineering workflows.

This section will register the final CSV deliverables, verify their availability and structure, and summarize the outputs produced by Notebook 01.

## 📋 13.1 Register Final Dataset Deliverables

This step defines the final dataset names, validated in-memory sources, export locations, and date fields required for verification.

In [129]:
# ============================================================
# Register Final Dataset Deliverables
# ============================================================

# Ensure that the processed-data directory exists.
PROCESSED_DATA_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# Register the final Notebook 01 deliverables.
final_dataset_deliverables = {
    "Sales Daily Dataset": {
        "file_name": "sales_daily_final.csv",
        "dataset": sales_daily_final,
        "parse_dates": ["date"]
    },

    "Calendar Dataset": {
        "file_name": "calendar_final.csv",
        "dataset": calendar_final,
        "parse_dates": ["date"]
    },

    "SKU Master Dataset": {
        "file_name": "sku_master_final.csv",
        "dataset": sku_master_final,
        "parse_dates": [
            "launch_date",
            "first_sale_date",
            "last_sale_date"
        ]
    },

    "Inventory Snapshot Dataset": {
        "file_name": "inventory_snapshots_final.csv",
        "dataset": inventory_snapshots_final,
        "parse_dates": ["date"]
    }
}

# Add the complete export path for each dataset.
for details in final_dataset_deliverables.values():

    details["file_path"] = (
        PROCESSED_DATA_DIR
        / details["file_name"]
    )

print("✅ Final dataset deliverables registered successfully.")
print(f"Deliverables registered : {len(final_dataset_deliverables)}")
print(f"Output directory        : {PROCESSED_DATA_DIR.resolve()}")

✅ Final dataset deliverables registered successfully.
Deliverables registered : 4
Output directory        : C:\Users\hp\Project FORESIGHT\data\processed

#### 📋 Preparation Summary

Four final dataset deliverables were registered successfully with their validated in-memory sources and expected export locations.

The files are ready for centralized verification.

## ✅ 13.2 Verify Exported Files

This step verifies that every final CSV exists, contains data, and preserves the expected dimensions and schema.

In [130]:
# ============================================================
# Verify Exported Dataset Deliverables
# ============================================================

verification_records = []
verified_exports = {}

for dataset_name, details in (
    final_dataset_deliverables.items()
):

    file_path = details["file_path"]
    expected_dataset = details["dataset"]
    parse_dates = details["parse_dates"]

    # Confirm that the file exists and contains data.
    file_exists = file_path.exists()

    file_size_bytes = (
        file_path.stat().st_size
        if file_exists
        else 0
    )

    assert file_exists, (
        f"Exported file is missing: {file_path}."
    )

    assert file_size_bytes > 0, (
        f"Exported file is empty: {file_path}."
    )

    # Reload the exported dataset.
    exported_dataset = pd.read_csv(
        file_path,
        parse_dates=parse_dates
    )

    verified_exports[dataset_name] = exported_dataset

    # Compare exported and expected structures.
    row_count_match = (
        len(exported_dataset)
        == len(expected_dataset)
    )

    column_structure_match = (
        exported_dataset.columns.tolist()
        == expected_dataset.columns.tolist()
    )

    exported_missing_values = (
        exported_dataset
        .isna()
        .sum()
        .sum()
    )

    expected_missing_values = (
        expected_dataset
        .isna()
        .sum()
        .sum()
    )

    missing_value_count_match = (
        exported_missing_values
        == expected_missing_values
    )

    verification_passed = all([
        row_count_match,
        column_structure_match,
        missing_value_count_match
    ])

    assert row_count_match, (
        f"{dataset_name} row count changed after export."
    )

    assert column_structure_match, (
        f"{dataset_name} schema changed after export."
    )

    assert missing_value_count_match, (
        f"{dataset_name} missing-value count "
        "changed after export."
    )

    verification_records.append({
        "Dataset": dataset_name,
        "File Name": details["file_name"],
        "Rows": exported_dataset.shape[0],
        "Columns": exported_dataset.shape[1],
        "File Size (MB)": round(
            file_size_bytes / (1024 ** 2),
            2
        ),
        "Status": (
            "Passed"
            if verification_passed
            else "Failed"
        )
    })

verification_summary = pd.DataFrame(
    verification_records
)

print("✅ Exported dataset files verified successfully.\n")

display(
    verification_summary
)

✅ Exported dataset files verified successfully.

                      Dataset                      File Name    Rows  Columns  File Size (MB)  Status
0         Sales Daily Dataset          sales_daily_final.csv  573900        6           24.41  Passed
1            Calendar Dataset             calendar_final.csv    1969       22            0.15  Passed
2          SKU Master Dataset           sku_master_final.csv   30490       16            3.66  Passed
3  Inventory Snapshot Dataset  inventory_snapshots_final.csv  573900       17           42.30  Passed

#### ✅ Validation Result

All four exported CSV files were found and verified successfully.

Each file preserved its expected row count, schema, and missing-value structure and is available for downstream notebooks.

# ✅ 14. Notebook Conclusion

Notebook 01 completed the data-engineering and validation foundation for Project FORESIGHT.

Raw sales, calendar, pricing, and product data were transformed into four standardized analytical datasets. The final outputs were validated, exported, and verified for downstream use.

## 14.1 Notebook Achievements

Notebook 01 successfully:

- standardized identifiers, dates, schemas, and business measures;
- engineered daily sales, Calendar, and SKU Master datasets;
- created a documented inventory simulation using historical demand;
- validated structural and cross-dataset integrity;
- exported and verified four final CSV deliverables.

The complete data foundation is ready for analytical use.

## 14.2 Datasets Generated

| Dataset | Purpose |
|---|---|
| **Sales Daily Dataset** | Daily SKU-level demand, revenue, price, and promotion records. |
| **Calendar Dataset** | Date attributes, events, seasons, weekends, and SNAP indicators. |
| **SKU Master Dataset** | Canonical SKU-store reference containing hierarchy, lifecycle, pricing, estimated cost, margin, and status attributes. |
| **Inventory Snapshot Dataset** | Simulated daily stock movements, replenishment activity, inventory status, estimated inventory value, and days of supply. |

Together, these datasets form the validated analytical model for Project FORESIGHT.

## 14.3 Readiness for Notebook 02

All required datasets are available, structurally valid, internally consistent, and successfully exported.

Project FORESIGHT is ready to proceed to Notebook 02 for exploratory data analysis, visualization, and business-insight development.

> **Key Takeaway**
>
> Notebook 01 transformed the raw project data into a validated and reusable analytical foundation.
>
> The final datasets are ready to support exploratory analysis, demand forecasting, simulated inventory analysis, and business decision-making in the remaining Project FORESIGHT notebooks.